### ISSUE TITLE
Interview Script for Power Users

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#104]
We need an interview script for power users to guide us in finding out broader issues the users may be facing.
The questions will have a topic centric structure where we start by asking the user to take us through a typical flow through interacting with DataBC overall.
The interview will contain some specific questions to which we want answers in addition to the reactive opportunistic deeper dive during the session.

> [5/19 1:39 PM] Decker, Brittany CITZ:EX
>     Hi- for power users, it would be same as New UX/UI script but the difference is that users can drive themselves not a guided tour of mock ups- it would actually be in the production.
[5/19 1:43 PM] Decker, Brittany CITZ:EX
    Yes, it is 4 people that are super high level BCDC users who we will save and do really in depth ux/ui with them- most likely Dan would rip through your UX/UI in 20mins in prod.  opportunity to test changes to UX/UI in new that we make as a result of input from previous rounds.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Should we keep this issue open, or do you want me to close it?

**Comment by yuisotozaki** [comment]
The script content will be stored in the [Design OneNote](https://bcgov.sharepoint.com/teams/00108/_layouts/15/Doc.aspx?sourcedoc={ba0484ba-7538-4891-b6f2-ef74533495ba}&action=edit&wd=target%28Usability%20Testing.one%7Cb3e90e80-2c97-424e-af89-37e3eede6473%2FInterview%20Script%20for%20Power%20Users%7Cf72c0e28-51e6-4d32-a5a4-f106cd5aaf71%2F%29&wdorigin=703) doc.
