### ISSUE TITLE
Expand/Collapse All only works with facets that have already been toggled

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckan-ui#116]
On the dataset list page the expand and collapse all buttons don't work unless you have already toggled the facet and only the ones that are toggled previously will change. Note that the states of all toggled facets are stored in local storage so only logging out or deleting local storage will give you a clean load.

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger on September 11.  All toggles working properly.  Closing ticket.
