### ISSUE TITLE
State doesn't show value

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckan-ui#117]
State and more generally all selects, don't show the actual value of the dataset when they are set to something invalid, this is particularly noticeable with state as their are examples of ARCHIVED which isn't a recognized state.

Change it so that selects will show the value either way in the view mode, but put out an error message below if the user is a sysadmin so they know that the value isn't valid

**Comment by SteveChapmanBCDX** [comment]
Done.  Closing.
