### ISSUE TITLE
Add links to pitch cards

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#119]
1. Link the "Browse thousands of …" pitch card to an empty search that results in the latest data at the top 
2. Link the "Log in with IDIR …" pitch card to the log in service 
3. Change the text on "Log in with IDIR ..." pitch card to read "Login with BC government ID and access additional data"

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Can we link this ticket directly to a sentiment from user testing?  For these and the rest in this set, it would be great to flag them as "User Tester Feedback" issues (or some similar label) and include the specific feedback that generated the issue.

**Comment by yuisotozaki** [comment]
Result of [Landing Page Recommendations](https://bcgov.sharepoint.com/teams/00108/_layouts/15/Doc.aspx?sourcedoc={ba0484ba-7538-4891-b6f2-ef74533495ba}&action=edit&wd=target%28Usability%20Findings.one%7C7f610107-db5a-4a1c-bbe8-a9bf3640af2d%2F2.1%20Landing%20Page%7C30f190fe-a9e5-4c8a-9802-87817ede151d%2F%29&wdorigin=703).

**Comment by yuisotozaki** [comment]
Issue closed. Work addressed in #121 .
