### ISSUE TITLE
Discuss with CE the content of one of the pitch cards for client engagement

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#120]
Client Engagement support required for this ticket.
Change the content of the 'Download data in a wide …" pitch card to "What's New at Data Catalogue?", and link to a popover content that showcases news, contact, and other client engagement content.
Make this card the left most card.

**Comment by yuisotozaki** [comment]
![image](https://user-images.githubusercontent.com/56084999/86623432-70ef5280-bf76-11ea-8e75-1e41ca4e5bf7.png)

From consumer user, editor users, and the quick demo, we had some comments and questions that kept coming up.
They are:

1. The pitch cards are nice - it reminds me that I need to login to see some datasets
2. Do I click on the cards to log in with IDIR?
3. Should we say "government ID" rather than IDIR?
4. Stating that some datasets require government ID to access may be perceived as "government is hiding data" - can we mitigate that kind of interpretation?
5. What's the difference between "browse thousands of ..." and "download data ..." cards?

**Comment by yuisotozaki** [comment]
From design point of view, here are some proposed improvements
Questions 2 to 5 all require additional content to make it perfectly clear what is being pitched. To address that, we can add a "Learn more" link on each card, allowing the users to quickly learn more about each pitch.

For the "Browse thousands of ..." card, a popup containing plain language version of what is DataBC and how the catalogue helps users find the dataset is recommended.

For the "Download data ..." card, a popup containing a plan language explanation of what resource types users can expect is recommended.

For the "Login with BC ..." card, a popup containing an explanation with links to additional material that explains why some datasets are behind government login is recommended.

**Comment by yuisotozaki** [comment]
July 7th Discussion with PO/CE team.

Pitch 1: Browse and download data
Pitch 2: Log in with government ID to access editor views
Pitch 3: Access groups
(Work on pitch labels to improve conciseness)

**Comment by yuisotozaki** [comment]
Updated design here
* Update label as in design
* Swap icons between the card on the left and the card in the centre
![image](https://user-images.githubusercontent.com/56084999/86952553-079f4900-c108-11ea-95a7-7b710418b626.png)

**Comment by BrandonSharratt** [comment]
Is this still relevant?

**Comment by yuisotozaki** [comment]
This is superseded by #208 .
