### ISSUE TITLE
Improve the clarity of login status in the header 

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#121]
Improve the clarity of login status in the header by using an alternate user icon.

**Comment by yuisotozaki** [comment]
![image](https://user-images.githubusercontent.com/56084999/86625842-a0a05980-bf7a-11ea-9391-265b2f134a0b.png)

![image](https://user-images.githubusercontent.com/56084999/86626175-30460800-bf7b-11ea-91a9-49c897381274.png)

1. Bold the "Log in" and "Add Dataset" labels
2. Shorten the "Francais" link to "FR" and keep their font weight at normal

**Comment by BrandonSharratt** [comment]
Done

**Comment by SteveChapmanBCDX** [comment]
Commit #9fddee3c5e4b74b274e00f5524ca713a1cacb28f - August 7.
