### ISSUE TITLE
Reorganize the menu content

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#122]
Reorganize the three-bar menu items so that similar content are visually together.
E.g. About and What is DataBC.

<img width="427" alt="Screen Shot 2020-06-16 at 6 51 51 AM" src="https://user-images.githubusercontent.com/36771389/84783384-0b72fc00-af9e-11ea-974d-1e3420e5bc66.png">

**Comment by yuisotozaki** [comment]
**Datasets** Rename to "Data Catalogue Home" to help users gain context
**Organizations** Rename to "Search by Organization" to help users understand the purpose of this menu item
**Groups** Rename to "Explore Dataset Groups" to encourage users learning about groups
**Subscribe to New Data** No change as we don't have a replacement mechanism envisioned
**Subscribe to Blog Posts** Remove this option as the DataBC blog has not been updated for two years
**About** Rename to "About Data Catalogue" to help users with context

**What is DataBC?** No change
**Geographic Services** No change
**Blog** Remove this menu item for same reason as above
**Developers** Remove this menu item as it links to BC DevExchange and is not 
**Contact** Rename to Contact DataBC to help users understand whom they are contacting

**Comment by SteveChapmanBCDX** [comment]
Done.  Closing ticket.
