### ISSUE TITLE
Support for a clear 'Home' behaviour in the header

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#124]
The users often clicked on the BC provincial mark in an attempt to go back to the Data Catalogue home page, only to be confused that they were directed to BC government website.
- Redirect the user click on the BC provincial mark to the Data Catalogue home page. (This is also a recommended approach on the BC Dev Exchange) https://developer.gov.bc.ca/Header-Basic

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger.  Closing issue.
