### ISSUE TITLE
Datasets View - Incorporate the groups in a filter in the main search 

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#126]
To support user awareness of groups, incorporate the groups in a filter in the main search, sorted alphabetically.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - To be clear, users recommend that we add an additional "Groups" filter to the list of existing search page filters (e.g., "Licenses", "Data Types", "Download Permissions", "Organization")?

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX That's correct. To help users learn about and search by groups, the recommendation is to add Groups to the existing filters.
*The order of filters will be revisited after looking at the survey results.

**Comment by yuisotozaki** [comment]
Updated Design
![Datasets View - Desktop](https://user-images.githubusercontent.com/56084999/87182488-179a6280-c299-11ea-834e-81f2f35c609a.png)

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger - closing issue.
