### ISSUE TITLE
Datasets View - Add a quick download feature on the results (Datasets view)

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#128]
Technical users simply want to download the layers and see the content themselves.
Add a quick download feature on the results on the datasets view.

**\*\*\*Disregard all comments below before July 3.  Yui clarified his thinking in his comment of July 3, 2020.\*\*\***

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Not sure at what level this feature would be.  

If on the datasets view, would this allow downloading of all underlying resources for N datasets?  If so, that could be a lot of data (depending on value of N and number of resources related to the N datasets).

If on dataset view, then would be resources associated with just a single data record.  That would relatively easy to achieve.

**Comment by yuisotozaki** [comment]
It's for the datasets view to cater to more technical users.
Currently these users would open multiple search results on separate tabs and download the resources anyway. We can facilitate this use case by adding links to the resources on each search result.
Another way to address this is to design a 'quick view' that shows a condensed version of the dataset view with links to download the resources.
In either case, this is definitely a design work that requires iterative approach.

**Comment by yuisotozaki** [comment]
Going over the notes again, the technical users who behave in this manner typically open multiple results on their browser tabs using Ctrl-Click.

Rather than making the result page complex, harder to maintain, and slowing the load time, we will update the Dataset View's Resources section to have separate buttons for preview, download, and request access.

This will have multiple benefits:
1. Non-technical users' experiences are not affected
2. Keeps the Datasets view code simpler
3. Technical users can ctrl-click the multiple results they're interested in, then directly click on download buttons on the resources

**Comment by BrandonSharratt** [comment]
This happened as part of another ticket
