### ISSUE TITLE
Phase 3 - Dataset View - Design Revision

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#130]
Based on the user [survey results,](https://bcgov.sharepoint.com/teams/00108/_layouts/15/Doc.aspx?sourcedoc={ba0484ba-7538-4891-b6f2-ef74533495ba}&action=edit&wd=target%28Usability%20Testing%20Findings.one%7C7f610107-db5a-4a1c-bbe8-a9bf3640af2d%2F4.0%20Survey%20Findings%7C380f766a-3ddb-4830-a657-20481abc5d29%2F%29&wdorigin=703) we want reorder the fields on the Dataset view.

**Comment by yuisotozaki** [comment]
Based on the user [survey results,](https://bcgov.sharepoint.com/teams/00108/_layouts/15/Doc.aspx?sourcedoc={ba0484ba-7538-4891-b6f2-ef74533495ba}&action=edit&wd=target%28Usability%20Testing%20Findings.one%7C7f610107-db5a-4a1c-bbe8-a9bf3640af2d%2F4.0%20Survey%20Findings%7C380f766a-3ddb-4830-a657-20481abc5d29%2F%29&wdorigin=703) we want reorder the fields on the Dataset view.

**Comment by yuisotozaki** [comment]
Updated Dataset Field Order

- Title
- Description
- Purpose
- Organization
- Contacts
- State
- Data Currency/Update
- Data Quality
- More Info
- Keywords
- Lineage Statement
- Who can view this data
- Who can view this record
- Who can download this data
- Licence
- Security Classification

![Uploading Dataset View - Desktop.png…]()

**Comment by yuisotozaki** [comment]
Updated Resource Field Order
(remove Type, Resource Type, and Retention Expiry Date fields)
* Name (in larger bold text like on Dataset view)
* Resource Description
* Supplemental Information
* Resource Storage Format
* Resource Access Method
* Resource Storage Location
* Source Data Path
* Resource Update Cycle
* Resource Status
* Replacement Records
* Temporal Extent
* Geographic Extent
* Projection Name
* Spatial Data Type
* ISO Topic Category
* JSON Table Schema
* Object Name
* Object Short Name
* Object Table Comments
* Details

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger.  The navigation bar has been implemented.

Work remaining:
* Reorganize left-column fields per Yui's design;
* Recode cards in right-column resources list per Yui's design

**Comment by SteveChapmanBCDX** [comment]
Testing navigation bar in Toyger.

Comments:
* Could not add a record to a group

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger.  Closing ticket.
