### ISSUE TITLE
Phase 3 - Dataset View, Resource View - Add helper popups (tooltips)

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#131]
Implement the Helper Popups for each field with helpful content.
Content needs to come from the business.

**Comment by BrandonSharratt** [comment]
the ui supports the json having a helper_text field which will render as a tooltip

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - Thanks for that information.  I'll have the team determine the required content for each field.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @yuisotozaki.

Recommendations:
* Yui and Steve to identify all fields
* Yui and Steve to identify fields that require tooltips
* Yui and Steve to prioritize highest value fields => Contacts, Dataset States
* DDS Team to add content
* Tooltips to be introduced in batches (by priority)

**Comment by TerryLanktree** [comment]
@annikaLiving  This is being worked on by team, shall we just close?

**Comment by TerryLanktree** [comment]
Covered by #428
