### ISSUE TITLE
Contact BCDC - Unify the contact point

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#134]
Many users showed confusion over who to contact at DataBC for what purpose. "Request New Data", was especially confusing to the users.

1. Unify the Data Request and Contact flows so that there is only a single way the users contact DataBC.
2. Improve the Contact form preamble by providing an FAQ or stepped flow for the users to be able to contact the right people.
3. Improve the perception of responsiveness and ease of contact by adopting a modern layout for the forms; e.g. using a popover or flyout instead of redirecting to a separate page improves the sense of responsiveness as the user can still see that they have not left their current page/context.

**Comment by yuisotozaki** [comment]
July 7, 2020
* Provide clear ways to contact custodians (data related) vs DataBC(site related) in the new UI
* Further discussions and brainstorming required based on the CE team's contact stream analysis effort

**Comment by BrandonSharratt** [comment]
This is not in the ckan ui, it is seperate

**Comment by yuisotozaki** [comment]
This will need to be tracked in the internal JIRA board for DPS team.

**Comment by SteveChapmanBCDX** [comment]
Migrated ticket to DDM Jira project => https://proj.data.gov.bc.ca/jira/browse/DDM-2593.

Closing this ticket.
