### ISSUE TITLE
Group/Org Permalink not working

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckan-ui#137]
On a direct load or a page refresh the "Copy Permalink" for a group or individual org page doesn't work properly, as it has `undefined` for the id.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - It looks like this has been fixed.  Can you link to PR or commit?

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt  - I can still reproduce this issue in Toyger.  I don't think the code change has been committed.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt  and I tested in Toyger.  Neither of us could reproduce this issue.  Closing as "cannot reproduce".
