### ISSUE TITLE
Compile CE Q&A document from user interviews (DDS-950)

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#142]
The client engagement team had a number of questions for the users during the interviews.
These notes are still contained separately across all interviews and is not easily analyzed.
Compile the notes into an easily consumable format in the OneNote document.

**Comment by sheilamv** [comment]
https://dpdd.atlassian.net/browse/DDS-950

**Comment by sheilamv** [comment]
https://dpdd.atlassian.net/browse/DDS-950

@TerryLanktree , is this still a task you'd like to be done, or should we start from ground zero post implementation?

**Comment by TerryLanktree** [comment]
I don't read this as the same task as dds-950.  I read this as Yui consolidating his documents into onenote.  His work is on Teams, note sure how easy it is to navigate, I find it's simply a lot of information.  This was used to create the current interface, so I will close this ticket.
