### ISSUE TITLE
Standardize Dataset Security Level with Government Security Classifications

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#144]
Consider standardizing the security levels with government information security classifications.
Editor users are often confused by the Security levels in dataset since the options are not the same as the standard government [Information Security Classifications](https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/information-security/information-security-classification).

**Comment by BrandonSharratt** [comment]
This is a big change that would require a db migration, in order to ensure that that is what we want I would want confirmation from Mike/Annika/Steve

**Comment by pumapants** [comment]
**Security Classification Mapping**:

**New / Old**
PUBLIC = LOW-PUBLIC
PROTECTED A = LOW-SENSITIVITY
PROTECTED B = MEDIUM-SENSITIVITY, MEDIUM-PERSONAL
PROTECTED C = HIGH-CONFIDENTIAL, HIGH-SENSITIVITY

**or**
   when 'HIGH-CABINET' then 'PROTECTED C'
        when 'HIGH-CONFIDENTIAL' then 'PROTECTED C'
        when 'HIGH-SENSITIVITY' then 'PROTECTED C'
        when 'MEDIUM-PERSONAL' then 'PROTECTED B'
        when 'MEDIUM-SENSITIVITY' then 'PROTECTED B'
        when 'LOW-PUBLIC' then 'PUBLIC'
        when 'LOW-SENSITIVITY' then 'PROTECTED A'
        else null

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/5

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - Does this mean we will also need to modify John's database conversion script?  Or does your change to the schema do that?

**Comment by SteveChapmanBCDX** [comment]
Confirm in Toyger.

**Comment by pumapants** [comment]
@SteveChapmanBCDX I confirmed that last week that these where indeed in toyger. I still wanted to check the import to ensure the conversion worked.

**Comment by SteveChapmanBCDX** [comment]
@pumapants - For sure - I'll test in Toyger and report back here.  I'll leave the ticket open for you to test and close.

**Comment by SteveChapmanBCDX** [comment]
Reviewed the changes in Toyger.

Summary:
* Reviewed tickets that used each of the four new security levels; and
* Modified an existing ticket's security level; and  
* Created new ticket with a selected security level

@pumapants  - I'll reassign to you for review and signoff.

**Comment by annikaLiving** [comment]
I have confirmed that all but 2 records have transferred correctly but as this is a cut of the data from a ~month ago. tjese could have changed in prod as i know the client has been looking and reviewing his datasets.

d28f6f88-b90e-471c-b5a5-da1d00c1e61e
21869ad1-ed7f-45fe-9337-9deb78009ea5
