### ISSUE TITLE
Phase 3 - Ensure Dataset Deletion Option is Available to Admin Users Only

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#145]
Double check and document editor and admin access levels to dataset deletion action.

**Comment by BrandonSharratt** [comment]
I tested this and can't reproduce

**Comment by pumapants** [comment]
Editors and Admin should be able to do the same thing:

1) Both can only delete records in a DRAFT State.
2) Both can delete resources in any State.

Deleting records is not encouraged.

**Comment by SteveChapmanBCDX** [comment]
This issue relates to the "Dataset Life Cycle" issue in the DDS Jira project (DDS-235).
