### ISSUE TITLE
Phase 3 - Improve the layout in Edit Dataset view by hiding the Resources section

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#146]
Improve the layout in Edit Dataset view by hiding the Resources section to focus the user's attention to the fields.

**Comment by yuisotozaki** [comment]
Updated Design for Edit Dataset view
- All right hand side elements are hidden

![Dataset View Admin Edit - Desktop](https://user-images.githubusercontent.com/56084999/87342543-49613280-c500-11ea-8178-4965c7398d03.png)

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger - Resources List still renders when editing or creating a record.

@BrandonSharratt - Can you review?

**Comment by BrandonSharratt** [comment]
Should be fixed in PR https://github.com/bcgov/ckan-ui/pull/221

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger - closing ticket.
