### ISSUE TITLE
Phase 3 - Sort the contents of the drop down fields

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#147]
In edit mode, sort the content of the drop down options fields so that they make sense: 
E.g.
- Status lists should be sorted in the order the status life cycle works 
- Alphanumeric for organizations list 
- Etc.

**Comment by BrandonSharratt** [comment]
Changed type to be workflow sorted (ish rejected doesn't super fit in)
most of the others were already alpha except org as it's populated by an api call which I've now added a manual sort to

**Comment by SteveChapmanBCDX** [comment]
> Changed type to be workflow sorted (ish rejected doesn't super fit in)
> most of the others were already alpha except org as it's populated by an api call which I've now added a manual sort to

@BrandonSharratt  - Can you clarify your first comment above?  I noticed that we haven't made any changes to reorganized status lists around status life cycles.  Was your comment aimed at addressing that?
