### ISSUE TITLE
"Data Currency/Update" terminology is unintuitive - Consider replacement

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#149]
Users, even technically adept editor users, found the term "Data Currency/Update" and "Date Type" confusing.
![image](https://user-images.githubusercontent.com/56084999/87336711-22eac980-c4f7-11ea-82f4-1b0d20550f1d.png)

Consider replacing these with other terminology.
Suggestions:
- Field Set Title: Dataset Status, Field Titles: Status, Date
- Field Set Title: Dataset History, Field Titles: Change, Date

**Comment by BrandonSharratt** [comment]
Which would we like to go with?

**Comment by yuisotozaki** [comment]
Maybe a combination like this?

Dataset Status History
   Date of Change
   Status

We'll need to pass this terminology by Annika/Mike as it's a significant departure from the previous label set.
What do you think @SteveChapmanBCDX

**Comment by SteveChapmanBCDX** [comment]
Agree that "Date Type" is weird.  I like @yuisotozaki's formulation above (Dataset Status History/Date of Change/Status).  Let's go with that.

The history log makes sense then.  The user can track the dataset's status from "Published" through one/many "Modified" events and finally to "Archived" or "Destroyed".

It would be great if the "Modified" event provided more information (what exactly was modified?), but that's a different issue altogether.

**Comment by yuisotozaki** [comment]
As of 2020-Dec-16 toyger shows updated label.
![image](https://user-images.githubusercontent.com/56084999/102398629-652ba180-3f94-11eb-8409-2bb24e797a20.png)

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @yuisotozaki.

Recommendation:  This ties in the bigger issue of data currency and how we inform users about changes to both data and metadata.  Let's review this issue as soon as possible following MVP release.

**Comment by sheilamv** [comment]
This was implemented as Record Lifecycle History with Type and Date labels.  Closing this ticket.
