### ISSUE TITLE
Improve More Info field to give it a text label

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#150]
Improve More Info fields so that they have a text label and the link itself so that the editors can display the name of the target link rather than just the links.

Updated Design - View Mode
- Display all description text
- Truncate the URL to one line
![image](https://user-images.githubusercontent.com/56084999/87340593-1f5a4100-c4fd-11ea-8cbe-112bf59cdb8c.png)

Updated Design - Edit Mode
- Description can be about 200 characters max
![image](https://user-images.githubusercontent.com/56084999/87340692-4c0e5880-c4fd-11ea-9759-9c398f01295e.png)

**Comment by BrandonSharratt** [comment]
More info is a composite repeating field, what do we want to do for old fields that don't have a description?

**Comment by yuisotozaki** [comment]
That makes sense to me! Hide description if it doesn't contain a value.

**Comment by SteveChapmanBCDX** [comment]
Agree with that recommendation - Hide the description field if no value.

**Comment by BrandonSharratt** [comment]
rolled the fix for this into https://github.com/bcgov/ckan-ui/pull/332

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger version `35570d3`.  Closing ticket.
