### ISSUE TITLE
Improve the Add/Edit Resource view's URL/File field element

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#152]
Users found that the Add/Edit Resource view's URL/File field toggle + URL/File field combination very confusing.

Proposed Design
- Use radio buttons for URL vs File selection
- When URL selected, show URL field
- When File selected, show File name field with placeholder text that guides users for next step
- When File field clicked, open system file browser dialog
- When file selected, attach and display the file name in the field with an option to remove the attached file using 'X' at the right hand end of the field
![image](https://user-images.githubusercontent.com/56084999/87348674-fdb38680-c509-11ea-83d0-0cc9938bea69.png)

**Comment by SteveChapmanBCDX** [comment]
The workflow is great for adding a file.  It's really intuitive and straightforward.

For adding a URL, I wonder if we want to change the prompt from "Resource Type" to "URL" or "Enter URL".  I changed it to "Enter URL", and I thought that looked pretty good.

@BrandonSharratt, @yuisotozaki - Your thoughts?

**Comment by pumapants** [comment]
Thumbs up on this! Resource Type look like a header and TL could not find where to put the URL.

**Comment by yuisotozaki** [comment]
February recommendation for tweaks to better guide the user (new and old) through the form.
![cap](https://user-images.githubusercontent.com/56084999/107797008-4be26f80-6d0f-11eb-8f91-3f11da22190f.png)

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Thanks, that recommendation looks good.

@BrandonSharratt - Reassigning to you - let's implement Yui's recommendation.

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger - fix implemented.
