### ISSUE TITLE
Clarify Contact Information section for consumer users

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#157]
**Story**
As a consumer, I need to be able to click a link and directly email a Contact type associated with a data record. Contacts types should be organized to allow me to figure out who to contact (e.g. report an error about the data, ask a question, request access)

**Design**
- We already have a `mailto` link on the contact's email address - ensure that this is reflected in the new UI.
- When adding the (?) icon to describe the Contact Information band, include in the description what each contact  type if for.

**Comment by BrandonSharratt** [comment]
The new UI already has the mailto link, and the latter part is better off in the ticket for adding help text

**Comment by SteveChapmanBCDX** [comment]
I need to review this issue.  I'm not sure if we can close this yet.

We need to ensure we address the issues that @yuisotozaki raised above to ensure that users can:
* Report errors
* Asks questions
* Request access

**Comment by BrandonSharratt** [comment]
@SteveChapmanBCDX I'm going to close this issue again because as this issue is worded it is complete, I believe what you are talking about would be an entirely new ticket

**Comment by SteveChapmanBCDX** [comment]
We can't close this yet, as the fundamental question raised in my comment of November 17th hasn't been answered yet.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @yuisotozaki.  Closing this ticket.  Opening related ticket #283.
