### ISSUE TITLE
Phase 3 - Remove 'FR' link from the header

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#161]
As the content is not bilingual, having 'FR' link in the header may set false expectations.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @BrandonSharratt - let's review further with @yuisotozaki.

**Comment by cpspicer** [comment]
What is the ultimate goal:  to remove, or make less visible?  **Move to hamburger (primary suggestion).**

**Comment by yuisotozaki** [comment]
To remove the option altogether since we cannot offer a good bilingual solution. Not having multi-language support is on par with existing cat (albeit there's a URL hack to make it happen).

**Comment by SteveChapmanBCDX** [comment]
If DDS decides to remove the link for now and reconsider it later, Brandon's work won't be wasted. He's created a French dictionary that could updated later.  This dictionary also provides a general pattern for internationalization if we decide to support other languages down the road.

**Comment by BrandonSharratt** [comment]
@yuisotozaki both of those statements are not true. catalogue.data.gov.bc.ca/fr The new UI already translates more than this. and there is no good way to translate user generated content so we are already doing the best a page can do unless there is some new ML api out there that I am unaware of for free translations (mostly looking at the free realm as google has an api but it charges for each api call after the first 50)

**Comment by yuisotozaki** [comment]
@BrandonSharratt Toyger definitely does far more than the current catalogue and the current catalogue does have an ML _functionality_. I wanted to emphasize that the _feature_ does not exist in the current catalogue. That is, the production catalogue doesn't have a designed UX around switching languages like a button or dropdown for the user to a) be aware of the feature and b) be able to do this without editing the URL themselves. The FR feature was part of the design work for BCDC 2.0 originally thinking that it's as easy as flipping a toggle; the design team was sadly mistaken.

Here are my observations on the ML feature on toyger version: 1.9.0-8f55cfa:
When FR link is clicked:
* Field labels are translated.
* Pre-defined values (like dropdown values) are translated (both Edit and View mode)
* User entered text field are not translated.
* Some labels are strangely translated like "Organizations" to "Le organisations" and sometimes "Les Organisations", and "Description" to "La Description"
* "Download" and "View" on Resource list are not translated.
* "Successfully Deleted" confirmation text is not translated.
* "You are viewing a deleted dataset" text is not translated.
* On Add Dataset view, "Please fix the fields in error before submitting" is not translated
* On Add Dataset view, each field validation phrase is not translated while the field labels are. E.g. "Titre* is required."
* "Permalink URL Copied to Clipboard" is translated.
* Content of "File Types" card is translated but the content of About is not.
* When navigating to the landing page, "/fr" does not stay in the URL.
* On Organization view, the parent link to "Organizations" does not translate.
* On Group view, the parent link to "Groups" does not translate.
* On Group view, the search field placeholder text does not translate (Organization view's search field placeholder does translate)
* The landing page UI's cards do not react to longer text in alt-language leading to text overflow from the cards.

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger.  Application toggles properly between English and French.

Closing ticket.

Noted that the French versions of certain UI elements need to be restyled.

For example:
<img width="861" alt="Screen Shot 2021-03-01 at 4 17 04 PM" src="https://user-images.githubusercontent.com/36771389/109577057-ce0dba80-7aa9-11eb-82d3-ba8bfc4ad082.png">

Writing up separate ticket for this issue.
