### ISSUE TITLE
Increase usability of dataset entry

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckan-ui#164]
When entering datasets it would be nice if

1) If url hasn't been set it gets set to what the title is (lowercased and hypened)
2) If a contact org hasn't been set it defaults to what the dataset org is assuming the dataset has one
3) If a contact is added and the dataset has an org the new contact should default to that org.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - Did you push these changes?

**Comment by SteveChapmanBCDX** [comment]
Changes implemented and tested in Toyger.  Closing ticket.
