### ISSUE TITLE
Organization View Issues

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#168]
**Datasets for an organization**
See https://toyger.data.gov.bc.ca/organization/agricultural-land-commission

- "learn more about this organization" members list shouldn't be shown if you are not logged in.
- Organization image is missing
- Organization description is missing
- Facet choices on right should be restricted to the ones that pertain to the datasets in the organization. And numbers should appear next to the org labels and the facet labels.
- Date formats are messed up and Data Types value is missing
- Organization view at a top-level should show datasets from sub-organizations

**Comment by BrandonSharratt** [comment]
- Learn more about this org ... The member list is retrievable when not logged in via api, However I'll hide it in the UI I'lm also hiding the Add member button as the UI wasn't designed

- I believe this is actually do to the image urls being broken (pointing to non existent images) in local/dev/test/stage however I've made the logic to show the placeholder instead more verbose

- I see the description

- unclear what you mean on data formats / data types I see them

- Facets are very restrictive I'll do a bit of a dig into the 2 on that (org view at parent should show sub and facets on the right)

**Comment by yuisotozaki** [comment]
The following issues are no longer observed.
- Organization image is missing
- Organization description is missing
- Date formats are messed up and Data Types value is missing

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger version `35570d3`.  

All work completed except:
* Facet choices on right should be restricted to the ones that pertain to the datasets in the organization. And numbers should appear next to the org labels and the facet labels.

@yuisotozaki - I'll create a new ticket for remaining issue.
