### ISSUE TITLE
Add Dataset Issues

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#169]
- When adding a dataset, State has to be Draft - other choices shouldn't be allowed.
- URL should be populated from the Title
- In Contacts section, the organization list is populated, but the content is not well organized. Both parent and sub orgs in the are in the list but very difficult for a user to find their branch. Would be good to be able to see the hierarchy.

Additional findings August 25, 2020
- Text fields starting with More Info URL loses focus after every single keystroke
- Save takes over 10 seconds with no indication that it is doing something -- **DONE - Spinner added**
- After a successful dataset creation, pressing Add Dataset again does not take the user to the Add Dataset form

**Comment by BrandonSharratt** [comment]
- State is currently just a select and not it's own special field which means it can't be restricted if we need this we need a seperate ticket for it
- URL should be populated from the title - I did this in another ticket
- Org list is populated by the orgs available to the user so if you are an editor for one org that is the only one you will see. We can investigate showing heirarchy but how do we want to show it

- More Info URL losing focus was fixed as part of a different ticket
- I've added a spinner to dataset, resource group and org that shows up when the form is disabled (deleting/saving)
- The navigiation after successful creation wasn't working so I fixed it and now
