### ISSUE TITLE
VueJS UI - Add/Edit Records (Dataset only) New UI

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#17]
@BrandonSharratt commented on [Thu Feb 28 2019](https://github.com/bcgov/ckanext-bcgov/issues/719)

See epic but for adding and editing records in the new ui

depends on the login functionality

**Comment by BrandonSharratt** [comment]
Includes group checking, and will only work with scheming so hooking up that

**Comment by ryleyw** [comment]
some bugs
**CREATE**
- should return to list page on cancel 
- when entering data in create dataset page or edit page, values are cached between them
**EDIT** 
- Infinite loading on create new resource no permissions to edit 
- deleting dataset w/o permission returns unformatted error 
- editing a package keeps edits until navigating away

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @BrandonSharratt  - Closing - work complete.
