### ISSUE TITLE
Search Engine Optimization - Ensure that this is at parity with existing website

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#170]
Reviewed this issue with @gjlawran.

Resources:
* https://catalogue.data.gov.bc.ca/sitemap.xml
* https://www.google.ca/webmasters/#?modal_active=none
* https://search.google.com/

@gjlawran says that we have an existing Google WebMasters account in PMP that we can leverage.

**Comment by gjlawran** [comment]
In addition to traditional site indexing / SEO we should also consider providing content accord to DCAT https://developers.google.com/search/docs/data-types/dataset 
there is CKAN extension. that makes this easy and should be planned for integration 
https://github.com/ckan/ckanext-dcat

**Comment by BrandonSharratt** [comment]
Sitemap wasn't working in the old extension given the schema changes, so that was fixed up and the sitemap and robots.txt files were added to the new ui in PR #200.

DCAT integration should be a new ticket.
