### ISSUE TITLE
Update Resource View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#184]
Updated Resource View Design
Notable Changes:
* Column orders have changed according to SME input.
* Buttons are now in a row just below the header. This row of buttons should remain visible even when scrolling.
* Permalink button is now called Share and clicking on it should copy the permalink to the user's clipboard and a notification should appear stating "Share link copied!". The notification should auto-dismiss in 3 seconds.* The name of the dataset it belongs to is shown above the resource title.
* For those with permission, Edit Resource, Add Resource, and Delete Resource buttons are shown
* Previous interactions such as "View in iMapBC" is now called "View in Advanced App" as per SME's recommendation but may still require further discussion.
* Other Resources section no longer show each resource as a card. The resources are visually separated by horizontal rules.
* For records with tables, we show a shrunken view on the left-hand-side.
* A new button "Expand View" button is provided for the shrunken views to show the content in full size using an overlay.

![Resource View - Desktop](https://user-images.githubusercontent.com/56084999/92145725-82fe3d80-edcd-11ea-85de-67d14648354b.png)

**Comment by BrandonSharratt** [comment]
having completed this and #130 many fields were left off of both designs, those fields will show up at the very bottom of the corresponding page. 

The main exception to this is resource type, as it affects the visibility of other fields on this page I have left it somewhere near the top (but below dataset title, resource name, resource url)

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger version `35570d3`.  All changes have been implemented.
