### ISSUE TITLE
Update box-shadow around the top half of the pitch cards

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#189]
Update the box-shadow of pitch-header class to box-shadow: 0 2px 2px rgba(0, 0, 0, 0.2);

Current look
![image](https://user-images.githubusercontent.com/56084999/92968249-a52c3700-f42f-11ea-9595-37cbf7cd3688.png)

Desired Look
![image](https://user-images.githubusercontent.com/56084999/92968334-c68d2300-f42f-11ea-939d-7164f1b22ee0.png)

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Please test in Toyger and close (assuming change made correctly).

**Comment by yuisotozaki** [comment]
Tested on Toyger - PASS.
