### ISSUE TITLE
Update the About page content to match production

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#195]
The production catalogue's `About` page content has been updated since the new UI designs were developed.
https://catalogue.data.gov.bc.ca/about

We want to update the new UI's `About` page content to match.

Acceptance Criteria
* The new UI has the same content
* The new UI has the same format
* The new UI has the same paragraph breaks

**Comment by SteveChapmanBCDX** [comment]
Let's hold off on this for now.  The `About` page in the current catalogue is pretty busy.  Let's review the content/design/UX and decide what changes (if any) are required.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - When able, please review the current ["About" page](https://catalogue.data.gov.bc.ca/about) and let me know your thoughts.  Perhaps an abridged version would work well for the new release.

**Comment by yuisotozaki** [comment]
I agree @SteveChapmanBCDX - let's go with the abridged version that's live on prod.
Just this part and making sure we include paragraph breaks.

> Welcome to the BC Data Catalogue (BCDC), a tool that helps users find, understand and explore data. The Catalogue describes over 3000 datasets, APIs, services and applications, and provides contact information so that data users can contact data custodians and other data experts to learn more.
> 
> The DataBC Program manages the BC Data Catalogue software and infrastructure, delivers user training and performs authorization management.
> 
> Data, APIs, Services and Applications registered and presented through the BC Data Catalogue are managed and provided by Custodians from across the Broader Public Sector (BPS). A Custodian is typically a Director or Executive Director of an organizational unit such as a Branch or Division. These Custodial organizations are visible under the Organizations tab.
> 
> The BC Data Catalogue is powered by CKAN.

**Comment by BrandonSharratt** [comment]
This is editable through the UI for sysadmins

**Comment by yuisotozaki** [comment]
@BrandonSharratt @SteveChapmanBCDX I will reach out to the team to handle the content. If they update the content on toyger, will the change persist to production when we go live? I.e. toyger isn't just test data?

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - good question - I assume that we'll have to reseed the text for Production, so we should establish what the text needs to be.

I think we should use the abridged version (your comment above, from Nov 23) for initial release.  If team wants to modify it later, then they can do that.

**Comment by BrandonSharratt** [comment]
It's a different database so prod and live have to be updated seperately

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @yuisotozaki.

Confirm that the change is persisting.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - I'm still seeing the single paragraph version of the "About" page on my machine (commit #85b4524).  I'm not sure that your change (using the UI) persisted.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Can you review this implementation.  I think we wanted to use the abridged version instead, but let me know what you think about using this version instead.  The version implemented here is the same that BCDC Prod is using right now.

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX I think the full version is fine as long as it can render properly. Looks like the tech is there but the content markdown source needs some work.
I think this means we can close this issue and pass this over to the team for editing the About text content for formatting.
We also want to make sure that the team's input will persist to production.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Thanks, that all sounds good.

Action (me):
* Close this ticket
* Open ticket for team to review "About" text content for formatting
* Open second ticket for Prod (ensure this version is added/persists in Prod).
