### ISSUE TITLE
Organization and Group view - Update with the new button bar just like the Dataset view

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#196]
We want to update the organization and group view with the same button bar as the updated Dataset view.
See below for design mockup.

**Organization View**
![Organization View - Desktop](https://user-images.githubusercontent.com/56084999/93148722-699ca180-f6a9-11ea-8233-aa355896af5b.png)

**Group View**
![Group View - Desktop](https://user-images.githubusercontent.com/56084999/93148728-6dc8bf00-f6a9-11ea-8a62-a14f5685fc26.png)

**Comment by BrandonSharratt** [comment]
The "Add a new dataset to this X" is new functionality that has not been added as it requires new dev that is not currently supported.

**Comment by yuisotozaki** [comment]
> The "Add a new dataset to this X" is new functionality that has not been added as it requires new dev that is not currently supported.

Understood!

**Comment by yuisotozaki** [comment]
Button bar was implemented at the top as described. Layout and margin tweaks to be addressed in #204 .

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger - closing ticket.
