### ISSUE TITLE
Phase 3 UI Update - Dataset View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#204]
- Introduce Scroll to top floating button when the screen is scrolled downwards
- Hide iMap link from the UI
- Remove Geographic Extent as the content is always the same
- Introduce resource description in the resources list
- Display button on the resource cards rather than having them in the ellipses
- Ensure button permissions are set properly
- Left align buttons with the field values
- Introduce a horizontal rule below between the button bar and the content
- Update Share button's toast label to 'Permalink URL Copied to Clipboard'
- Layout field label and values horizontally for fields likes 'who can view/access this record'

![Dataset View - Desktop](https://user-images.githubusercontent.com/56084999/94749822-99020e00-0339-11eb-9054-6a867e7273ac.png)

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger - closing ticket.
