### ISSUE TITLE
Phase 3 UI Update - Resource View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#205]
- Introduce Scroll to top floating button when the screen is scrolled downwards
- Layout field label and values horizontally for fields likes 'who can view/access this record'
- Introduce resource description in the resources list
- Rename 'Other Resources' to 'Other Resources on this Dataset'
- Update Share button's toast label to 'Permalink URL Copied to Clipboard'
- Use the same font size for title as dataset title on the dataset view
- If there are no other resources on this dataset, hide the 'Other Resources on this Dataset' section altogether

![Resource View - Desktop](https://user-images.githubusercontent.com/56084999/94601508-704e1b80-0248-11eb-88cc-70817b4d84aa.png)

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger - closing.
