### ISSUE TITLE
Update 'Groups' description

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#207]
Update the content of the text that describes what 'Groups' mean on Groups view so that it explains to the users what Groups are.

**Comment by yuisotozaki** [comment]
Text to be used.

"Groups are used to collect datasets for a particular project or on a particular theme. These groups are managed by DataBC Data Catalogue team."

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger - closing ticket.
