### ISSUE TITLE
Update the pitch card content and function

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#208]
Update the pitch cards since just about all users want to click on it to see what they do. 

**Card 1** 

Before: Browse thousands of government datasets 

Revision: Make the card clickable and send the user to ./datasets 

**Card 2** 

Before: Download data in a wide variety of file formats 

Revision: Make the card clickable and show an overlay of how to use the BCDC 

Text: Access data in a wide variety of formats 

Overlay Content: Example of formats and their uses 

**Card 3** 

Before: Login with IDIR and gain access to even more data 

Revision: Make the card clickable and send the user to the same login screen

**Comment by yuisotozaki** [comment]
Here's the content for the second card

Open Standard Data
**json** JavaScript Object Notation standard data file
**openapi-json** OpenAPI that returns data in JSON format

Geospatial Data
**arcgis_rest** ArcGIS REST API
**e00** ESRI ArcInfo interchange file
**fgdb** ESRI File Geodatabase format
**geojson** Open standard format representing simple geographical features
**kml** Google Earth file
**kmz** Keyhole Markup Language
**shp** ESRI Shapefile
**wms** Web Map Service

Tabular Data
**csv** Comma Separated Value
**xls** Microsoft Excel (97-2003)
**xlsx** Microsoft Excel (2007)

Documents
**html** Hypertext Markup Language
**pdf** Portable Document Format
**txt** Plain Text
**xml** Extensible Markup Language

Archives
**zip** Compressed Archive File

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger - closing ticket.
