### ISSUE TITLE
Search field and filter should be reset when switching views

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#211]
Search field should be reset to blank and filters cleared when navigating between major views:
* Home (./)
* Explore Datasets (./datasets)
* Explore by Organization (./organization)
* Explore by Groups (./groups)

When the user switches between these views, they are starting a new search rather than thinking "apply the same search field and filters in other views."

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @BrandonSharratt - need follow-on conversation with Yui to determine proper UX/logic here.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @yuisotozaki.

Let's use the logic that @yuisotozaki sets out in his first comment (comment of Oct 6).

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger - closing ticket.
