### ISSUE TITLE
Datasets View layout and colour correction

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#212]
To visually complete the datasets view:
* Top align the first search result and the filter set title
* Update the colouring of the filter criteria bands
![Datasets View - Desktop – 1.png](https://images.zenhubusercontent.com/5e3c6715d85e5dced833aef6/6cc47e47-81ce-4d5d-8ab9-030e09418d27)

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger - closing ticket.
