### ISSUE TITLE
BCDC QA:  Confirm top of page links 

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#219]
Duplicate of 161

### Story
**As a** public user (no login),
**I want to** be able to use the pages' links,
**so that** I can navigate to pages within or outside the catalogue 

Full test results can be found [here](https://bcgov.sharepoint.com/:x:/r/teams/00108/Shared%20Documents/PROD_BCDC/UIUX%20User%20Acceptance%20Testing/Templates/EDC_UAT_NewUI_SMV.xlsx?d=wa02da30961264f17b72e240c98a35074&csf=1&web=1&e=Z4b73J) on the Public (No Login) tab. 

### Steps to Reproduce

Precondition:  On https://toyger.data.gov.bc.ca/

|Case #|Step #|Description|Expected Outcome|Actual Outcome|Result|Comments|
|:---:|:---:|:---|:---|:---|:---:|:---|
|3|1|Select FR|System displays all labels on site and content of the datasets in French|Only labels changes, not content of datasets|**Fail**|This should be removed as the site is not bilingual.  Data sets are not translated into French, which is what a user selecting French would expect.  You can't search using a French word.  This needs to be removed until the need to become bilingual is a requirement. |
|3|2|Select Logo|System displays the official website of the Government of British Columbia (https://www2.gov.bc.ca/gov/content/home)|As expected|Pass|Hidden functionality that is not apparent to the user. Tested from homepage (refreshed)|
|3|3|Select **Data Catalogue** text|System to displays the B.C. Data Catalogue homepage|As expected|Pass|Confusing when selected from the homepage, but when on other pages, it returns as expected. |
|3|4|Select **Log In** text|System to display the log in page to capture IDIR/BCeID|As expected|Pass|For these tests, login is not required and was not completed.  Need to confirm if sso will be used to understand the impacts of a Government employee on Government issued hardware.
|3|5|Select _hamburger_ to view menu bar|System displays menu bar with eight (8) options|As expected|Pass||
|3|6|Select **Data Catalogue Home** submenu options under _hamburger_ to view menu bar|System return the user to the homepage of the Data Catalogue|As expected|Pass|Confusing when selected from the homepage, but when on other pages, it returns as expected. |
|3|7|Select **Explore Datasets** submenu options under _hamburger_ to view menu barr|System displays a list of Published and Pending Archived datasets on the dataset page|As expected|_Conditional Pass_|**NOTE**:  this page does not have a page header like the Organization and Groups pages have.  _UI inconsistency_.|
|3|8|Select **Explore by Organizations** submenu options under _hamburger_ to view menu bar|System displays a list of organizations (parent organizations on the organization page|As expected|Pass|I noticed that if the ministry name is too long, it wraps around but the section is not scalable and text is hidden (see Ministry of Forests, Lands, Natural Resource Operations and Rural Development.|
|3|9|Select **Explore by Dataset Groups** submenu options under _hamburger_ to view menu bar|System will display a list of groups with the number of datasets associated to each group on the groups page|As expected|Pass||
|3|10|Select **Subscribe to New Data** submenu options under _hamburger_ to view menu bar|System to present the user with a mechanism to subscribe to notifications using RSS??|<rss version="2.0"><channel><title> Province of British Columbia BC Data Catalogue RSS Feed </title><link>https://cati.data.gov.bc.ca/feeds/recent.rss</link><description> An RSS Feed of the contents of the Province of British Columbia's Data Catalogue </description></channel></rss>|**Fail**|This shows up as html.  Is that correct?|
|3|11|Select **Geographic Services** submenu options under _hamburger_ to view menu bar|System to display the Geographic data and services page (https://www2.gov.bc.ca/gov/content/data/geographic-data-services)|As expected|Pass||
|3|12|Select **About** submenu options under _hamburger_ to view menu bar|System to display the About page|About is presented as a popup with an 'x' to close the popup|_Conditional Pass_|**NOTE**:  in the current catalogue there is a lot more information presented that would fit in the popup.  May rethink the implementation of the About page.|
|3|13|Select **Contact DataBC** submenu options under hamburger to view menu bar|System to provide a mechanism to allow the user to enter information about their query.|As expected|Pass|In theory, this could be replaced with the Service Desk Client Portal, if implemented branch wide. |

**Comment by sheilamv** [comment]
@BrandonSharratt , does the following text mean that RSS is working as expected?

<rss version="2.0">
<channel>
<title> Province of British Columbia BC Data Catalogue RSS Feed </title>
<link>https://toyger.data.gov.bc.ca/api/ckan/rss</link>
<description> An RSS Feed of the contents of the Province of British Columbia's Data Catalogue </description>
</channel>
</rss>

**Comment by sheilamv** [comment]
FR is hidden (thanks)
About box is still a popup, but nice that we have control over the content.

I will close this once I get a reply back from @BrandonSharratt on the **Subscribe to New Data** menu option.

**Comment by BrandonSharratt** [comment]
That is what the current version of the test environment shows so that is what I believ eyou should see

**Comment by sheilamv** [comment]
Thanks @BrandonSharratt .  will close this ticket.
