### ISSUE TITLE
Homepage Dataset Searches

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#223]
As a consumer (Public or Government) user of the BCDC, I should be able to navigate from the home page based on the presentation of text to me.  However, There seems to be some UI controls that don't provide the UX implied.

![image.png](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/879be81c-72fb-4c42-abd6-9f1056ec47a4)

This full document can be found [here](https://bcgov.sharepoint.com/:x:/r/teams/00108/Shared%20Documents/PROD_BCDC/UIUX%20User%20Acceptance%20Testing/Templates/EDC_UAT_NewUI_SMV.xlsx?d=wa02da30961264f17b72e240c98a35074&csf=1&web=1&e=x41ouk). Public (No Login) tab > Test case #4.

**Comment by BrandonSharratt** [comment]
All of the fails are part of a PR that is waiting to be merged PR #216

**Comment by SteveChapmanBCDX** [comment]
@sheilamv - These changes (PR #216) should be available tomorrow (Nov 18) - can you retest then?

**Comment by sheilamv** [comment]
@SteveChapmanBCDX , Yes, I can retest when changes applied.

**Comment by yuisotozaki** [comment]
As of 2020-Dec-16, toyger has these links fixed.

**Comment by SteveChapmanBCDX** [comment]
Moving to "QA (in Toyger)" for testing.

**Comment by SteveChapmanBCDX** [comment]
All issues resolved.  Closing ticket.
