### ISSUE TITLE
Design Consistency when filtering datasets from dataset list

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#224]
As a Public (or Government) consumer of data from BCDC, I would expect consistency in UX and presentation of List of Values (LoVs) in a control to be presented in the same manner (ascending alphabetical order. 

Details of the test case #5 can be found [here](https://bcgov.sharepoint.com/:x:/r/teams/00108/Shared%20Documents/PROD_BCDC/UIUX%20User%20Acceptance%20Testing/Templates/EDC_UAT_NewUI_SMV.xlsx?d=wa02da30961264f17b72e240c98a35074&csf=1&web=1&e=dYac8c).  Pay attention to the comments for test cases that did pass and have conditional passes.  

Highlights:

- Ability to deselect all selected for filtering

- Need a header above the right side controls noting this is filtering

- Presentation of filtering is not in ascending alphabetical order in all filtering sections

- No ability to filter datasets by resource 'type' (current catalogue has this associated at the Dataset level, this has been moved to the Resource level as Type (Application , Dataset, Geographic Dataset, Web Service/API).  I understand the move to the Resource for flexibility, but could be a useful filter to see all Datasets that have Geographic Datasets.  A filtering of datasets based on resource identification. 

- Under the Organization subsection of filtering, the list of organizations are daunting.  It may be better to present listing the parent organizations first with their associated child organizations group together.

**Comment by yuisotozaki** [comment]
Observation as of 2020-Dec-16
* Ability to deselect all - Present
* Header for filtering - Present
* Resource Data Type content is alphanumerically ordered (all caps first, then lowercase)
* Organization list is a technical challenge to be overcome in a ticket of its own.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @yuisotozaki.  All issues either resolved or duplicated elsewhere.
