### ISSUE TITLE
Dataset Search from Explore Datasets Inconsistencies

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#225]
As a consumer, Public or Government, I need the ability to search for a dataset from a list of Datasets, so that I can filter and find the appropriate dataset needed for viewing, etc.  The actual file can be found [here](https://bcgov.sharepoint.com/:x:/r/teams/00108/Shared%20Documents/PROD_BCDC/UIUX%20User%20Acceptance%20Testing/Templates/EDC_UAT_NewUI_SMV.xlsx?d=wa02da30961264f17b72e240c98a35074&csf=1&web=1&e=dYac8c), on the Public (No Login) tab (Test case #6)

![image.png](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/a43f9db3-d9fc-4019-b5ff-78ac010489a3)

**Highlights**:

- What is the default order by sequence?  This should not be the default order by selection.

- Not sure of the logic behind the order of popularity.  Can this be identified, as it doesn't appear to work properly?

- When changing order by to **Publish Date**, it is unclear if this is a date in ascending (oldest to newest) or descending order (newest to oldest).  Consider implementing ascending/descending order for this Order By type.  This should be the **default** on all pages where Order By is displayed. 

- When changing order by to **Last Modified**, the data is inconsistent.  Months are 01,02,03,04,05,06,07,08,09,10,11, 12 and days are 01, 02, 03…to 28, 29, 30, 31.

**Comment by BrandonSharratt** [comment]
The schema migration had previously gotten rid of the fields which were used for sorting this should be resolved when the data migration is finished.

**Comment by SteveChapmanBCDX** [comment]
Transitioning to "QA (in Toyger)".  Let's test to see if this issue can be closed.

**Comment by SteveChapmanBCDX** [comment]
All issues resolved or duplicated elsewhere.
