### ISSUE TITLE
Group Filtering and Page Inconsistencies

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#228]
As a consumer of data (Public or Government), I should be able to see a listing of all datasets belonging to a specific Group for ease of analysis.  You can find the details of the issues found [here ](https://bcgov.sharepoint.com/:x:/r/teams/00108/Shared%20Documents/PROD_BCDC/UIUX%20User%20Acceptance%20Testing/Templates/EDC_UAT_NewUI_SMV.xlsx?d=wa02da30961264f17b72e240c98a35074&csf=1&web=1&e=dYac8c)on the Public (No Login) tab, test case 8.

**Highlights**:

- Filtering by data type does not render the correct datasets (see (9,2) - **FAIL**

- Metadata Modified field is word wrapped and should be shown on one line (yyyy-mm-dd)

- _Share_ link should be labeled to be _Share link_ or _Copy link_ 

- Members section should only be visible to Admins, regardless of whether they are members of the group or not

- Members section should be visible to members of the group and all editors of the dataset's organizations which belong to the group. 

- Order by logic needs to be consistent throughout the application.

**Comment by SteveChapmanBCDX** [comment]
Closing ticket - any outstanding issues have been duplicated elsewhere.
