### ISSUE TITLE
JSON Schema Updates

### ISSUE THREAD

**Issue by pumapants** [bcgov/ckan-ui#231]
Additional items need to be added to the domain lists.

"name" : "contact_roles",
--

- "dataManager"
- "dataSteward 

"name" : "resource_format",
--

- "gpkg"
- "multiple"

"name": "resource_update_cycle",
--

- "biweekly"
- "nightly"

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/6

That PR also adds Archived to the state drop down

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger - closing ticket.
