### ISSUE TITLE
Data Resource Icon - Make a colour and not gray

### ISSUE THREAD

**Issue by pumapants** [bcgov/ckan-ui#232]
The Data icon for a Resource is set as a light gray. From the users perspective and was reported by a user, this looks like it is a grayed out item and not available when it is the main downloadable it.

![image](https://user-images.githubusercontent.com/32690119/99323174-7f078680-2826-11eb-867a-312d624a4706.png)

**Comment by BrandonSharratt** [comment]
Old UI only
