### ISSUE TITLE
Visual Alignment Issue for About view

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#238]
This ticket contains a summary of alignment issues in the new UI as of December 15, 2020.
See attached PDF.
[About@1.5x.pdf](https://github.com/bcgov/ckan-ui/files/5698889/1.About%401.5x.pdf)

**Comment by SteveChapmanBCDX** [comment]
Reviewed changes - all changes complete.  Moving to "Closed".
