### ISSUE TITLE
Visual Alignment Issue for Datasets View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#239]
This ticket contains a summary of alignment issues in the new UI as of December 15, 2020.
See attached PDF.
[Datasets View@1.5x.pdf](https://github.com/bcgov/ckan-ui/files/5698848/2.Datasets.View%401.5x.pdf)

**Comment by BrandonSharratt** [comment]
The dataset card width DOES reach the end of the search bar you just picked one that had a line wrap due to a word not fitting on the remainder of the line, looking at the card below you can see it does have the correct width.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckan-ui/pull/248

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Let's talk about reintroducing the search feature in the header.

All other changes complete.

**Comment by SteveChapmanBCDX** [comment]
Reviewed the issue with @yuisotozaki  - closing the issue.
