### ISSUE TITLE
Improve error messaging when back end fails to respond

### ISSUE THREAD

**Issue by jachurchill** [bcgov/ckan-ui#24]
In CADI and CATI, the back end will occasionally fail with no error message.  The behaviour from the user's perspective is a perpetual spinner (that is, the failure is not graceful).

How do we handle this error more gracefully?  Reviewed with dev group => recommended implementation is timeout that alerts user that there has been a failure and invite user to reload application. 

Related, but not pertinent - Issue may arise from config differences between CADI and CATI.  Probably best to diff the containerization setup between CADI and CATI.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @jachurchill.  This issue is fixed, except in CATI.

**Comment by ryleyw** [comment]
2 options
- have a simple monitor in the front end 
- set the error code after a time out on request
