### ISSUE TITLE
Visual Alignment Issue for Dataset View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#240]
This ticket contains a summary of alignment issues in the new UI as of December 15, 2020.
See attached PDF.
[Dataset@1.5x.pdf](https://github.com/bcgov/ckan-ui/files/5698852/3.Dataset%401.5x.pdf)

**Comment by BrandonSharratt** [comment]
The more info field has been changed by a change made for resources page #241 which makes it not pretty, the snackbar can't be moved without remaking the functionality entirely as snackbars only support bottom in material spec. 

The license spelling is from the schema and is changed elsewhere, I will suggest it be changed when the team adds tooltips

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - Thanks, I'll review the changes.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckan-ui/pull/252

**Comment by SteveChapmanBCDX** [comment]
Outstanding issues:
* Add space below "Resources" header

Review with @yuisotozaki:
* How to handle null information in "More Info" field - may be able to abstract discussions to all fields in general

**Comment by SteveChapmanBCDX** [comment]
Reviewed issue with @yuisotozaki - will close this tickets and issue new tickets for related, uncompleted work.
