### ISSUE TITLE
Visual Alignment Issue for Resource View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#241]
This ticket contains a summary of alignment issues in the new UI as of December 15, 2020.
See attached PDF.
[Resource@1.5x.pdf](https://github.com/bcgov/ckan-ui/files/5698857/4.Resource%401.5x.pdf)

**Comment by BrandonSharratt** [comment]
The Not provided is difficult to achieve in most of the fields you have as you don't seem to always want it.

I have applied it to JSON and composite fields. the other changes are done, the spacing being applied to composite and JSON fields where it wasn't before to veritcally align left edge, has made them quite hideous on my screen as most of their values are quite large.

**Comment by SteveChapmanBCDX** [comment]
Reviewed the ticket with @yuisotozaki.  Closing this ticket.
