### ISSUE TITLE
Visual Alignment Issue for Organizations View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#242]
This ticket contains a summary of alignment issues in the new UI as of December 15, 2020.
See attached PDF.
[Organizations@1.5x.pdf](https://github.com/bcgov/ckan-ui/files/5698864/5.Organizations%401.5x.pdf)

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckan-ui/pull/250

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Can you review the styling of orgs that don't have children?  For them, we may need more space between margin and label text.

**Comment by SteveChapmanBCDX** [comment]
Closing ticket - will open a separate issue for alignment of orgs without children.
