### ISSUE TITLE
Visual Alignment Issue for Organization and Group View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#243]
This ticket contains a summary of alignment issues in the new UI as of December 15, 2020.
See attached PDF.
[Organization and Group@1.5x.pdf](https://github.com/bcgov/ckan-ui/files/5698867/6.Organization.and.Group%401.5x.pdf)

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckan-ui/pull/249

**Comment by SteveChapmanBCDX** [comment]
Reviewed - all changes complete.  Closing issue.
