### ISSUE TITLE
Visual Alignment Issue for Groups View

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#244]
This ticket contains a summary of alignment issues in the new UI as of December 15, 2020.
See attached PDF.
[Groups@1.5x.pdf](https://github.com/bcgov/ckan-ui/files/5698871/7.Groups%401.5x.pdf)

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckan-ui/pull/247

**Comment by SteveChapmanBCDX** [comment]
Outstanding items:
* Constrain images to padded squares

**Comment by SteveChapmanBCDX** [comment]
Reviewed with Yui and Brandon - this has been fixed on their machines.  Closing issue.
