### ISSUE TITLE
About Box's header needs to stay visible when the user scrolls the content

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#260]
Can we make sure the header stays visible by using scrollable modal dialog? 
Ref: https://vuetifyjs.com/en/components/dialogs/#scrollable

![image](https://user-images.githubusercontent.com/56084999/106963625-b71bb880-66f5-11eb-8131-2eb0ac7db804.png)

**Comment by SteveChapmanBCDX** [comment]
@TerryLanktree - @yuisotozaki created an abridged text for the `About` page.  We can replace the existing text with this abridged text version, if you prefer.

Abridged version is contained in one of Yui's comments in #195.

**Comment by SteveChapmanBCDX** [comment]
This view could be probably be made static, with scrolling removed.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckan-ui/pull/376

**Comment by sheilamv** [comment]
Unable to fully test this, but I have seen it demoed to work as above.  Closing ticket as per conversation with team. 

![image](https://user-images.githubusercontent.com/65407822/114425543-0820b080-9b6e-11eb-80a2-055736950f28.png)
