### ISSUE TITLE
About box should not be any horizontal scrollbar visible

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#261]
The horizontal scroll bar should not be visible
**Consumer View**
![image](https://user-images.githubusercontent.com/56084999/106963189-15946700-66f5-11eb-814b-fef6e8d7cfd6.png)

**Edit View**
![image](https://user-images.githubusercontent.com/56084999/106963434-6b690f00-66f5-11eb-9fdb-9c9b7685612c.png)

**Comment by TerryLanktree** [comment]
Another aspect of #260

**Comment by sheilamv** [comment]
I have been able to test this - horizontal bar no longer visible - PASS.  This ticket can be closed.
