### ISSUE TITLE
Replace stock image on Landing Page

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#267]

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX Do we have a stock photo resource that we can draw from?

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - I never head back from my contact - I'll try again to see if we can find one.

**Comment by TerryLanktree** [comment]
We could always try the image used at data.gov.bc.ca

**Comment by yuisotozaki** [comment]
Looks pretty good with the background image from data.gov.bc.ca
https://data.gov.bc.ca/assets/gov/images/summer_background.jpg
![image](https://user-images.githubusercontent.com/56084999/108541161-fcfc8300-7296-11eb-9097-fae0ab1e2e45.png)

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - Let's replace the current image with this image.

@yuisotozaki - Can you create a new ticket to review the landing page image, and include link to the stock photo that we're using now?  I don't want to lose the reference to that photo.

**Comment by SteveChapmanBCDX** [comment]
Code changes go here:
* https://github.com/bcgov/ckan-ui/blob/dev/frontend/src/components/pages/home.vue

**Comment by yuisotozaki** [comment]
Created new ticket #327 to track the stock image.

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger.  New image implemented.

**Comment by TerryLanktree** [comment]
Looks great!
