### ISSUE TITLE
Move some of the logic

### ISSUE THREAD

**Issue by BrandonSharratt** [bcgov/ckan-ui#27]
Some of the logic for how to display/sort objects is in the vuex store, we should move things that don't affect lists (at least) the backend bridge in an attempt to normalize the data so if the backend changes with a new version of CKAN or if the backend isn't CKAN it would be easier to change it.

**Comment by ryleyw** [comment]
Moved getResource to bridge

**Comment by BrandonSharratt** [comment]
Made some fixes from the movement, and moved users, deleted some redundant calls. the movement around users should make page load faster when logged in.
