### ISSUE TITLE
Database migration:  Check to ensure that resource types are being mapped properly

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#276]
With BCDC 2.0, the resource type will reside with each resource, rather than with the record itself.  That means that the database migration must allow for the resource types to be mapped from the records to the underlying resources.

Database migration logic:
* General => for a given record, its resource type is mapped to the record's resources; and
* Special => for certain geographic records, some underlying resources are mapped to a different resource type (e.g., records that have Custom Download/WMS/KML resources)

**Comment by cpspicer** [comment]
How do we test  that the mapping is correct?  An example would be helpful for the UAT.  e.g. an exact example of what was broken and what a proper result is would be useful.

**Comment by cpspicer** [comment]
Terry decided to close this ticket.  We can re-open if we observe similar issues, or spawn a new ticket with more specific details.
