### ISSUE TITLE
Create/modify Data Record:  Success/Fail notifications are conflicting with other UI elements

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#279]
When an editor/admin creates or modifies a data record, the editor/admin receives a success or fail notification when she submits changes.

These notifications are overlapping other UI elements.

The same issue exists for create/modify data resources.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Will need your advice here.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - @BrandonSharratt fixed this in PR #346, linked to issue #340.

Can you review the change for styling?

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX 
I'm seeing strange layering
Chrome 88.0.4324.192
Toyger Version: 1.9.0-8f55cfa Api Version: 2.7.5
Tried editing a dataset:
![image](https://user-images.githubusercontent.com/56084999/109551291-38f8ca80-7a85-11eb-8c7f-66ee6b87d60c.png)

Tried adding a text file resource without the file specified (no feedback when Save pressed):
![image](https://user-images.githubusercontent.com/56084999/109551700-bf151100-7a85-11eb-8aa9-3db1e19dac74.png)

Tried adding a text file resource with a file attached:
![image](https://user-images.githubusercontent.com/56084999/109551965-13b88c00-7a86-11eb-8dd1-d20d60d257a9.png)

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Changes have been deployed.  Functionality looks really good.  Can you review and advise as to any recommended changes?

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX The notifications look good!

**Comment by SteveChapmanBCDX** [comment]
Agreed.  @BrandonSharratt did a great job.

Closing ticket.
