### ISSUE TITLE
Resource Description field - change default value

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#281]
Where a resource's "Resource Description" field is null, the value defaults to "No Description found. Please Update this resource." 

As per Yui's recommendation (see below), let's change this to "Description not provided."

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX We can be more specific with "Description not provided." to redirect consumers' attention to data provider.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Thanks - that is more purposeful.

@BrandonSharratt - as Yui suggested, let's change the default to "Description not provided."

**Comment by BrandonSharratt** [comment]
@yuisotozaki @SteveChapmanBCDX The field is not allowed to be null. So the best I can do is change the migration script to set it to that. The value you referenced is the current default over there.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - Understand.  Yes, let's change the migration script to set empty description fields to "Description not provided."

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/16

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger.  Change implemented.
