### ISSUE TITLE
Prevent Search button from caching last search term

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#286]
When the user performs a search using the Search button, the search is cached.  Let's clear the search when the user access the search by way of the Search button.

@yuisotozaki - Your thoughts here?  Would users expect the last search term to be cached, or to be presented with an empty search bar?

**Comment by yuisotozaki** [comment]
There are a few user stories here:
1. User is on landing page and enters a search term in the main bar in the middle of the screen. The user is redirected to datasets view where the user expects the search term to persist in the search bar
2. User is on landing page and enters a search term in the header search bar. The user is redirected to datasets view where the user expects the search term to persist in the search bar.
3. User is on datasets view and enters a new search term in the search bar. The user is shown a new set of datasets on the datasets view where the user expects the search term to persist in the search bar.
4. User is on datasets view and and clicks on the search bar in the header where the user does not expect the previous search term to persist.
5. User is on dataset view after navigating from datasets view (where there was a search term). The user then clicks on the header search bar where the user does not expect the search term to persist.
6. The user is on datasets view after a search and navigates to Explore by Organization and clicks on an organization. The user does not expect the search term to persist.
7. The user is on organization view and navigates to home or Explore Datasets. The user does not expect the search term to persist.
8. The user is on datasets view after a search and navigates to Explore by Groups and clicks on a group. The user does not expect the search term to persist. 
9. The user is on group view and navigates to home or Explore Datasets. The user does not expect the search term to persist.

I think functionally, we're looking for this set of behaviour:
* The header search bar should never cache pervious search term
* When navigating to Home, Explore Datasets, Explore by Organization, and Explore by Groups, the search bar cache should be cleared.

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX This ticket can be closed as #211 has addressed this issue.
