### ISSUE TITLE
The "Resource Description" field is not populating properly in the Resource View

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#287]
In the detailed Resource view, the "Resource Description" field is displaying "No Description found. Please Update this resource" even when the resource appears to include a description.  For the resources in the dataset below, the resource descriptions are appearing in each resource's card in the resources list (righthand side of screen).  However, the resource description is not displayed when the resource is selected in the main Resource view.

Subject Dataset => https://toyger.data.gov.bc.ca/dataset/shorezone-observed-habitat-polygons

![Screen Shot 2021-02-09 at 11.06.19 PM.png](https://images.zenhubusercontent.com/5c95a0ffb350086a7c331f14/fc750af4-7ca0-4e65-8e10-da4a7faef390)

**Comment by yuisotozaki** [comment]
Reproduced by visiting the link in Steve's comment above and clicking on one of the 'View' links in Other Resources.
I'm also seeing a strange error message popup over the browser.
![image](https://user-images.githubusercontent.com/56084999/107589110-1e37e200-6bba-11eb-8585-c208692b67af.png)

**Comment by SteveChapmanBCDX** [comment]
It looks like this fix replaced all existing resource descriptions with the default description.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/18

This will require another migration but should fix a lot of migration issues.

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger - issue is resolved.  Closing ticket.
