### ISSUE TITLE
Header Search Icon, Share Button Snackbar, "Licence" spelling, Organizations without suborgs

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#288]
Issue 1 Header Search Icon
![image](https://user-images.githubusercontent.com/56084999/107587691-14f94600-6bb7-11eb-9f51-598974c4cb4a.png)
- Header search icon is tad too big - it should have the same height as the hamburger menu icon

Issue 2 Share Button Snackbar
![image](https://user-images.githubusercontent.com/56084999/107587721-26425280-6bb7-11eb-8d98-8f3d3f00410f.png)
- When the Share button is clicked, the system pops up a snackbar stating "Permalink URL Copied to Clipboard!" at the bottom centre of the screen - this snackbar is too far away from the point of action (the Share button) and can be easily missed.
- Can we increase the font size and bold the text?

Issue 3 "Licence" spelling
![image](https://user-images.githubusercontent.com/56084999/107587791-43772100-6bb7-11eb-8cbc-050879da12a3.png)
- "License" should be spelled "Licence" on Dataset, Search filter section, etc.

Issue 4 Organizations without suborgs
![image](https://user-images.githubusercontent.com/56084999/107587841-5e499580-6bb7-11eb-8783-3605ab4e810e.png)
- The names of organizations without children should be aligned with names of other organizations

**Comment by BrandonSharratt** [comment]
1. Done
2. Done - 16px and bold
3. I have added it to translations HOWEVER it should really be done in the schema for posterity
4. Done added pl-10 to orgs without children

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger - all implemented.
