### ISSUE TITLE
Geospatial Resource field Projection Name pulling from Resource Access Method list

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#291]
When adding a Geographic Resource the Project Name options are presenting the list from Resource Access Method.
--

**Comment by SteveChapmanBCDX** [comment]
Reproduced the issue here => https://toyger.data.gov.bc.ca/dataset/geographic-feature-code-catalogue/resource/create

<img width="1026" alt="Screen Shot 2021-02-11 at 10 05 01 PM" src="https://user-images.githubusercontent.com/36771389/107735730-41938780-6cb5-11eb-85c4-aee35b5e6b8c.png">

**Comment by annikaLiving** [comment]
Looks like adding new geographic resources makes things hang if you select a value that is available but not one that is intended.

Test case is just spinning and spinning when i try to view or edit it.

Also note the Spatial Coordinate System values are all links to their definitions in Cat Classic. They are not in in new Cat. 

Spatial Reference System | [EPSG_3005 - NAD83 BC Albers](https://epsg.io/3005)

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - I have come across the same behaviour on adding/editing geographic resources.  On one occasion, I was presented with the Spatial Coordinate System values for any field that I tried to edit.

Hard to pin down this behaviour, but it should probably be tested thoroughly before release.

**Comment by SteveChapmanBCDX** [comment]
Testing in Toyger - version `d05408a`.

When I created a new resource (https://toyger.data.gov.bc.ca/dataset/geographic-feature-code-catalogue/resource/create), the Projection Name field dropdown listed the appropriate values.

However, I wasn't able to create the resource because I ran into the known 409 error on save.

**Comment by sheilamv** [comment]
I tested this and can confirm that the Projection Name is now populating with the correct list.

**Comment by sheilamv** [comment]
I see that the list is correct, but got this error when saving a new resource: 

Failed to load resource: the server responded with a status of 409 ()
