### ISSUE TITLE
Temporal Extent Beginning Date and End Date are not Date enabled fields

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#292]
The dates fields under Temporal Extent on a record do not have a calendar that pops up to select a date. Therefore what format these need to be in is unknown.
Temporal Extent
* Beginning Date
* End Date

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt, @yuisotozaki - What do you two recommend here?  Add a date picker or a hint to date format (MM-DD-YYYY) in the textbox?

Also, I'm not sure if these fields are being validated.  The textbox did not go red when I entered what I thought would be considered an invalid entry.

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX
Recommend adding a data picker just like on Add Dataset form's Record Lifecycle History section. Placeholder is not necessary if we don't allow manual entry.
We should validate on the front-end if the End Date is Before Beginning Date or Beginning Date or later than End Date.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - let's add data pickers here.

How difficult would be to add validation to ensure that Beginning Date precedes End Date?

**Comment by annikaLiving** [comment]
Concur with @yuisotozaki that just enabling the date picker like the other Date fields would suffice.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - **Implementation**:

Please add date pickers for each of the Temporal Extent fields:
* Beginning Date
* End Date

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt  - 

I'm running into an error when I use the date pickers:

<img width="650" alt="Screen Shot 2021-02-23 at 9 31 53 PM" src="https://user-images.githubusercontent.com/36771389/108953179-9fae5c00-761f-11eb-949d-03415cc754b2.png">

The code appears to be running into an error in the new version of the `watch` method in `Composite.vue`:

<img width="758" alt="Screen Shot 2021-02-23 at 9 35 39 PM" src="https://user-images.githubusercontent.com/36771389/108953296-d4221800-761f-11eb-8951-31f3de22b1fa.png">

**Comment by SteveChapmanBCDX** [comment]
Results of testing Temporal Extent date pickers:
* When creating new resource, date pickers allow user to select dates (both beginning and end dates)
* On save, selected dates NOT persisted
* On editing, date pickers allow user to select dates (both beginning and end dates)
* On save, user gets a 409 error
* On editing (second time), dates selected during first editing attempt are persisted.  However, those dates are not displayed when viewing resource in read mode

**Comment by BrandonSharratt** [comment]
This is actually a different issue affecting composite fields in general and should likely have been a different issue

https://github.com/bcgov/ckan-ui/pull/370

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - Agreed - there appear to be two separate issues:
* Selected dates not persisting on creation of resource; and
* The known 409 errors on modification of an existing resource (see #340)

The 409 error is becoming entangled with all other resource issues and makes testing and analysis difficult.  Recommend we sort out the 409 errors first.
