### ISSUE TITLE
Resource Name is not shown as Mandatory

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#293]
Resource Name does not include a red outline and warning text when not filled in.

When left blank and then hit Save and Error comes up does not indicate that this field is what is not allowing it to be saved.

**Comment by SteveChapmanBCDX** [comment]
I reproduced the error.

Agree with @annikaLiving that we need to:
* Mark the "Name" field as mandatory; and
* Add standard validation for the "Name" field (red outline on fail)

**Comment by annikaLiving** [comment]
Cat Classic by-passes this by putting the name of the file in the place of the Name when you hit safe. Prefer that the text is user entered.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/13

**Comment by cpspicer** [comment]
File needs an update (Git Repo pointer) prior to this being live in Toyger

**Comment by sheilamv** [comment]
I have tested and found that Name on a resource is not required.  This ticket can be closed.

**Comment by SteveChapmanBCDX** [comment]
Closing ticket.
