### ISSUE TITLE
Geospatial Resource Geographic Extent fields to be Pre-Populated with Provincial Bounding Box Coordinates

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#295]
When creating a Geospatial resource the Geographic Extent fields are to be auto populated with the bounding box of the province.
* North: 60.0
* East: -113.5
* South: 48.0
* West: -139.5

**Comment by SteveChapmanBCDX** [comment]
This is the default behaviour in the current version of the BCDC:

![Uploading Screen Shot 2021-02-11 at 10.12.45 PM.png…]()

**Comment by annikaLiving** [comment]
Confirmed that this is applied.
