### ISSUE TITLE
Composite Repeating Views - Add consistent alignment for all fields and truncate overflowing field values

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#296]
The Dataset view has a section called "More Info" which itself contains "URL" fields.

These URLs are supposed to use the same alignment as the other fields on the page.  However, when the URLs are long, the formatting becomes inconsistent.

The URLs may need to be truncated to allow for the desired alignment.

These two screenshots (same dataset, different screen sizes) illustrated the differences between desired and existing alignments.

**Case #1 - Desired Alignment**

<img width="1680" alt="Screen Shot 2021-02-11 at 8 58 17 PM" src="https://user-images.githubusercontent.com/36771389/107732201-9e3e7480-6cac-11eb-85e9-d74b293243f8.png">

**Case #2 - Inconsistent Alignment**

<img width="1680" alt="Screen Shot 2021-02-11 at 8 58 27 PM" src="https://user-images.githubusercontent.com/36771389/107732217-aac2cd00-6cac-11eb-8136-ed5fb32a84b6.png">

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Can you review this?  Not sure if truncating the URLs is the best solution, but it would solve the alignment issue.

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX Good catch - the hyperlinked URL values should wrap in its own container so as not to start mixing with the "URL" field labels.
Thanks to #150, the users now have the ability to set a human legible text description for each URL. The wrap behaviour  should be same here that if the user entered a very long description that needs to wrap, it should wrap within its own container and not mix with 'Description' field label.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt  - please make these two changes:
* Hyperlinks to be truncated (if required) to maintain normal alignment
* Text description to wrap (if required) to maintain normal alignment

**Comment by SteveChapmanBCDX** [comment]
Reviewed this issue with @BrandonSharratt.  This field is wrapped in a composite repeating field.  Accordingly, the best design would be one that could be abstracted for use by all fields.

I'll modify this issue to apply these rules for all composite repeating fields:
* Use same alignment for all child fields; and
* Truncate all fields values (URLs and any others) that are overly long

**Comment by SteveChapmanBCDX** [comment]
Test results from Toyger:
*  URLs are still overflowing

Tested using https://toyger.data.gov.bc.ca/dataset/grizzly-bear-bear-areas-km2-by-density-code-unit-data-south-coast-sbot.

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger.  Formatting has been corrected.  Truncated links work properly.

Closing ticket.
