### ISSUE TITLE
If "More Info" section is empty, hide the entire section

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#297]
The dataset view contains a section called "More Info".  When this section is empty, we should hide the entire section.

<img width="1680" alt="Screen Shot 2021-02-11 at 9 09 09 PM" src="https://user-images.githubusercontent.com/36771389/107732722-e742f880-6cad-11eb-87b4-913c0057289c.png">

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - What do you think about this situation?

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX I agree with your recommendation. Since it's a set of fields for additional information rather than a standard set, if there are no values present we should hide this section altogether.

**Comment by SteveChapmanBCDX** [comment]
Reviewed this issue with @BrandonSharratt.  This view is of a type called "composite repeating views".  Other composite repeating views include Contacts and the Record Lifecycle History(resource).

Codewise, it would be best if we could come up with a common approach for all of these views.

@yuisotozaki - need to review this one with you.

**Comment by yuisotozaki** [comment]
Developing a good UX is about how the fields and their contents are consumed in context of user story. Even if the data construct is the same behind the scenes, it's the purpose of displaying the information to the user that dictates visibility behaviour.
Contact section helps users find who to contact with all questions concerning the dataset. This should never be empty as there must be at least one point of contact for each dataset.
More Info can be empty as the name implies, it is a set of information in addition to the minimum fieldset that can constitute useful information on the catalogue. If there are not any additional information, then this section can be hidden without negatively affecting user's experience.
History should always contain at least one record (e.g. original publication date).

Since business rules say that Contact and History should not be empty, we _could_ implement a UI behaviour that "if no data exists, do not display the composite set section". However, in case of erroneous data entry in the future, it can cause confusion later down the road as to why the Contact or History section is empty.

**Comment by sheilamv** [comment]
I am trying to test this but not sure what the final decision was on this.  I created a new dataset in Toyger (https://toyger.data.gov.bc.ca/dataset/testing-more-infor-appearance---297) and while the optional objects are showing Not Provided for Purpose, Data Quality and Lineage Statement, the More Information and URL as still visible with no reference to Not provided.

Not sure if this is a full P or a PP(provisional pass) until the More Info and URL are addressed.

**Question**:  Does the description provided of the More Info and the URL resolve that the text for the link is the Description and the underlying link is the provided URL?

**Comment by SteveChapmanBCDX** [comment]
@sheilamv - Thanks, I'll review this with @yuisotozaki.

**Comment by yuisotozaki** [comment]
Looks to me like a PP as it doesn't hurt UX but the More Info section should be hidden if no values are present.

**Comment by sheilamv** [comment]
This needs to go back for fixing.  I still see the labels for More Info and URL when none have been provided.  The implementation of this is also incorrect.  

When a URL is provided on its own - display the URL as entered.  If there is Description text provided along with the URL, it should be the text displayed and the URL be the underlying source.  [This is the Description|https://google.ca]

**Comment by annikaLiving** [comment]
1.9.0-c386025Api Version: 2.7.5
![image](https://user-images.githubusercontent.com/32690119/109861125-ce29c980-7c13-11eb-8ef1-c66cc67c31ea.png)

**Comment by annikaLiving** [comment]
If playing around with More Info 

1. can the example of the URL be changed to a valid gov url
* https://www2.gov.bc.ca/gov/content/moreinfo.html
1. When the values are long can the ... be expandable to see the values for both Description an URL
* Still believe these fields should not be aligned as they are and a user should see more.

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - Great suggestions immediately above - could you open a new ticket to capture those?  I'll try to focus this ticket on the narrow issue of the "More information" section's visibility.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki and I reviewed this issue again yesterday.  We recommend hiding the "More Information" and all other composite views when the views are empty.

@TerryLanktree - If you're happy with this recommendation, then we can ask Brandon to implement.

**Comment by TerryLanktree** [comment]
If this is causing problems, I think it would be fine to do this, but it does beg a larger question of consistency.  We need to have a workflow for when items get "Not Provided" and when items are hidden.  If we are not consistent, we should have rationale for the difference in handling methodology.

**Comment by SteveChapmanBCDX** [comment]
The reason we recommended to handle all composite views (as opposed to individual fields) this way was for that express purpose - to maintain consistency across these views.  As I understand it, there are three main composite views: the "More Information" section, the Contacts list and the Record Lifecycle History.  In practice, the latter two should never be hidden as each record is required to have at least one contact and at least one life cycle event ("created on ...").

So totally agree with desire for consistency.  The issue about "Not Provided" versus "Unknown" relates to individual fields rather than the composite views.  So an important issue, but one unrelated to this one.

**Comment by sheilamv** [comment]
Still seeing More Info and URL labels with no data - on existing records and when creating a new dataset.

**Comment by TerryLanktree** [comment]
Please ensure that blank field states "Not Provided"
