### ISSUE TITLE
"Record Lifecycle History" section - Extra "Date" label needs to be removed

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#298]
The dataset view has a section called "Record Lifecycle History".  In edit mode, each entry in this section has a "Date Type" label.  These labels do not have enough room, and are spilling over on the next line.   They need to be given space to remain inline with their corresponding fields.

<img width="1680" alt="Screen Shot 2021-02-11 at 9 27 06 PM" src="https://user-images.githubusercontent.com/36771389/107733719-8a950d00-6cb0-11eb-8a06-5eae2beb7e62.png">

**Comment by yuisotozaki** [comment]
I think this means renaming "Date Type" to "Type" for the first field.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki - Thanks - you're right, the label is "Date Type", but there's not enough room to contain the entire text to one line.

Let's link this ticket to the review of the "Record Lifecycle History"/"Date Type"/"Date" discussion.

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX Sounds good - we can close this ticket as duplicate I think.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt -  You can move ahead with this one.  Immediate task is to prevent label text for "Date Type" from overflowing onto row beneath.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/20

**Comment by sheilamv** [comment]
Not logged in, I still see Date Type. https://toyger.data.gov.bc.ca/dataset/fibre-utilization-forest-carbon-initiative-projects

Logged in, I still see Date Type label when creating a new dataset. 

Not fixed.
