### ISSUE TITLE
Toolbar for Dataset View needs to be a tad wider

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#301]
The toolbar for Dataset View needs to be a tad wider to ensure the Resources box does now peek from underneath when scrolling.
This is **not an issue on Resource View**, so maybe we can replicate how the toolbar on that screen works.
![image.png](https://images.zenhubusercontent.com/5e3c6715d85e5dced833aef6/de15938e-0c91-4396-a475-00f8581b1410)

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckan-ui/pull/378
