### ISSUE TITLE
Caching Issue when Add Dataset clicked while on an existing Record page

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#303]
When looking at a record and then clicking on the Add Dataset button the information for the original record is cached on the page. Only once the page is refreshed is the create record details blank.

**Comment by SteveChapmanBCDX** [comment]
I reproduced the bug in version `1.9.0-85b4524`.  

When I pressed the "Add Dataset" button from a record, this error appeared:

<img width="574" alt="Screen Shot 2021-02-18 at 10 11 03 PM" src="https://user-images.githubusercontent.com/36771389/108465400-c68f1b80-7236-11eb-901b-6a1b9bbb2b9a.png">

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - How tricky a fix would this be?  An alternative would be to hide the "Add Dataset" from the Dataset view and force users to create a new dataset from the dataset lists view.

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - I'm still seeing caching here.  I tested in Toyger against commit #63ee044.

**Comment by SteveChapmanBCDX** [comment]
Reviewed in Toyger - issue was fixed.  Closing ticket.
