### ISSUE TITLE
Resource listed Licences  need to be live links to Licence Location

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#305]
From the view Record page, the listed licence needs to be a live link to the licence location.

E.g, from Cat Classic

Licence  [Access Only](https://www2.gov.bc.ca/gov/content/home/copyright)

Licence  [Open Government Licence - BC Assessment](https://info.bcassessment.ca/pages/opengovernmentlicencebcassessment.aspx)

Licence  [Open Government Licence - British Columbia](https://www2.gov.bc.ca/gov/content?id=A519A56BC2BF44E4A008B33FCF527F61)

**Comment by sheilamv** [comment]
Open Government Translink link (https://www.translink.ca/-/media/Documents/plans_and_projects/managing_the_transit_network/2017-TSPR/Open-Government-Licence--TransLink-TSPR.pdf) - resolves to a 404 error

I search Translink site and found this:  https://www.translink.ca/-/media/translink/documents/plans-and-projects/managing-the-transit-network/tspr/open-government-license-translink-tspr.pdf)

All other links resolve  correctly.  I will move back to the sprint backlog.

**Comment by BrandonSharratt** [comment]
This is also an issue in prod, @annikaLiving has reached out to see what url they'd like linked up
