### ISSUE TITLE
Time Out Issues when calling back the Org List.

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#306]
Went into the dev tools and get this when i click on Orgs.
 
for "activity" and "organizations" i get this:

>  message: "Upstream service error - The upstream server is timing out"

 As well as "...api/an?pageUrl=/organization&pageTitle=Organizations&referrer=/"

"notOk": "Not Enabled"

Results in 0 records found after this.

**Comment by SteveChapmanBCDX** [comment]
I haven't been able to reproduce this issue.  Let's track instances of this issue to see what's going on here.

Platform Services has also granted us additional resources for the OCP3 BCDC-Test namespace.  Alan and Brandon will be able to reallocate more resources to the API, which may alleviate the problem.

**Comment by cpspicer** [comment]
Annika not getting her zero results like last week; more resources added to name space.  Maybe this has been resolved?  Suggest close until its observed again.
