### ISSUE TITLE
Resource Status = Obsolete - include Replacement URL

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#307]
When a Record's Resource Status is set to Obsolete, a field to add a Replacement URL needs to be included.

This field is then mandatory.

This is how it is set up in Classic Cat and is a widely used field required for retirement processes and finding replacement datasets. Future would allow for a Retirement Service people could subscribe to.

![image](https://user-images.githubusercontent.com/32690119/108299452-4f348b80-7153-11eb-950f-71e0f2f294f6.png)

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - Do editors outside of our branch set records to "Obsolete"?  I thought this was only for editors/admins within the branch, but want to confirm.

**Comment by annikaLiving** [comment]
This is used by all editors and admins. As this function is hidden, not all users know it exists. Although we would and have encouraged that all editors use this.

**Comment by SteveChapmanBCDX** [comment]
It sounds like main use case if for admins, although I agree that we should encourage editors to use it.

Given that this is an admin function, I think we could probably delay this issue to MVP or Future Improvement.

@TerryLanktree - Your thoughts?

**Comment by annikaLiving** [comment]
@SteveChapmanBCDX  this is not an admin function, it is an editor and a consumer use as well.

The fear that if this is added after the fact, all the records that have this filled in, the data will be lost.

**Comment by annikaLiving** [comment]
My bad, this is actually there but as it appends after the date fields, one would not know it is there if you already thought it was the end of the record. Like i did.
