### ISSUE TITLE
Record Life Cycle - Create state machine to restrict available state transitions

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#308]
When a new record is created, the State should be set to DRAFT.

**Comment by SteveChapmanBCDX** [comment]
This issue relates to the "Dataset Life Cycle" issue in the DDS Jira project ([DDS-235](https://proj.data.gov.bc.ca/jira/browse/DDS-235)).

**Comment by cpspicer** [comment]
Implementation of workflow state.  TL:  MVP

**Comment by cpspicer** [comment]
DDS-235

**Comment by cpspicer** [comment]
Details in 235 RE: state machine

**Comment by sheilamv** [comment]
[DDS-235 - State Machine.pdf](https://github.com/bcgov/ckan-ui/files/6124719/DDS-235.-.State.Machine.pdf)

State machine diagram reviewed with @annikaLiving and @TerryLanktree .  Please proceed as discussed, without any notifications.  I will enter a new ticket for the backlog noting the need for notifications to continue with like for like between Current Cat and New Cat.

**Comment by sheilamv** [comment]
[DDS-235 - State Machine.pdf](https://github.com/bcgov/ckan-ui/files/6125233/DDS-235.-.State.Machine.pdf)

Update the document to show that Delete is a function and not a state change that should be available to Editors and Admins of the organization only when the dataset is in Draft state.

**Comment by SteveChapmanBCDX** [comment]
We should consider adding these two transitions to state machine:
* "Pending Archived" => "Published" (Admin only); and
* "Archived" => "Pending Archived" (Admin only)

Both would be added for the purpose of reversing mistakes.

**Comment by sheilamv** [comment]
Added Published => Pending Publish (Admin only)

[DDS-235 - State Machine.pdf](https://github.com/bcgov/ckan-ui/files/6125600/DDS-235.-.State.Machine.pdf)

**Comment by BrandonSharratt** [comment]
In addition to #418 this also requires  https://github.com/bcgov/ckanext-bcgov-schema/pull/24

**Comment by sheilamv** [comment]
I will run through the state machine in Toyger today.  I have two profiles (admin & editor).  I will also validate visibility of Public (first) and then other logged in users (not belonging to the organziation).

**Comment by sheilamv** [comment]
Public User - not logged in can only see Pending Archived and Published records.  This is correct.  There is no ability for a Public User (no login) to change the state of a dataset/record within the BCDC UI.

**Comment by sheilamv** [comment]
Logged in to Toyger as sheivand (Editor only of data-innovation-program-dip organization).  I am able to view Draft records for organizations to which I am not an Editor.  @annikaLiving, is this correct?  I am not able to edit them, so are we 1/2 way there?

cc. @TerryLanktree

**Comment by sheilamv** [comment]
**Groups** - logged in as sheivand (Member of two groups) - I should be able to view published records and add to the groups of which I am a member.  I am not able to do this (**fail**)

**Comment by TerryLanktree** [comment]
@sheilamv that behaviour sounds correct, logged in you can see all records, but not edit ones outside your role.  I believe that is like for like.  I can add to DAtaBC, whichI belong to, not to groups I do not belong.

**Comment by sheilamv** [comment]
I noted an issue in another ticket about logged in and inability to filter by all states when logged in as an Editor.  

Not logged in - should be able to filter by Published and Pending Archived 
Logged in with no roles - should be able to filter by Published and Pending Archived 
Logged in with a role (Editor) - should be able to filter by Draft, Pending Publish, Published, Pending Archive and Archived.  Able to Edit Draft, Pending Publish, Published and Pending Archived datasets belonging to their Org
Logged in with role (Admin) - should be able to filter by Draft, Pending Publish, Published, Pending Archive and Archived.  Able to Edit Draft, Pending Publish, Published, Pending Archived and Archived datasets belonging to their Org

**Comment by TerryLanktree** [comment]
Provided we cannot transfer states inappropriately, this ticket is accomplished.  This appears to still show filtering issues, which are being covered under a different ticket.  Will close.
