### ISSUE TITLE
Datasets View: Design

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#31]
Creation of a datasets view.

**Comment by SteveChapmanBCDX** [comment]
List of facets:
* Licence
* Format
* Organizations
* Download permissions
* State

**Comment by yuisotozaki** [comment]
Design notes and mockups.
https://documize.pathfinder.gov.bc.ca/s/bkph5eb5fb79okvk8ffg/data-discovery-and-management/d/bp261mnf7ss5649lh7h0/bcdc-uiux-design-notes?currentPageId=bp28p8vf7ss5649lh7og
