### ISSUE TITLE
Record Visibility Set to "logged in" but content still Visible with URL

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#310]
When the visibility of a record is set to internal, this record should then not be accessible when not logged in. Currently visible with the URL.

Have confirmed the record is not returned when searched.

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - I'm not sure what you mean here.  Do you mean that a user that is not signed in can access an IDIR-only data record if she enters the record's URL?

**Comment by annikaLiving** [comment]
@SteveChapmanBCDX that is correct.

**Comment by SteveChapmanBCDX** [comment]
I tested in the current version of BCDC, and the behaviour is the same.  I tested with this record => https://catalogue.data.gov.bc.ca/dataset/parcelmap-bc-packaged-product-internal

I agree that this is a desirable security improvement, but I'm not sure that it needs to be completed for Beta/MVP.

@TerryLanktree - Please review and prioritize as to Beta/MVP/Future Improvement.

**Comment by annikaLiving** [comment]
@SteveChapmanBCDX the record above is set to Record, i.e., the metadata, is Visible to Public, not Gov. 

The data is set to Visible to Gov.

**Comment by SteveChapmanBCDX** [comment]
Thanks @annikaLiving - Can you send me a better URL to test against?

**Comment by SteveChapmanBCDX** [comment]
URL for "IDIR-only" view of data record => https://toyger.data.gov.bc.ca/dataset/first-nation-consultative-areas

**Comment by SteveChapmanBCDX** [comment]
Disregard my comments above.  The behaviour here is different than the behaviour in the production version of BCDC.

Will review with @BrandonSharratt to discuss implementation.

**Comment by yuisotozaki** [comment]
Discussed with @SteveChapmanBCDX around logout flow.

Two options were discussed as typical flows found in the wild.
1. Redirect user to landing page with toast message confirming logout (toast goes away after a few seconds)
2. Redirect user to a specific screening confirming that the user was logged out (existing behaviour in cat)

The main purpose of "you were successfully logged out" confirmation is to tell the user that they can step away from their computer and not worry about a bad actor browsing with their credentials.

With option 1, it's slick and looks nice. Depending on the toast implementation, however, the confirmation message can be missed as it is a temporary popup.

With option 2, it's a very explicit confirmation and also opens up opportunity for customer engagement points by having "recommended stats" or "did you know we have a blog?" type of things.

After a short discussion, we decided that option 2 is preferred. For now, we can have a simple message of "You were successfully logged out." and link to the Catalogue home page.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @BrandonSharratt. Brandon to fix immediate issue - will implement existing logic in BCDC Prod and modify to change error message from "Not authorized" to "Not found".

I'll write up a ticket for the larger issue of whether the log out UI/UX should be modified.

**Comment by SteveChapmanBCDX** [comment]
Reviewed with @BrandonSharratt  - working properly in Prod, except that it's returning "Access denied" (should be "Not found").

Fix - use procedure from Prod catalog, but change error message to "Not found".

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov/pull/850

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - I tested this in Toyger (version #8f55cfa) and it is working properly.

Before I close this ticket, can you test it against a relevant dataset?

**Comment by annikaLiving** [comment]
I have confirmed a record set to visible on when logged in is not findable when logged out.

This is the error returned. 

`404 Not Found: No such dataset`

Future enhancement could be to direct users with a better message.

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - Thanks for taking a second look for me.  Closing ticket.
