### ISSUE TITLE
Domain list contains a blank value - Multiple fields

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#311]
Multiple field contains what looks to be a blank along with the list of selectable values. This is selectable but for those set as mandatory field it errors when trying to save.

This blank needs to be removed from the list.

* Resource Type* 
* Resource Storage Format*
* Spatial Datatype
* Projection Name

**Comment by TerryLanktree** [comment]
Blank field should not be selectable in a mandatory field.

**Comment by BrandonSharratt** [comment]
This should be the case for all fields now, it was previously broken for fields that were conditional and for fields that changed order due to conditionals. Please test
