### ISSUE TITLE
Dataset in URL has changed between Cat Classic and New

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#315]
The New Cat main page is plural "datasets" while Cat Classic is singular with all it's URLs "dataset".

Is this intentional? 

**Cat Classic**
https://catalogue.data.gov.bc.ca/dataset
https://catalogue.data.gov.bc.ca/dataset/add
https://catalogue.data.gov.bc.ca/dataset/new
https://catalogue.data.gov.bc.ca/dataset/water-users-communities

**New Cat:**
This is plural datasets
. ...data.gov.bc.ca/datasets

These are singular dataset
. ...data.gov.bc.ca/dataset/create
. ...data.gov.bc.ca/dataset/water-users-communities

**Comment by SteveChapmanBCDX** [comment]
I think it's intentional.  I think an endpoint named "datasets" is more accurate than one called simply "dataset", as the purpose of the endpoint is to return all available datasets.

**Comment by annikaLiving** [comment]
@SteveChapmanBCDX I do agree with that logic as that is how we name things in the BCGW but other naming standards in other Ministries, do the opposite. I see 2 things: 
* if people have bookmarked or linked it from their webpage as this main page, those will break. This is the main page that i would share as i would not share the one with the public facet attached. 
* I found this because i went to a resource and then removed the resource title from the url as one does when looking at the URL string like a directory structure. I was expecting to be taken up a directory and it produced a 404.

**Comment by SteveChapmanBCDX** [comment]
I reviewed similar endpoints.

Here's a summary:

Datasets =>  "dataset" in current BCDC, "datasets" in new BCDC
Organizations => "organization" in both current and new BCDC
Groups => "groups" in both current and new BCDC

So the endpoint naming convention is the consistent across the two versions of BCDC, but for the Datasets endpoint.

@BrandonSharratt  - Do you remember why the Datasets endpoint was changed to "datasets" for the new release?

**Comment by TerryLanktree** [comment]
I understand some things are singular and some things plural, but I will often delete part of a URL and reform on the fly.  I see the "s" as a potential gotcha.

**Comment by BrandonSharratt** [comment]
I did it for clarity not for consistency as that was literally the first page made in the new UI. I think adding '/dataset' as a redirect to '/datasets' as an easy solution that allows for everyone to be happy

alternatively we can alias it instead of redirect ie both /dataset and /datasets would work

**Comment by TerryLanktree** [comment]
Either works for me, as the both appear to solve the issue of not connecting when a user shortens the URL.  Is one way more obvious, so we don't have to go looking for hidden parameters in the future (I don't like gotchas)?
