### ISSUE TITLE
Contact Displayed Should be Checked On by Default

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#318]
The Contact check box should be checked on by default as it is in Cat Classic.

**Comment by SteveChapmanBCDX** [comment]
Agree - I thought I had written this up already - I'll see if there's a duplicate somewhere.

**Comment by SteveChapmanBCDX** [comment]
Closing as duplicate.

**Comment by annikaLiving** [comment]
Confirmed this displayed is checked on at default.
