### ISSUE TITLE
Spash View: Design

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#32]
Design of splash view.

**Comment by SteveChapmanBCDX** [comment]
**Issue**:  Should we keep the "Try Searching For" function?
**Decision**:  Yes, keep this function
**Rationale**:  Engages the user and provides them with several search defaults.  This list will initially be hard-coded and determined by our team.  Later, we may be able to connect this to analytics that will allow us to display the top 5/10/15 most popular search terms.

**Comment by SteveChapmanBCDX** [comment]
Approved Design for Desktop:

![Splash View - Desktop](https://user-images.githubusercontent.com/36771389/74376179-87fa9180-4d96-11ea-8a1e-3bd2c6052c94.png)

Approved design for Mobile:

![Uploading Splash View – Mobile.png…]()

**Comment by SteveChapmanBCDX** [comment]
Closed issue by mistake - reopening.

**Comment by SteveChapmanBCDX** [comment]
Approved design for Mobile:

![Uploading Splash View – Mobile.png…]()

**Comment by yuisotozaki** [comment]
Design notes and mockups.
https://documize.pathfinder.gov.bc.ca/s/bkph5eb5fb79okvk8ffg/data-discovery-and-management/d/bp261mnf7ss5649lh7h0/bcdc-uiux-design-notes?currentPageId=bp265cnf7ss5649lh7j0

**Comment by yuisotozaki** [comment]
Met with PO and Dev February 20, 2020 and hammered out a revision to the header.
- Move Log in and language toggle to header for desktop
- In mobile view, hide log in and language toggle in menu (Login will be the top option while language toggle will be at the bottom as that's where users expect it to be)
