### ISSUE TITLE
Schema Domain Items Missing - Visible and Downloadable to

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#321]
The following are missing from the drop down list, i have also reordered them so they fall to how security progresses.

**Who can view this data?**
Public
Government and Business BCeID _- Missing_
Government
Named users

**Who can download this data?**
Public
Government and Business BCeID _- Missing_
Government
Named users
Not downloable _- Missing_

Had thought i created a tix in the schema repo but can't find it) Brandon asked to make one here and he will deal with.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/17

**Comment by cpspicer** [comment]
Requirements.txt - needs to be modified (references a GIT commit) before this will go live in Toyger before Annika can initiate testing.

**Comment by SteveChapmanBCDX** [comment]
Tested in Toyger.  New values included in dropdown menus.  New values can be assigned to fields and persisted.

**Comment by annikaLiving** [comment]
I have confirmed that an existing record with 2 of these is now populated with the additional field.

dataset/28ba5352-c4fd-4832-984c-8179e35e0f49

dataset/a0d909d7-df03-490d-9d3c-14cea5270ae6

* The behaviour of the second one is wrapping, of which @yuisotozaki  you may have a comment.

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - I reviewed both records and didn't see anything unusual.  Could you add a screenshot to illustrate the wrapping behaviour?
