### ISSUE TITLE
Update landing page

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#327]
For post go-live to update the background image.
Link to Adobe Stock is here.
https://stock.adobe.com/ca/images/hiking-around-mt-assiniboine-late-summer/291596098

**Comment by SteveChapmanBCDX** [comment]
@TerryLanktree - This issue was created to decide if we want to use the original image (mountains) rather than the new image (lake).

**Comment by TerryLanktree** [comment]
I like the lake, it doesn't have a watermark, and it is in Toyger, so I'm good with leaving it alone for now.  Would like to know if this could be configurable, so we could change the image without having to do a re-deploy?

**Comment by sheilamv** [comment]
Point 1 has been completed.
Point 2 is address by #365 
Point 3 has been added to #365

Closing this ticket.
