### ISSUE TITLE
Review existing UI/UX for user log out

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#333]
Current behaviour on user log out:
* User remains on same page
* User not notify of successful logout by toast/alert
* The "Log in" label appears at top of screen

Migrated comment from @yuisotozaki (#310):

> Discussed with @SteveChapmanBCDX around logout flow.
> 
> Two options were discussed as typical flows found in the wild.
> 
> Redirect user to landing page with toast message confirming logout (toast goes away after a few seconds)
> Redirect user to a specific screening confirming that the user was logged out (existing behaviour in cat)
> The main purpose of "you were successfully logged out" confirmation is to tell the user that they can step away from their computer and not worry about a bad actor browsing with their credentials.
> 
> With option 1, it's slick and looks nice. Depending on the toast implementation, however, the confirmation message can be missed as it is a temporary popup.
> 
> With option 2, it's a very explicit confirmation and also opens up opportunity for customer engagement points by having "recommended stats" or "did you know we have a blog?" type of things.
> 
> After a short discussion, we decided that option 2 is preferred. For now, we can have a simple message of "You were successfully logged out." and link to the Catalogue home page.

**Comment by annikaLiving** [comment]
Just had it log out while i was creating a resource. It spun and spun until this error: 

> An Error Occured:
> Please try again or contact your system administrator

Found out i was logged out due to 
> {"error":"Not logged in"}

**Comment by TerryLanktree** [comment]
Appears to go to last public page, we'll see how people comment.
