### ISSUE TITLE
Magnifying Glass Search doesn't Return Values when starting from a fresh Landing Page

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#337]
Start with a fresh landing page with cache cleared, clicking on the magnifying glass in the top bar and a search popup bar appears but...

1. Clicking on this should move the cursor to the popup search bar.
2. Entering a word and hitting enter does not actually search for that word.
    * the entire catalogue is returned.

**Comment by cpspicer** [comment]
Annika to provide a demo to Brandon (steps or screen share)

**Comment by cpspicer** [comment]
part 2 fixed as part of another bug deploy, part 1 just a UI thing - can create a different ticket for that bit.  Moving to QA

**Comment by annikaLiving** [comment]
Tested both in Chrome and Firefox and bullet number 2 works as expected.
