### ISSUE TITLE
"About" view - team to review for content and formatting

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#342]
Before we move to Prod, recommend that the team reviews the "About" view for content, formatting and styling.

**Comment by annikaLiving** [comment]
About text has been updated and ready for review.

This also confirms that the security settings are correct.

**Comment by sheilamv** [comment]
1. ** BC Data Catalogue** - is this correct formatting?
2. Organizations link points to Current Cat.  Is that correct?
3. Selecting a link in a popup box should not redraw the page, but open in another tab. 
4. The DataBC Program and the Data Innovation Program are both part of the Data Systems and Services Branch - not sure the formatting is correct.  Seems a bit heavy to the eyes.
5. DataBC Products and Services API Program Services - Is there missing context to publish?

**Comment by annikaLiving** [comment]
The content in test does not reflect what has was changed. It was overwritten with the last data import. What is in prod matches what was added here.
