### ISSUE TITLE
Cannot Create/Edit Resources - 409 Error

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#345]
Testing in Toyger using version #8f55cfa.

I tried to edit a resource's name, but was not able to do so.  When I tried to save my changes, the UI indicated that the `Resource Type` field (a required field) was empty.  The UI required me to enter a value in this field before I could save my changes.

I attempted to use each of the available values for the `Resource Type` field.  For each of these values, I received a 409 error when I tried to save the changes.

Later, I tried to create a resource.  I ran into the same 409 error.

Error message in console:

![Screen Shot 2021-02-25 at 9.09.00 PM.png](https://images.zenhubusercontent.com/5c95a0ffb350086a7c331f14/ef18bf07-0993-47b4-9d6f-2b428ccadea6)

Steps to reproduce:
* Navigate to the editing view for a resource
* Change the name of the resource
* Add a value for the `Resource Type` field
* Click "Save"

**Comment by annikaLiving** [comment]
Relates to #340

**Comment by BrandonSharratt** [comment]
This is likely a duplicate, and also likely due to a schema error, so if (now that the alerts are more visible) this pops up please create an issue with the text of the alert as a 409 is the api telling you you're colliding with something

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - sorry, I don't understand your comment on the 409 errors.  Are you suggesting that that is something we don't need to troubleshoot?

**Comment by SteveChapmanBCDX** [comment]
@BrandonSharratt - Here's the response:

{"help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_update", "success": false, "error": {"__type": "Validation Error", "created": ["Date format incorrect"], "last_modified": ["Date format incorrect"], "resource_type": ["Missing value"]}}

**Comment by annikaLiving** [comment]
FYI, I created this for the missing values for Resource Type (this is new) and Preview Information (happened a couple migrations ago). I am working on full value comparisons but had not gotten to resources yet.
https://github.com/bcgov/ckan-ui/issues/357

**Comment by SteveChapmanBCDX** [comment]
Testing against 409 errors in Toyger version `35570d3`.

**Test Case #1 - Creating a new resource**

On save, I'm getting a 409 error with this response:

{"help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_create", "success": false, "error": {"__type": "Validation Error"}}

**Test Case #2 - Editing an existing resource**

On save, I'm getting a 409 error with this response:

{"help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_update", "success": false, "error": {"__type": "Validation Error", "created": ["Date format incorrect"], "last_modified": ["Date format incorrect"], "resource_type": ["Missing value"]}}

**Comment by SteveChapmanBCDX** [comment]
**Test Case #2 - Editing an existing resource**

On save, I'm getting a 409 error with this response:

````{
  "help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_update",
  "success": false,
  "error": {
    "__type": "Validation Error",
    "created": [
      "Date format incorrect"
    ],
    "last_modified": [
      "Date format incorrect"
    ],
    "resource_type": [
      "Missing value"
    ]
  }
}

**Comment by SteveChapmanBCDX** [comment]
Returning ticket to "Sprint Backlog" for review.

**Comment by SteveChapmanBCDX** [comment]
More testing in Toyger version `35570d3`.

If I create a new dataset (that is, one distinct from the datasets that were migrated over from Prod), I can create new resources for that dataset.

However, I cannot modify these resources.

When I try to modify the resources, I get this 409 error:

````{
  "help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_update",
  "success": false,
  "error": {
    "__type": "Validation Error"
  }
}

**Comment by annikaLiving** [comment]
Version: 1.9.0-0a93892

@BrandonSharratt , tested editing a resource and got the following

This was on a resource i created to the data store but there was an issue that the file path did not stay.
* .../dataset/annika-has-a-mullet/resource/9a24d844-295a-496b-aaf8-5fbee0860374

> {"help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_update", "success": false, "error": {"__type": "Validation Error", "json_table_schema": ["Invalid JSON string: No JSON object could be decoded"]}}

This was on an existing resource
* .../dataset/databc-download-statistics/resource/808cc945-e1f6-4823-8112-530dbecfbab2

> {"help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_update", "success": false, "error": {"__type": "Validation Error", "created": ["Date format incorrect"]}}

**Comment by annikaLiving** [comment]
Still getting a 409

1. ISO Topic Categaories - need to allow multiple selection

{"help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_create", "success": false, "error": {"__type": "Validation Error", "iso_topic_category": ["unexpected choice \"biota,boundaries\""], "json_table_schema": ["Invalid JSON string: No JSON object could be decoded"]}}


2.  the JSON Schema Table is erroring.
{"help": "https://cati.data.gov.bc.ca/api/3/action/help_show?name=resource_create", "success": false, "error": {"__type": "Validation Error", "json_table_schema": ["Invalid JSON string: No JSON object could be decoded"]}}

**Comment by BrandonSharratt** [comment]
Check again after https://github.com/bcgov/ckan-ui/pull/391 is merged
