### ISSUE TITLE
Preview Information and Resource Type is now Empty

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#357]
In a recent migration the following are not populated:
* Preview Information section
    -  Layer Name​
    - Preview Latitude
    - Preview Longitude
    - Preview Map Service URL
    - Preview Zoom Level
    - Image URL
    - Link to iMap
* Resource Type
     * https://cati.data.gov.bc.ca/api/action/package_show?id=be69a760-a58f-46d1-9ffe-5a7f42b2ed9f

Working on a comparison script to find others.

**Comment by BrandonSharratt** [comment]
Is this still relevant? I'm seeing preview information
https://toyger.data.gov.bc.ca/dataset/groundwater-wells/resource/2a1df0bc-cc3d-4e2d-8b76-1ad67526afdc

the above also has resource_type

these are resource level fields now not dataset level fields

**Comment by annikaLiving** [comment]
Confirmed these are now populating.
