### ISSUE TITLE
BCGW/WMS Preview Still calling DMF - Migrate to SMK.

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#358]
When clicking on a resource that has the preview for BCGW WMS enabled it is to use the BCDC SMK. Currently still calling the DMF.
* getting this for Geographic datasets that are not affiliated with the BCGW.
   e.g,  ... dataset/30aeb5c1-4285-46c8-b60b-15b1a6f4258b/resource/3d72cf36-ab53-4a2a-9988-a883d7488384

Where it should exist.
E.g., .../dataset/parcelmap-bc-parcel-fabric/resource/b3a8efef-d540-412c-9f44-f0ba5d79f575

>There was an error while loading site ID 7535188336326689232. Please ensure the site ID is correct or contact your administrator.

> Request URL:
> 	
> https://apps.gov.bc.ca/pub/dmf-viewer/jsp/viewerConfig.jsp?//apps.gov.bc.ca/pub/dmf-rest-api/resources/sites/7535188336326689232?mode=0

**Comment by TerryLanktree** [comment]
SMK needs to be incorporated in Cat 2.0, all references to DMF removed.

**Comment by annikaLiving** [comment]
Preview of the the SMK works but not drawing up the details from the values entered for the WMS, zoom level, etc.

**Comment by SteveChapmanBCDX** [comment]
Moved issue back to "Sprint Backlog".

@BrandonSharratt - Not sure if you have enough information here to proceed.  If not, please review with @TerryLanktree, @annikaLiving.
