### ISSUE TITLE
Title needs to be unique

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#361]
The record title should be a unique value and should warn the provider that the title is a duplicate when trying to save.

Currently the title url is set to be unique but not the title that creates it.

CC's title is unique.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/23

**Comment by annikaLiving** [comment]
@BrandonSharratt in Toyger this is erroring but with Unknown Error.

Messaging for URL when duplicate is clear.

**Comment by TerryLanktree** [comment]
Given an unknown error, nothing that states the Title is already in use.

**Comment by BrandonSharratt** [comment]
This was the result of a bug fixed in https://github.com/bcgov/ckanext-bcgov-schema/pull/32

**Comment by sheilamv** [comment]
@TerryLanktree , this is associated to a ticket that I am about to close.  I tested that the title and URL must both be unique
