### ISSUE TITLE
Saved Resource or Record should take to view state of what was created

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#362]
Inconsistent functioning so want to create more examples to find out consistent themes.

Saving a Record
* Should take a user to the Record View page
* Currently inconsistent as stays in the edit page and sometimes takes to edit page.
    - e.g., when creating a new record, as the keywords error, when this is fix and saved stays on edit mode.
        - this errors with
        - > id: The input field id was not expected.
        - > Name: That URL is already in use. 
    - Interesting that when i go to the view page, i don't have the Add Resource button. 

Saving a Resource
* Should take a user to the Resource View page
   * Unknow what happens as right now it is just spinning as it logged me out while saving. doh
   * Tested again and it takes one back to the Resource View page.

**Comment by annikaLiving** [comment]
@TerryLanktree  for your review.

**Comment by TerryLanktree** [comment]
Agreed, each save should take you to the View page, not keep you on the Edit page.

**Comment by sheilamv** [comment]
I created a new record (**dataset**) and when I saved, it displayed the record in read only mode (**Pass**). 

I created a **resource** on an existing dataset.  When saved, it took me back to the dataset record, not the resource page (**Fail**).   I don't think this is fixed.  Can either @annikaLiving or @TerryLanktree move to sprint backlog if you feel this is not fixed either.  

@BrandonSharratt

**Comment by sheilamv** [comment]
I was able to create a new dataset (https://toyger.data.gov.bc.ca/dataset/ckan-ui-362) and when saved, returned me to the record in read only mode (passed)

**Comment by TerryLanktree** [comment]
Looking at the behaviour, I'm not certain we want to change.  You may be as the dataset level when you create/edit a resource.  You have the ability to select resource edit from the dataset page.  Perhaps this actually saves clicks.  I think this needs more discussion before we modify.

**Comment by sheilamv** [comment]
@TerryLanktree, should we just close this ticket then and address if/when others make comments during Beta or post MVP?

**Comment by TerryLanktree** [comment]
done!
