### ISSUE TITLE
Geographic Resource ISO Topics not accepting Multiple Values

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#363]
For a Geographic Resource the ISO Topic field errors with multiple values selected. Was able to save with only 1.

This is the error response.

````{
  "help": ".../api/3/action/help_show?name=resource_create",
  "success": false,
  "error": {
    "__type": "Validation Error",
    "iso_topic_category": [
      "unexpected choice \"economy,boundaries\""
    ]
  }
}

**Comment by annikaLiving** [comment]
Still not accepting multiples @BrandonSharratt

**Comment by BrandonSharratt** [comment]
The problem here is that the ckan in test didn't update the plugins properly I'll investigate if it doesn't self build after the state machine PRs are merged
