### ISSUE TITLE
Resource Card Download/Access/Request Access/View logic

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#364]
Logic behind the words used are based on OFI configured or not.

When OFI then Resource Card is set to:
* Request Access & View

All others are 
* Download & View

----
This logic needs to be refined as these do not reflect what that Resource type is.
* **Request Access** is a term used when a dataset is not available, not for when required to submit an order.
    - **Order** would be a much better term.
* **Access** as a term on it's own can cover all 4 types of Resources.
* Cat Classic it was **Download/Access & View**.
* There are many datasets that are Geospatial that are not from the BCGW and OFI enabled.
* What should be used when a Resource is not downloadable at all?
    - e.g., DIP
    - e.g., BCGW Objects not downloadable to anyone
* For Apps and Webservices using Download very misleading
    - For an App one would think one was downloading an app.
    - Same for Webservices
* The intent of the Catalogue is to catalogue gov resources irregardless of downloadable or not.
   - Will see in the future more resources that are not downloadable as ministries turn to the cat to catalogue their operational holdings. 

----
Possible better options:

**Geographic Dataset _with_ OFI:**
1. Order & View
1. Access & View
1. Download/Order & View
1. Download/Access & View
1. **Add to Shopping Cart || i in circle**

**Geographic Dataset _without_ OFI:**
1. **Access || i in circle**
1. Access & View

**Tabular Dataset:**
1. Download/Access & View
    - Technically one could Order tabular data too.
    - An enhancement would be to enable OFI to tabular too.
1. **Access  || i in circle**

**Webservice/API**
1. **Access  || i in circle**

**Application**
1. **Access  || i in circle**

**Comment by annikaLiving** [comment]
@TerryLanktree will let you review this one. i think it should be addressed for MVP.

**Comment by joe-taylor** [comment]
I need a french translation for Access/Download.

**Comment by joe-taylor** [comment]
Also need to decide what icon to use for Access/Download - classic catalogue uses the "open in new" icon, shown below.

![image](https://user-images.githubusercontent.com/5297264/131202995-65279c61-7d68-4381-b0e4-58d1d7285d72.png)

**Comment by TerryLanktree** [comment]
If we are staying status quo, let's stay status quo.  I suspect for secure download it may even hold true.

**Comment by joe-taylor** [comment]
This has been migrated to toyger but you may need to clear your browsers cache or hold shift and click reload to get the changes to show up.

**Comment by sheilamv** [comment]
Testing while not logged in:

**Type**: Application - **PASSED**
**Dataset**: https://toyger.data.gov.bc.ca/dataset/bc-canadian-aquatic-biomonitoring-network-cabin-sites-and-models-web-app
**Resource**: https://toyger.data.gov.bc.ca/dataset/bc-canadian-aquatic-biomonitoring-network-cabin-sites-and-models-web-app/resource/151c7801-a738-48bf-8fce-c9106d694575
**Resource Card Label Link**: Access/Download
**Resource Menu Label**: Access/Download
**Results**:  Access/Download (as expected)

**Type**: Geographic Data - **PASSED**
**Dataset**: https://toyger.data.gov.bc.ca/dataset/bc-assessment-data-advice
**Resource**: https://toyger.data.gov.bc.ca/dataset/bc-assessment-data-advice/resource/3da3dc21-e99b-4476-b28a-cc5ccbcb17cf
**Resource Card Label Link**: Access/Download
**Resource Menu Label**: Access/Download
**Results**:  Access/Download (as expected)

**Type**: Tabular Data - **PASSED**
**Dataset**: https://toyger.data.gov.bc.ca/dataset/bc-finance-budget-2020
**Resource**: https://toyger.data.gov.bc.ca/dataset/bc-finance-budget-2020/resource/ece3b52e-077e-4ab4-ab55-f6f7b7f88c15
**Resource Card Label Link**: Access/Download
**Resource Menu Label**: Access/Download
**Results**:  Access/Download (as expected)

**Type**: Webservice/API - **PASSED**
**Dataset**: https://toyger.data.gov.bc.ca/dataset/open511-drivebc-api
**Resource**: https://toyger.data.gov.bc.ca/dataset/open511-drivebc-api/resource/6667ea7d-933e-4329-9b13-6e6687c33ac9
**Resource Card Label Link**: Access/Download
**Resource Menu Label**: Access/Download
**Results**:  Access/Download (as expected)

**Comment by sheilamv** [comment]
Testing while not logged in:

Type: Application - PASSED
Dataset: https://beta-catalogue.data.gov.bc.ca/dataset/bc-canadian-aquatic-biomonitoring-network-cabin-sites-and-models-web-app
Resource: https://beta-catalogue.data.gov.bc.ca/dataset/bc-canadian-aquatic-biomonitoring-network-cabin-sites-and-models-web-app/resource/151c7801-a738-48bf-8fce-c9106d694575
Resource Card Label Link: Access/Download
Resource Menu Label: Access/Download
Results: Access/Download (as expected)

Type: Geographic Data - PASSED
Dataset: https://beta-catalogue.data.gov.bc.ca/dataset/bc-assessment-data-advice
Resource: https://beta-catalogue.data.gov.bc.ca/dataset/bc-assessment-data-advice/resource/3da3dc21-e99b-4476-b28a-cc5ccbcb17cf
Resource Card Label Link: Access/Download
Resource Menu Label: Access/Download
Results: Access/Download (as expected)

Type: Tabular Data - PASSED
Dataset: https://beta-catalogue.data.gov.bc.ca/dataset/bc-finance-budget-2020
Resource: https://beta-catalogue.data.gov.bc.ca/dataset/bc-finance-budget-2020/resource/ece3b52e-077e-4ab4-ab55-f6f7b7f88c15
Resource Card Label Link: Access/Download
Resource Menu Label: Access/Download
Results: Access/Download (as expected)

Type: Webservice/API - PASSED
Dataset: https://beta-catalogue.data.gov.bc.ca/dataset/open511-drivebc-api
Resource: https://beta-catalogue.data.gov.bc.ca/dataset/open511-drivebc-api/resource/6667ea7d-933e-4329-9b13-6e6687c33ac9
Resource Card Label Link: Access/Download
Resource Menu Label: Access/Download
Results: Access/Download (as expected)
