### ISSUE TITLE
Data Catalogue text moving down over action Bar when browser Resized results in Failure to use Action Buttons

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#368]
Using both my laptop and my monitor when the browser is resided or the Dev Tools are open, results in the Data Catalogue overlapping the action buttons and error buttons.

* Instead of wrapping on a lower area, can the words not just get smaller?
* This is very frustrating.

**Comment by annikaLiving** [comment]
@yuisotozaki for your review.

**Comment by yuisotozaki** [comment]
There's a very narrow width range where the "Data Catalogue" header drops down into the content area. About 945px and 965px. If the browser continues to be reduced in width, the "Data Catalogue" disappears so it's not obstructing other UI elements.
Recommendation
* Reduce the title font size to 24 below 965px width
* Reduce the title font size 18 below 768px width (Need to verify that 'Data Catalogue' fits)
* Reduce the title font size to 14 below 480px width (Need to verify that 'Data Catalogue' fits)

**Comment by TerryLanktree** [comment]
Could we adjust the font size a wee bit smaller so it stays in the banner until disappears?

**Comment by BrandonSharratt** [comment]
This only happens at a VERY specific breakpoint (about 4 pixels 970-974px), smaller and it's hidden by design larger and it has enough space to show properly. 

I can adjust the size but that was specced out by the UI, so for now I have just made it properly hide at that very specific breakpoint
