### ISSUE TITLE
Keywords & Resource File are emptied when other fields entered.

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#371]
Fields are emptied when other fields are selected \

1. Keywords is emptied with Resource Status is selected
2. Resource File is emptied when the resource Type is entered.
   - This does not happen to a URL
   

**UI Design issue - Side Comment:**
* This is the second time due to the large spacing between fields that i have missed things happening.
* The spacing does not work on my labtop (which is pretty standard for gov), nor on my attached monitor.

**Comment by annikaLiving** [comment]
@yuisotozaki comment about the spacing

**Comment by yuisotozaki** [comment]
The vertical spacing between the fields have definitely grown since earlier in the year.
The vertical spacing takes into account reserved space for error messages and the 8px top and bottom padding.
If we can make the reserved space for error messages per field to display only when needed, it alleviates some of the visual issues.

**Comment by annikaLiving** [comment]
Thanks. Definitely room now to button things up.

![image](https://user-images.githubusercontent.com/32690119/109870597-27e3c100-7c1f-11eb-86a9-9666c37c427d.png)

**Comment by annikaLiving** [comment]
@BrandonSharratt here is the tix where the fields get blanked out. 

FYI, also the file disappears when saved (will do more testing on this)

**Comment by annikaLiving** [comment]
I have confirmed:
1. Resource File is no longer removed by selecting resource type
1. Keywords is no longer removed by selecting Status

However keywords has a blank value that is selectable. unsure if that was there before.
