### ISSUE TITLE
Security Fields in Incorrect Order

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#373]
1.9.0-c386025Api Version: 2.7.5

The Security fields for the Record is mixed in with the Security values for the Resources, i.e., Data. The Record question was at the end of the 4 in Cat Classic. Security Classification should also come first as it did in Cat Classic as that is the overarching security, while the other two are configuration.

What it is:
![image](https://user-images.githubusercontent.com/32690119/109864716-07fccf00-7c18-11eb-8f95-f4aa1c4814b0.png)

**What is should be:**

**Security Classification** Public
**Who can view this data?** Public
**Who can download this data?** Public

> ideally even a space between this as they do not belong together.

**Who can view this record?** Public

---
**Additional Comments:**
* Would actually love for these to be shorter labels as label length impacts the value indenting.
* Also who can view this data really only pertains to iMapBC.
* Download is now on all records, where-as it was not for Applications and WebServices and APIs.
   * For these this will be even more confusing.

**Comment by annikaLiving** [comment]
@yuisotozaki  for comment.

@TerryLanktree at some point we should come up with better Labels. Help text will help things like Data Visibility as it make no sense.

**Comment by yuisotozaki** [comment]
The suggested order makes sense since it follows the logical structure of the security values.

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/23
