### ISSUE TITLE
Record Title Field Length is now less at max 100 characters and Error indicates this as Name

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#379]
1. The max Title Length is now shortened to max 100 Characters
* Cat Classic:
   - Longest title is 184 characters
   > BC Finance - 2013 Financial and Economic Review - Expense by Function - 2001-02 to 2012-13 - Table A27 Expense by Function Supplementary Information - 2001-02 to 2012-13 - Table Q28
   - 197 records have a title of over 100 characters.

* Error Message:
    > Name: Name must be a maximum of 100 characters long

2. Second issues the error message above indicates that the Title field is called "Name"

----
Comments:
* I have confirmed that the full titles of those over 100 characters have been migrated over and not truncated but if a provder attempts to edit their record or resource they will be required to shorten the name. 
    - this may result in a lot of work for the provider if they have multiple records with similar titles, like the example of above.

**Comment by annikaLiving** [comment]
@TerryLanktree  one for you to review. For me this needs to fixed before MVP.

**Comment by TerryLanktree** [comment]
@BrandonSharratt  Please review the setting for filed length and let us know the ramifications for increasing the length to match Cat Classic.  I lean toward mirroring Classic, unless there are good reasons for this change.

**Comment by BrandonSharratt** [comment]
In the database title stores what the frontend calls url and name stores what the frontend calls title. 

The database has a limit on the url of 100 characters and this is also true for Cat classic, in the example given the url is stopped at 100 characters.

We could allow title to be longer than 100 characters but it breaks parity with url which we cannot extend the length of.

**Comment by BrandonSharratt** [comment]
see https://github.com/bcgov/ckanext-bcgov-schema/pull/29
