### ISSUE TITLE
About option in Menu should state what language it is showing currently

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#387]
Update language menu item label to just "Français".
The current label "Language: FR" can be seen as reporting on the current language setting.

**Comment by yuisotozaki** [comment]
@SteveChapmanBCDX Quick fix for a menu item.

**Comment by yuisotozaki** [comment]
Sorry - I meant just "Francais" like this.
![image](https://user-images.githubusercontent.com/56084999/110509715-43374c00-80b7-11eb-8083-9ab82dce3f54.png)

**Comment by SteveChapmanBCDX** [comment]
I was going to ask you about that - that does look better. I'll make the change.

**Comment by SteveChapmanBCDX** [comment]
@yuisotozaki  - @BrandonSharratt prefers "EN/FR" for smaller screens.  Do you have a preference there?

**Comment by SteveChapmanBCDX** [comment]
https://github.com/bcgov/ckan-ui/pull/396

**Comment by yuisotozaki** [comment]
For smaller screens, EN/FR makes sense to me!
