### ISSUE TITLE
Tool Bar Layout / Button Review

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#393]
Version: 1.9.0-baad8d7Api Version: 2.7.5

There are 3 groups of actions in the tool bar and as such should be grouped together. And the Management functions should be grouped together based on what they are doing the action to, i.e., a Dataset or a Resource.

1. **Navigational Tools**: 
    + Back to Datasets (D) list or Back to Dataset (R)
         - this does seem like the words could be shortened to allow for more space on the page.
         - Why not just Back with an arrow?
    + Scroll Down (A)
    + Groups (D)
         - Should this be visible if no groups are applied as it takes a consumer to no information if not applied? There are so few Groups as they are not easily managed at this time. I would not want to promote their use other than when serves a great purpose.
         - Users may want Groups to be accessible but at this time that is not possible. Will take a lot more work to make Groups accessible and require more actually staff resources if we open them up with the current process.
    + Preview (R)
    + Advanced Map Preview  #412 (R)
           - Think this would be a great place for the iMapBC button but don't call it that so it can be used for other apps. We have examples of other data/apps that could use this.
    + Download/Request Access (R)
1. **Communication Tools**:
    + Share (A)
    + Contact Data Expert (A)
        - This is/may not be self expandatory and one thinks they are contacting anybody.
        - Contact this Data Expert - may be too long.
1. **Management Tools**: - These are only to be visible if a user is an editor or admin of that org.
    + Dataset: - A Resource function should not be in between the Dataset functions.
         - Edit Dataset
         - Delete Dataset
             - This will only be visible if the Dataset is in the State of Draft. 
         - Add Resource
             - This needs to be beside the two above, not between then as it is an action to a Resource and the two above are to a Dataset. 
    + Resource:
        - Edit Resource
        - Delete Resource
         - Add Another Resource
             - Missing 
---

**RECORD**

**Editor - Logged out View Record**
![image](https://user-images.githubusercontent.com/32690119/110395331-cfe3fa80-8022-11eb-9e36-1de5833d519b.png)

**Editor - Logged in View Not Editable Record**
![image](https://user-images.githubusercontent.com/32690119/110395088-62d06500-8022-11eb-8869-3080ff190267.png)

**Editor - Logged in View Editable Record**
![image](https://user-images.githubusercontent.com/32690119/110394952-27ce3180-8022-11eb-969a-d0bce40a85c4.png)
+ Where did Scroll to Bottom go to?

**Admin - Logged in View Not Editable Record**
![image](https://user-images.githubusercontent.com/32690119/110396143-4fbe9480-8024-11eb-973c-5c47629ebb28.png)
+ As does not have privs to this record should not be able to do either of the following and the buttons removed.
    - Delete Dataset
    - Edit Dataset
    - Add Resource
+ Where did Scroll to Bottom go to?

**Admin Profile -  Logged in View Editable Record**
![image](https://user-images.githubusercontent.com/32690119/110837646-59c7d980-8256-11eb-8078-35e8e2eb1fee.png)
+ Where did Scroll to Bottom go to?

----

**RESOURCE**
+ Should the Contact This Data Expect be added at the resource level?
+ For Apps and Webservices/APIs - need to review what to do with Download and Preview. #416 #415 

**Editor - Logged out Resource**
![image](https://user-images.githubusercontent.com/32690119/110395373-dc685300-8022-11eb-8f32-19252d04b7d1.png)

**Editor - Logged in View Not Editable Resource**
![image](https://user-images.githubusercontent.com/32690119/110395173-87c4d800-8022-11eb-905c-eac029948b5a.png)

**Editor - Logged in Editable Resource**
![image](https://user-images.githubusercontent.com/32690119/110395021-459b9680-8022-11eb-9bf0-97dec7b458b9.png)
* Example is from an OFI related resource - Also in the OFI configure tix but OFI resources should not have both a Download and a Request Access. Tix: #394
* Term Request Access to be updated tix: #364

**Admin Profile -  Logged in View Not Editable Resource**
![image](https://user-images.githubusercontent.com/32690119/110396323-b348c200-8024-11eb-82d0-0a7c3f9a8968.png)
+ As does not have privs to this record should not be able to do action the following and the button removed.
    - Edit Dataset

**Admin Profile -  Logged in View Editable Resource**
![image](https://user-images.githubusercontent.com/32690119/110837528-300eb280-8256-11eb-9ac5-e25261dcfc31.png)

**Comment by annikaLiving** [comment]
@TerryLanktree  now to add text to what should be for each.

**Comment by SteveChapmanBCDX** [comment]
Recommend that @yuisotozaki review this and any other UI/UX changes before a final decision is made.

**Comment by annikaLiving** [comment]
This tix is not ready for final review as there are multiple things that have come out of this review and still working through this. Will let you know when i feel i have it ready.
1. buttons should be moved around to be grouped with like functions as they seem random at this time.
1. buttons need to be removed from datasets/resources that a user doesn't have privs to.
1. buttons are missing.

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - Totally understand, and this review is excellent.  Wanted to make sure that UI/UX design review isn't overlooked.

**Comment by annikaLiving** [comment]
Dataset Tool Bar

Edit/Management functions only if granted access to edit as an editor or admin

![image](https://user-images.githubusercontent.com/32690119/111394178-69d92200-8677-11eb-9f24-103a20f18c58.png)

**Comment by annikaLiving** [comment]
Resource Tool Bar

* The Preview, iMapBC Preview and Download/Request Access - need to be dealt with better because not all resources use these terms.
    - Apps you don't really "Preview", you "Open" and you for sure don't "Download"
    - Services and APIs you could "Preview" or "Open" and you don't really "Download"
        - As the Network Link KML shouldn't should probably be data and not a service as it is a file one downloads that links to a service.
        - OFI you don't "Request Access" - you "Order" data -
             - there is a tix to fix this wording.
        
![image](https://user-images.githubusercontent.com/32690119/111394219-89704a80-8677-11eb-8abb-6d1e7509c572.png)

**Comment by yuisotozaki** [comment]
Mar 17, 2021
The team had a discussion around the placement of the buttons.
The team agreed that the above mockup makes sense with a few outstanding questions around the Preview/View in iMapBC/Download/Request Access buttonset.

**Comment by sheilamv** [comment]
@BrandonSharratt , it appears that I am able to see menu options on a dataset for which I am not an editor/admin of the org. 

I am an editor & admin of DataBC Program and Knowledge Branch.  

I see the edit/copy/delete/+resource functions on a dataset belonging to Regional Operations - Cariboo.  While it throws an error, the system should be smart enough to know to hide those from me as I can't manage datasets belonging to orgs for which I a have no edit/admin role associations.

**Comment by sheilamv** [comment]
[Git393.docx](https://github.com/bcgov/ckan-ui/files/6281053/Git393.docx)

Three (3) scenarios - two (2) passed and one (1) failed.  Not finished testing but this will eventually go back to @TerryLanktree .
