### ISSUE TITLE
OFI Needs to be Configured

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#394]
Currently all OFI related resources are not configured to use the OFI.

Tool Bar for OFI need to not have both Download and Request Access buttons
![image](https://user-images.githubusercontent.com/32690119/110397298-7382da00-8026-11eb-98f3-c459dc3dbf10.png)

**Comment by annikaLiving** [comment]
@TerryLanktree another one to move into the sprint backlog

**Comment by BrandonSharratt** [comment]
I'm unclear about what this ticket is looking for

**Comment by TerryLanktree** [comment]
There appears to be two parts to this ticket.
1) the toolbar has both "Download" and "Request Access", both of which appear to be trying to invoke the shopping cart (POW) (need to remove one, we should have a bigger discussion about terminology as we are adding to the shopping cart, so neither really express the action)
2) the shopping cart doesn't load either way

I believe we have to wait until we move the container before we can instantiate the shopping cart.  Let me know what we are restrained by.
