### ISSUE TITLE
Searching by keyword by clicking on a keyword is not working: 1.9.0-5e3d2fa

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#397]
On toyger 1.9.0-5e3d2fa, clicking on a keyword from Dataset view does not search by that keyword.
It appears to simply reload the /datasets page.

**Comment by TerryLanktree** [comment]
I see the search bar is filled in with the term, but the search is not started.  @BrandonSharratt  Can you force the search?

**Comment by TerryLanktree** [comment]
Please verify or explain logic.  https://toyger.data.gov.bc.ca/dataset/vri-2019-forest-vegetation-composite-rank-1-layer-r1- shows several keywords.  When I select "forest cover"  the resulting list shows many results that do not have "forest cover" as a keyword.  MDW test record - DPS-524 doesn't appear to even mention this anywhere, and it is at the top of my list.

**Comment by BrandonSharratt** [comment]
The search term should be filled in now and the search forced. It does not search on the keyword field it just searches as though you had entered that text into the box.
