### ISSUE TITLE
Resource Card - Edit (Pencil) Transition to go to Edit Mode not View Mode

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#409]
When clicking on the pencil on a Resource Card from a dataset level, The pencil transitions to a view mode of the resource.

This should take a user to edit mode of the resource.

**Comment by sheilamv** [comment]
@SteveChapmanBCDX , @TerryLanktree  - this has been tested and passed.  When selecting the pencil from the resource card, the system takes user to the resource page in edit mode. This can be closed.
