### ISSUE TITLE
Explore Datasets Order By - Presentation Logic

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#410]
Version: 1.9.0-b15b897

Logic:
1. When no search provided should show the latest published records (as in Cat Classic).
2. When set to a different order by, e.g., Popular and a facet is chosen, should stay on the selected Order preference.
    - Currently reverts back to Relevance.

----
Something that we have always wanted to determine is how to flag records that are considered the authoritative source/primary dataset when results come up with way too many things, e.g., BEC or BEI.
* WIth these examples these datasets are used as the base of so many other datasets. so thus are only attributes of a dataset.
* Can fields be weighted for search results?

**Relevance** - Current Default
* What is Relevance?
    - What is shown first is a record published First Published: 2014-12-16 ???

**Popular**
* Does this still function based on the popularity seen/viewed function?
* This does seem like a useful thing.

**Name Ascending**
* Never used this - don't know if assists the consumers or not.

**Name Descending**
* Never used this  - don't know if assists the consumers or not.

**First Published**
* Showing the most recent, not the first published,
* This should be changed to "Most Recent Published"
* As showing the actual first published has no real value.

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - "First published" is actually "First Published - Descending", so the record that was published most recently is shown first.

Agree with you that would be better to rename that sorting choice to something more accurate.

@yuisotozaki - What's your advice here?  The UI items is "Order by: {option}".  So here, we're using "Order by: First Published".  Change to something like "Order by: Most Recently Published" or simply "Order by: Newest"?

**Comment by annikaLiving** [comment]
Agree with the use of "Newest" - and think that should also be the default when no search has been done.

**Comment by yuisotozaki** [comment]
These ones make sense. 
Order by: Newest
Order by: Name Ascending
Order by: Name Descending

During the user interview, users had trouble understanding "Relevance" and "Popular". Relevance is sort of implied with a keyword based search engine, so it doesn't make sense to the users when it's an option on its own.

**Comment by annikaLiving** [comment]
Think Relevance or Popular was supposed to be a way to find those we wanted the user to find not all the other things that a user may find. Don't think either quite hit that mark.

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - I agree that "Newest" (or similar term) should be default, for sure.  Pretty sure Yui's research confirmed that.

**Comment by annikaLiving** [comment]
Also in this is the functional issue that when you do a search, change the order and then use a facet, the order type reverts to the default.

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - Thanks for flagging this second issue.  I'll write that up as a separate issue.

**Comment by TerryLanktree** [comment]
Resulting list of searched data (or complete list of data) should have the following sorts:

Order by: Newest (default with no search) - rename from First Published
Order by: Name Ascending
Order by: Name Descending
Order by: Relevance (default with search) 
  * (what does that even mean, what is the logic?)
Order by:  Most Viewed Metadata - rename from Popular

**Comment by BrandonSharratt** [comment]
Order has been changed in toyger,

Relevance is a scoring mechanism from solr, I am unsure how it is populated

Popular is a bit more tricky, Popular is a term from ckan core, and is meant to index views_recent, which is populated over a 2 week period, however...the popular we use is all time views so most viewed metadata is more accurate here

We can change to be the most viewed over the last 2 weeks or keep it all time, and we can change the name I just need to know the preference.

**Comment by cpspicer** [comment]
Most viewed in last 2 weeks as default (as per Terry L)

**Comment by sheilamv** [comment]
@TerryLanktree , feedback from Karen Samuelson as follows:
-	Browse - Searched for “mta”
o	Noticed the Order By is defaulted to **Newest** whereas **Popular** is the best choice for us as it automatically brings the user to sort through the data based on most used/viewed

Unsure if this is the correct default, as I believe the current catalogue returns ordered by **Relevance**, not **Popular**.

**Comment by joe-taylor** [comment]
In toyger, non-empty searches default to relevance. In beta, they default to newest. The beta implementation is a bug.

Relevance refers to keyword relevance. That usually starts with TF/IDF scores (Term Frequency / Inverse Document Frequency), which is a formula that balances the rarity of a term across the entire corpus with how frequently it occurs in a particular document.

Relevance can be enhanced with other metrics. For major search engines, which sort by proprietary concepts of relevance, ranking is never left as simple as a mere tabulation of keyword frequency, but nonetheless, relevance as a general concept is the basis of pretty much all search and I believe it is the expected default in most search implementations. We want the items that are more relevant to a user's query to appear near the top of the results, and while relevance as a nebulously defined concept _can_ factor in popularity, and can be very far off the mark for some searches, it's more nuanced and more of a balancing act than simply choosing another basic metric to take its place. I think there will always be justification for some particular use case to choose one search ordering over the other but I think defaulting to relevance and leaving it up to the user to choose something more appropriate is best.

**Comment by sheilamv** [comment]
Testing:

1. Not logged in 
2. Hamburger > Explore Datasets (https://toyger.data.gov.bc.ca/datasets)
3. Order By = Relevance

**Expected**:  _Order By: Relevance_
**Actual**: _As expected_, however, looking at the first three pages, it appears that the datasets are displayed by First Published: <date> in descending order

This give the impression that Relevance is used, however, when viewing a list that has not been giving any search criteria, this does not make sense.

**Comment by sheilamv** [comment]
**Testing Results**:

1. Not logged in
2. Enter mta in Search Data Catalogue field on https://toyger.data.gov.bc.ca/
3. Order By = Relevance

**Expected**: _Order By: Relevance_
**Actual**: _As expected_.  There is no further sorting as the First Published: <date> is not displayed in any order.  Not sure if there is a second sort at all, like there appears to be when the user views from the Hamburger.

**Comment by sheilamv** [comment]
Tested in Beta environment the same steps used to test in Toyger and got the same results.

PASSED
