### ISSUE TITLE
Transition State Security Logic

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#411]
Certain states are only visible to certain folks granted access.

**Visible and Editable** only to those who are assigned Admin or Editor to Orgs Groups in Keycloak
* Draft
* Pending Publish

**Visible** only to those who are assigned Admin or Editor to Orgs Groups in Keycloak
* Archived

**Visible to All**
* Published
   - Exception: Record Visible to IDIR only those who log in with IDIR.
* Pending Archive
    - Exception: Record Visible to IDIR only those who log in with IDIR.

**Comment by sheilamv** [comment]
@BrandonSharratt , this is the ticket regarding visibility and editability of a record in the noted states by and Editor and/or Admin.

**Comment by TerryLanktree** [comment]
@annikaLiving is this still an issue?  I know the state machine has been worked on

**Comment by annikaLiving** [comment]
@TerryLanktree we need to test that the state machine adheres to this. There has been initial testing.
Brandon had asked for a separate tix for security of which i can see in the JSON schema that it has been applied.
Could you move to in QA and will do as such.

**Comment by TerryLanktree** [comment]
Maybe refresh your browser.  I see more options.
![image](https://user-images.githubusercontent.com/45210368/113056318-7faf1280-9160-11eb-8176-e5edac4a9627.png)

**Comment by sheilamv** [comment]
![image](https://user-images.githubusercontent.com/65407822/113058247-c7cf3480-9162-11eb-950b-7ca62e4697b7.png)

Logged in as sheivand (Editor of one org, member of two groups)

**Comment by sheilamv** [comment]
- **Not logged in** - should be able to filter by Published and Pending Archived 
- **Logged in with no roles** - should be able to filter by Published and Pending Archived 
- **Logged in with a role (Editor)** - should be able to filter by Draft, Pending Publish, Published, Pending Archive and Archived.  Able to Edit Draft, Pending Publish, Published and Pending Archived datasets belonging to their Org
- **Logged in with role (Admin)** - should be able to filter by Draft, Pending Publish, Published, Pending Archive and Archived.  Able to Edit Draft, Pending Publish, Published, Pending Archived and Archived datasets belonging to their Org

**Comment by sheilamv** [comment]
Not logged in:  **Pass**
![image](https://user-images.githubusercontent.com/65407822/113912759-5d387d00-9790-11eb-8fb4-5af99eeb3b65.png)

**Comment by sheilamv** [comment]
Logged in with role (Editor): **Pass**
![image](https://user-images.githubusercontent.com/65407822/113912984-9ffa5500-9790-11eb-9535-d092ff41236a.png)

**Comment by sheilamv** [comment]
Logged in with Admin Role:  **Fail** (unsure why there are _Pending Published_ and _Pending Publish_.  _**Pending Publish**_ is the correct state.  
![image](https://user-images.githubusercontent.com/65407822/113914298-409d4480-9792-11eb-86db-ef3bcec98554.png)

**Comment by sheilamv** [comment]
Logged in with IDIR (no role);  **Pass**
![image](https://user-images.githubusercontent.com/65407822/113919002-eef7b880-9797-11eb-8969-c4d89c1ce4df.png)

**Comment by sheilamv** [comment]
The state logic of moving records through the process works.  The display of the available states based on logged in (or not logged in) users is not working.  This is purely the need to fix the available states on which to filter, based on user.

**Comment by cpspicer** [comment]
'pending publish' and 'pending published'

**Comment by BrandonSharratt** [comment]
https://github.com/bcgov/ckanext-bcgov-schema/pull/31

**Comment by sheilamv** [comment]
State Machine works, however I found that an Editor's ability to Filter the list as a consumer is not correct.  All states should be available to the Editor, not just the states that they can move between. 
[State Machine.docx](https://github.com/bcgov/ckan-ui/files/6361871/State.Machine.docx)
