### ISSUE TITLE
Configure iMapBC Button

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#412]
1.9.0-b15b897Api Version: 2.7.5

iMapBC button to be live/visible when a link is provided in Link to iMap field on Geographic datasets.

E.g., 
http://maps.gov.bc.ca/ess/hm/imap4m/?catalogLayers=7624,7627&scale=10000000.0&center=-13456401.49,6471823.11038

Improvements that could be made to this.
1. Rename this "View in Advanced Map"
    - This would be useful as there are other advanced maps, we, providers, and would be beneficial to consumers.
    - The feds have preview and view in advanced map in their toolbar.
2. Move this to either or both:
    1. The Tool Bar beside Preview instead of being embedded in the Preview pop-up.
    2. The Resource Cards.

**Comment by annikaLiving** [comment]
@TerryLanktree could you review how you would like the iMapBC button implemented as it is not visible or working at this time. When i did see it, it was on the Preview pop-up map as a button.
* as the previous PO before we had POs of iMap, this would be a great one for you to comment on.

**Comment by TerryLanktree** [comment]
If this is not a part of the UX design, I would suggest it goes beside the Preview button, as a View in iMapBC, if iMapBC is the only option.  If the button is configurable, and could launch MapHub or some other application, then "View in Advanced Map" or "View in mapping application", or some other variation.  Wording to be determined once I understand if the button calling application is static (iMapBC only) or configurable.

**Comment by annikaLiving** [comment]
It could be used for any map application. In edit mode, would just update the label to reflect this (this piece is easy).

**Comment by annikaLiving** [comment]
@yuisotozaki  for your review and comment. :)

**Comment by yuisotozaki** [comment]
Is there a benefit to calling whatever the mapping application as "advanced" or calling out its name? Can we simply say "View Map" on the button?

**Comment by TerryLanktree** [comment]
I think it was to differentiate from the Preview, which is also a map.  Would it be possible to make the button title configurable, so it could say "View in iMapBC" on one page, and View in "BC MapHub" on another page?

**Comment by TerryLanktree** [comment]
I think this may be dealt with in ticket 393

**Comment by TerryLanktree** [comment]
@BrandonSharratt please ensure the iMapBC button is working, it is not on the Preview page.  Ultimately, I think it would be nice to have it on the main page toolbar beside the Preview button.
