### ISSUE TITLE
Spatial Datatype to Include NA as this is not applicable to all things

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#413]
1.9.0-b15b897Api Version: 2.7.5

Spatial Datatype only relates to a specific set of Geographic Datasets and thus must not be mandatory.
* this should cause data issues for the data import from prod if this is mandatory.

This wasn't before.

**Comment by annikaLiving** [comment]
@BrandonSharratt how are you going to move forward with this as the Implimentation in classic was mandatory but with the bug, it didn't come across as such.

Still should not be mandatory, or if it is, then a NA added.

**Comment by annikaLiving** [comment]
@BrandonSharratt . Review with a few DAs, it was agreed to keep mandatory and add NA. (in the same format as the projection name, could be N.A. or N/A - as long as they are all consistent).

As "Not provided" for empty fields doesn't make sense to a consumer or editor.

**Comment by annikaLiving** [comment]
I will add this to the drop down as i am already working in the schema json.

**Comment by sheilamv** [comment]
I created a draft record and Geographic Data resource and I didn't see N/A displayed anywhere on the resource record.  It displays Not Provided. 

I am not sure what the requirement is here, nor any development notes, so am sending back to PO Review for @TerryLanktree to comment, correct labels and place in the queue for development.  

Unsure if the Beta flag is correct, or if it should be removed and MVP or Post MVP added.

**Comment by TerryLanktree** [comment]
Not Provided was the term Yui suggested we leave everything with, if the item is not populated.  We can leave with this and see what our clients suggest.
