### ISSUE TITLE
Resource File is not Adding a file - Blanks out when Saved

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#414]
1.9.0-b15b897Api Version: 2.7.5

When uploading a file to a resource, it presents like it works but in view mode it is blank and then when editing it is gone.

....data.gov.bc.ca/dataset/annika-has-great-hair/resource/7dd7a2e8-75ab-4c62-90fb-ac33942a8c44

**Comment by annikaLiving** [comment]
@TerryLanktree this should be brought into the sprint backlog.

cc - @BrandonSharratt

**Comment by SteveChapmanBCDX** [comment]
@annikaLiving - Thanks - moving to "Sprint Backlog".

**Comment by sheilamv** [comment]
I have tried twice in beta (https://beta-catalogue.data.gov.bc.ca/dataset/annika-has-great-hair/resource/a3b52663-2c95-4cae-bdaf-2ba261720eba) to upload a file and the wheel keeps spinning and nothing is saved.  

This should be moved back to Spring backlog.

**Comment by sheilamv** [comment]
when creating a new resource and uploading a file, it works fine.  When uploading another file to an existing resource, the circle spins and spins and doesn't save.
@TerryLanktree , do you want this sent back for fixing, or close this and create another ticket for uploading a file to an existing resource?
cc. @BrandonSharratt

**Comment by TerryLanktree** [comment]
Sounds like a different issue, let's go with a new ticket.
