### ISSUE TITLE
Resource Application Preview

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#416]
1.9.0-b15b897Api Version: 2.7.5

How the Preview button should present for Applications?

**Preview Button**
1. Should this exist or be removed for Apps?
1. Should it open the app in another tab?

**Download Button**
 * Download not make sense in the toolbar options for an application.
 * Currently it opens the app.
 * This functionality used to be be called Download/Access which was cleared for Webservices/APIs and Applications.

This also relates to 
#393 - Toolbars
#364 - Terminology used in relationship to Access/Download

**Comment by TerryLanktree** [comment]
@BrandonSharratt How difficult is it to make the buttons context sensitive based on resource type?  If resource is Application, do not contain Preview nor Access, but have a Launch button?

**Comment by cpspicer** [comment]
Brandon - yes, buttons can be contextual based on record type, but wants a mapping (record type to buttons).

Application ->  (terry to populate)
Tabular ->  (terry to populate)
Geographic ->  (terry to populate)
Services ->  (terry to populate)

**Comment by TerryLanktree** [comment]
this is very similar to #364 , need to rationalize
