### ISSUE TITLE
"Order By" value resets to default when filter applied

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#417]
In the datasets view, the sorting ("Order by:") option currently defaults to "Relevance".  When the user applies any filter (e.g., a "Licence" filter), the sorting option reverts back to the default even where the user has chosen a different value.

Tested in Toyger using version `b15b897`.

**Steps to reproduce:**
* Navigate to the datasets view
* Set the sorting option to "First Published"
* Set the "License" filter to "Access Only"

**Result:**  The sorting option is reset to "Relevance"

**Comment by BrandonSharratt** [comment]
Duplicated by ckan-ui#410
