### ISSUE TITLE
Confirmation for successful log out should be green

### ISSUE THREAD

**Issue by yuisotozaki** [bcgov/ckan-ui#425]
When the user logs out, the successful logout confirmation banner should be in green with a checkmark. Just like when a dataset is successfully edited. The text could be simplified to "You're now logged out."

![image.png](https://images.zenhubusercontent.com/5e3c6715d85e5dced833aef6/3f94773a-7f8a-4889-8d02-d065e6bc6d2b)
![image](https://user-images.githubusercontent.com/56084999/111341777-0fb86c80-8637-11eb-883d-7fb9beb43e32.png)

**Comment by sheilamv** [comment]
Tested in Toyger.  This has passed and can be part of a pull request to Beta for Open Beta Testing.

**Comment by sheilamv** [comment]
Tested and passed.
