### ISSUE TITLE
Copy functionality at the record level

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#433]
This is missing functionality in Toyger which is in Cat Classic.   User has the ability to copy the metadata record in the current catalogue

- In the new catalogue, the user should be able to take an existing record, regardless of state, and copy it to create a new draft record.

- Resource(s) can be optionally selected as part of the copy function but not a requirement.  

@annikaLiving , please add any other details here to groom the ticket for @TerryLanktree and @SteveChapmanBCDX to preview and prioritize.

**Comment by TerryLanktree** [comment]
@BrandonSharratt Please add a copy record button for editors.  This should be equivalent to "Add Dataset" button, but with all the fields of the current record copied over except Title and URL, which must be unique.

**Comment by sheilamv** [comment]
@annikaLiving was able to clone a dataset for which she is an editor of the organization (no group).  It had a resource, but there was no option to clone the resource with the record.  System assumes that a resource is not part of the copy function.  It should be optional as part of the copy process.

**Comment by sheilamv** [comment]
@TerryLanktree and @annikaLiving  - should an editor of Organization A be able to clone a record from an organization B and change Organization to A?  The issue we are running into is that Editor from org A can't select Draft as the state on the cloned record, therefore, unable to create the clone, as it is assuming that the editor needs to be on the org B, when it doesn't since the cloned record's org is A.

**Comment by sheilamv** [comment]
IF the copy function should only be allowed on records associated to the editor/admin's organization, then Copy Dataset link should not be visible to the logged in user along with the Edit dataset, Delete dataset, Add resource.  I think this issue is more about the menu bar, than the copy function.

**Comment by TerryLanktree** [comment]
@sheilamv Please check your permissions.  I am an editor and I can only copy datasets that I can edit.  Perhaps the logic needs some work, but that could be for 2.1.  Right now, it seems to work for me.  It may be Admin gets different results (perhaps Admin gets copy button, but cannot use on groups they don't belong to?) but I believe there will be few Admin accounts, and only internal.  Please correct this if wrong.

**Comment by sheilamv** [comment]
@TerryLanktree , @annikaLiving  - I am able to copy a metadata record only (no ability to select one, some or all resources).  Only the ability to copy the dataset is working.  I will say this is complete and add the enhancement of being able to change the organization as an editor to another organization of which I am an editor and the ability to select one, some, all or no resources as part of the copy function.
