### ISSUE TITLE
Groups/Orgs Caching Issue

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#443]
If a sysadmin has gone into edit mode for a Group or Org, if they then try to create a new one, it takes them to edit mode of the last Org/Group they opened.

Steps:
1. Navigate to a Group
1. Click edit
1. Click Cancel
1. Click Create Group
    * all the fields will be populated with the Group previously reviewed.
1. Now change the name of the Group.
    * Results in the original Group being edited.

**Comment by sheilamv** [comment]
@annikaLiving , the steps provided above are not how I am able to test.  

1. Navigate to Group ([Sheila Group testing for #443](https://beta-catalogue.data.gov.bc.ca/group/sheila-group-testing-for-443))
2. Click Edit Group (system displays Edit Group popup) 
3. Click Cancel (system closes popup and returns user to Group ([Sheila Group testing for #443](https://beta-catalogue.data.gov.bc.ca/group/sheila-group-testing-for-443)))
4. Click Create Group

ACTUAL:  This button is not visible from the group page.  I must select [Back to Group list](https://beta-catalogue.data.gov.bc.ca/groups) link to see the button.  Text of button is Add Group.  When I select the button is displays Add Group popup and all fields are empty ready.

I can't perform or reproduce step 5 and your outcome.  I believe the fix has achieved the desired result. 

HOWEVER, I did notice that when creating a new group, the URL is not automatically created, like it does when creating an Dataset and Organizations.  

I am closing this ticket as fixed, but @TerryLanktree , should I enter a new ticket for the URL not auto creating when typing in the name of the Group?
