### ISSUE TITLE
Secure Groups - Remove visibility from API and UI when logged out

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#447]
Secure Groups
1. Hide from API unless user provides API Key.
2. Hide from UI when not logged in.
> Explore Dataset Groups, all private groups should be hidden
> Explore by Datasets, all private groups should not be displayed in the list of Groups under Search under Filter Search Results. 
3. Hide from the record when clicking on what Group, it is in the Group.

**Comment by annikaLiving** [comment]
@TerryLanktree  this may require more than one tix.

**Comment by cpspicer** [comment]
Annika to turn into more tix (2? 3? 8?)

**Comment by cpspicer** [comment]
GBA URL can be called without being logged in.   i.e. security by obscurity.

**Comment by TerryLanktree** [comment]
If group security is recognized by the API, then we should not have to modify the UI, it should automatically restrict secure groups.

**Comment by sheilamv** [comment]
No API testing required.  I have tested the UI:  PASSED

- Unable to filter datasets by, or view Groups which are deemed Private.
