### ISSUE TITLE
Deleting a record should present a confirmation message to the user

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#448]
See https://proj.data.gov.bc.ca/jira/browse/DPS-524 for UAT details.  

- When deleting a **Resource** associated to a Dataset (https://toyger.data.gov.bc.ca/dataset/tire-stewardship-bc-tire-recycling-data) in any state, the system should provide a confirmation message to allow the editor/admin to back out of the action should they not wish to follow through with the deletion.

- I then proceeded to delete the dataset(https://toyger.data.gov.bc.ca/dataset/tire-stewardship-bc-tire-recycling-data), and it allowed me to do so without any confirmation. As above, the system should provide a confirmation message to allow the editor/admin to back out of the action should they not wish to follow through the deletion. 

- I took the URL and entered it into another tab (same session) and displayed **! You are viewing a deleted dataset** message

**BUG**:  Logged in as Admin, I was able to delete a Dataset in Published state.  This is wrong.

**Comment by sheilamv** [comment]
@TerryLanktree, I have added this to your PO Review queue.

**Comment by TerryLanktree** [comment]
@sheilamv I do not have access to ADMIN account, please document how the saves works vs. should work for each of the different types of users.  Right now, ad editor, I do not have a delete button.  Should Editors be allowed to delete a draft record they create?

**Comment by sheilamv** [comment]
[DDS-235 - State Machine.pdf](https://github.com/bcgov/ckan-ui/files/6299678/DDS-235.-.State.Machine.pdf)

According to this state machine diagram, only Editors and/or Admins can delete records (dataset) only when the state = Draft, however, it does not explicitly state that they must be an editor/admin of the organization - but that is a given, noting the state change can only be done by the editor/admin must be associated to the dataset's organization. 

Now with that said, resources could be a different story.  That has not been flushed out. Looking for your input on this:

- _Resources_ can only be **DELETED** by an editor/admin of the associated dataset/record's Organization
- System must provide a popup confirmation of deletion with the option to Cancel the deletion and Continue to complete the deletion
- _Resources_ can be **DELETED** at any time, regardless of the state (**Admins** - any state, **Editors**, any state but Pending Archived or Archived)
- _Datasets/Records_ can only be **DELETED** when in _Draft_ state and by an editor/admin of its Organization
- As above, system must provide a popup confirmation of deletion with the option to Cancel the deletion and Continue to complete the deletion

@annikaLiving , @TerryLanktree , can you please confirm the above regarding Resources to be accurate and true to the business?

**Comment by TerryLanktree** [comment]
Sounds like what I would expect.  I, as an Editor, can only delete Resources, not the Dataset.  In this, I am looking at a record I created, which is in Draft.

**Comment by sheilamv** [comment]
@TerryLanktree , fourth bullet point above states that both an **editor** or **admin** can _delete_ a dataset.  The dataset state must be _Draft_.  That is not how it currently works. I could delete a _published_ record (metadata/dataset).

**Comment by TerryLanktree** [comment]
@sheilamv that is not how it works for me, which is why I brought it up.  I am an editor, and I cannot delete a record that I made.  Record is in draft.  I want to see if we can figure out why you can delete in any state while I cannot delete in Draft.  We need to review Keycloak before proceeding.

**Comment by TerryLanktree** [comment]
To keep things succinct.  This ticket will only deal with the title issue: a confirmation dialogue box.  Other items will be placed in a separate ticket.
@BrandonSharratt please add a dialogue pop-up for each "delete" action.  "This will permanently delete this information.  Continue?" with OK/Cancel buttons.

**Comment by sheilamv** [comment]
I have tested this and was not able to delete a draft record as an editor of Tenure and Geoscience sub-org.  

- Copied an existing published record
- No Delete link visible (so not able to delete the record)
- Message displayed - but needs rewording

**Message**:  <same as production message>

**DEFECT**:  Editor was not able to delete a record in Draft state

NOTE:  Sys Admin can delete a record in Draft state

**Comment by joe-taylor** [comment]
@sheilamv, per [Terry's comment](https://github.com/bcgov/ckan-ui/issues/448#issuecomment-818923451), the latest patch only strived to add a dialog box to existing delete buttons. It should not have changed the visibility thereof one way or another.

**Comment by sheilamv** [comment]
@joe-taylor , the message presented should be updated, if that is okay.  I will address the visiblity in another ticket and reference this one as it holds all the details.

**Comment by joe-taylor** [comment]
That's totally fine. Rephrasing the message will be straightforward. Changing the popup header and buttons on the other hand requires a totally different approach.

I opted for the browser's built in dialog box to keep things simple and triage my effort. The tradeoff is control over the title and buttons. To achieve that level of control I would need to mock up a custom on-page modal dialog and using that instead of the browser's built-in confirmation dialog.

**With MVP in mind, I wonder if it's sufficient to change the message to what you suggest and leave the buttons and confirmation title alone for now?** Then, I propose we tackle the custom UI element as an enhancement in a separate ticket.

**Comment by sheilamv** [comment]
@joe-taylor , as per our conversation, I will create two new tickets and linke to this one.  

1. ticket to address the UI/UX part
> Header Text
> Button presentation and logic

2. ticket to address the Delete icon on a record and/or resource
> details on who can see the delete function on each object and record state

Feel free to address on the message changes by object, noted above, and as per our conversation.

**Comment by sheilamv** [comment]
Testing in Beta;

1. when trying to delete a draft record, system displays the appropriate popup message
2. when trying to delete a resource, system displays the appropriate popup message

**New Defect**: user is able to delete a record (and its resources) when the state <> Draft.  A new ticket will be entered to address this.
