### ISSUE TITLE
About page spelling mistakes and URL issues

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#473]
_Snippet of text needing fixing_

**BC Data Catalogue**
Finding, exploring and accessing data, services and applications that have been _catalogue_ by BC Government and Broader Public Sector organizations.

---------------
ISSUES: 

- catalogue by should be **published by**

**Comment by annikaLiving** [comment]
@sheilamv i have updated the catalogue by to published by and the url to the portal is correct.

**Comment by sheilamv** [comment]
This has not been fixed - 

**BC Data Catalogue**

**Purpose**

- Finding, exploring and accessing data, services and application have have been published by BC Government and Broader Public Sector organizations

**Comment by TerryLanktree** [comment]
You will find this in the hamburger/pancakes under "About".

**Comment by joe-taylor** [comment]
Since I was in there already to make another change, I went ahead and fixed this.

**Comment by TerryLanktree** [comment]
Still incorrect -- "have have" should be "that have"

Finding, exploring and accessing data, services and application have have been published by BC Government and Broader Public Sector organizations

**Comment by joe-taylor** [comment]
Oh wow - updated.
