### ISSUE TITLE
Modify production with banner ("Go to Beta")

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#481]
This request is to place a banner with Beta URL to 'check out' the Beta application.  This will be added when we have finished Beta testing with Custodians/Editors.  This  is for the general public/user, etc.

https://proj.data.gov.bc.ca/jira/browse/DDS-180

**Comment by TerryLanktree** [comment]
We have a new look coming! If you want a sneak-peak, check out the beta site. Keep in mind the information may not be current, please come back here to do "real" searches.

**Comment by TerryLanktree** [comment]
set up for deploy, but do not deploy until we are ready.

**Comment by BrandonSharratt** [comment]
Created branch 'banner' in ckanext-bcgov  off of prod, it has the above text at the very top, and bumps eveything down by 29px (the height of the banner)

**Comment by cpspicer** [comment]
Ready to go live - just say the word Terry
