### ISSUE TITLE
OFI Resources - URL needs to be hidden on Resource

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#489]
The URL listed on the BCGW Custom Download resource needs to be hidden as it is in cat classic.

This URL doesn't work on it's own and must be access with the Request Access button on the Resource Card or the Resource Toolbar., thus a user will be confused on how to get access and think download doesn't work.

**Comment by joe-taylor** [comment]
For reference in testing later, here's a random sample of OFI resources and their pages in prod. On these pages, the URL should be hidden.

 [fadm-provincial-forest-addition](https://catalogue.data.gov.bc.ca/dataset/fadm-provincial-forest-addition/resource/facd5c71-86bf-407b-b2e4-7a32a4114d32)
 [aquifer-vulnerability-to-saltwater-intrusion-pumping-and-coastal-hazard](https://catalogue.data.gov.bc.ca/dataset/aquifer-vulnerability-to-saltwater-intrusion-pumping-and-coastal-hazard/resource/df2d3b34-b916-47c5-8e2b-3cb82d732279)
 [oil-and-gas-commission-changes-in-and-about-a-stream-applications](https://catalogue.data.gov.bc.ca/dataset/oil-and-gas-commission-changes-in-and-about-a-stream-applications/resource/f6736951-9e9f-4ba1-bcf9-3acf1f667fac)
 [bc-major-watersheds](https://catalogue.data.gov.bc.ca/dataset/bc-major-watersheds/resource/0ebae863-42f2-42fc-bb93-af7e97d7668c)
 [ungulate-winter-range-proposed](https://catalogue.data.gov.bc.ca/dataset/ungulate-winter-range-proposed/resource/e31fdec2-ff7c-40b9-a525-04cd1f7a8ea1)
 [conservation-cross-reference-table](https://catalogue.data.gov.bc.ca/dataset/conservation-cross-reference-table/resource/fa9f8d96-e204-4b07-89e7-69777a6350b5)
 [nts-50k-grid-digital-baseline-mapping-at-1-50-000-nts](https://catalogue.data.gov.bc.ca/dataset/nts-50k-grid-digital-baseline-mapping-at-1-50-000-nts/resource/ed651f83-f82a-4388-b977-3e67afe67e86)
 [mta-coal-grid-unit](https://catalogue.data.gov.bc.ca/dataset/mta-coal-grid-unit/resource/3de0bcee-4c80-4669-acbb-efb03b0f65da)
 [protected-lands-access-restrictions](https://catalogue.data.gov.bc.ca/dataset/protected-lands-access-restrictions/resource/ee288450-40c1-425c-8f74-69b5066a5fe6)
 [nts-bc-designated-area-points-1-250-000-digital-baseline-mapping-nts](https://catalogue.data.gov.bc.ca/dataset/nts-bc-designated-area-points-1-250-000-digital-baseline-mapping-nts/resource/68b9e22e-9466-4d34-980d-cae6bb0b0c98)

<details><summary>SQL select statement</summary><pre>select
  concat('[', package.name ,'](https://catalogue.data.gov.bc.ca/dataset/', package.name, '/resource/', resource.id, ')') url
from package
inner join package_extra
  on package_extra.package_id = package.id and
     package_extra.key = 'download_audience'
inner join resource
  on resource.package_id = package.id and
     resource.state = 'active'
where
  package_extra.value in ('Public', 'Not downloadable') and
  package.state = 'active' and
  resource.extras::json->>'ofi' = 'true'
order by random()
limit 10;</pre></div></details>

Now, here's a sample of non-OFI resources, linked to corresponding prod pages. On these pages, the URL should be shown.

 [summerland-district-of-2007-community-energy-and-emissions-inventory-report](https://catalogue.data.gov.bc.ca/dataset/summerland-district-of-2007-community-energy-and-emissions-inventory-report/resource/2620ff64-21fc-4d04-974a-2dffa4cf3f1a)
 [how-about-this](https://catalogue.data.gov.bc.ca/dataset/how-about-this/resource/1e36f126-d2f1-4261-8460-0c4cd75134ef)
 [railway-markerpost-point](https://catalogue.data.gov.bc.ca/dataset/railway-markerpost-point/resource/762960aa-7be5-477e-9649-312bd8ad7b31)
 [mount-polley-sampling-sites-data](https://catalogue.data.gov.bc.ca/dataset/mount-polley-sampling-sites-data/resource/cf89d421-8edf-4530-968d-28f17e59a2fe)
 [census-marital-status-profiles-by-sex-and-relationship-type-for-chsa-2016-census](https://catalogue.data.gov.bc.ca/dataset/census-marital-status-profiles-by-sex-and-relationship-type-for-chsa-2016-census/resource/08be6c3c-2336-44db-b60a-83961ac5b214)
 [north-cowichan-land-parcels](https://catalogue.data.gov.bc.ca/dataset/north-cowichan-land-parcels/resource/4e6cee06-52ab-4db9-a19f-191ce848f009)
 [other-forest-carbon-initiative-projects](https://catalogue.data.gov.bc.ca/dataset/other-forest-carbon-initiative-projects/resource/9081b9c1-a01e-44e1-ab8b-b189ad73bac4)
 [shorezone-biobanding-polygons](https://catalogue.data.gov.bc.ca/dataset/shorezone-biobanding-polygons/resource/496ccdaa-e4fa-4269-85ce-e077b3d2631a)
 [local-government-tax-rates-and-assessments-assessed-values-2009](https://catalogue.data.gov.bc.ca/dataset/local-government-tax-rates-and-assessments-assessed-values-2009/resource/06302d22-28dc-4538-a6f3-06e6eb4d7a2f)
[georgia-basin-ecosystem-initiative-boundary-polygon](https://catalogue.data.gov.bc.ca/dataset/georgia-basin-ecosystem-initiative-boundary-polygon/resource/f34527d0-fce0-4b41-9f12-d82a6beca123)

<details><summary>SQL select statement</summary><pre>select
  concat('[', package.name ,'](https://catalogue.data.gov.bc.ca/dataset/', package.name, '/resource/', resource.id, ')') url
from package
inner join package_extra
  on package_extra.package_id = package.id and
     package_extra.key = 'download_audience'
inner join resource
  on resource.package_id = package.id and
     resource.state = 'active'
where
  package_extra.value in ('Public', 'Not downloadable') and
  resource.extras::json->>'ofi' is null and
  package.state = 'active'
order by random();</pre></div></details>

**Comment by joe-taylor** [comment]
Removing the highlighted parts of the interface for OFI resources, those being resources where the "Request Access" button is visible.

![image](https://user-images.githubusercontent.com/5297264/130291309-17d6342f-fb2d-43d1-b19e-17e851c9296a.png)

**Comment by sheilamv** [comment]
Passed.

**Comment by sheilamv** [comment]
URL is hidden as requested and tested - ready for production
