### ISSUE TITLE
Migrated data not presenting file size for resources on some datasets in Beta/Toyger

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#494]
This is only affecting the display.  The migrated files are able to be downloaded.  

**Beta Catalogue**:  https://beta-catalogue.data.gov.bc.ca/dataset/4cf233c2-f020-4f7a-9b87-1923252fbc24

![image.png](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/64bb2da4-1dfd-4816-bb66-a60f5f02f2d7)

- the display of the resources o the metadata page is misleading when displaying the size a 0.0 MB

**Current Catalogue (CC) dataset**:  https://catalogue.data.gov.bc.ca/dataset/4cf233c2-f020-4f7a-9b87-1923252fbc24 

![image.png](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/d3e6d111-3f75-45a9-8f95-44ac5812ea9d)

- the display of the resource on the metadata page doesn't display the file size in CC.

**Comment by TerryLanktree** [comment]
If size = 0mb hide it.

**Comment by sheilamv** [comment]
tested and passed.

**Comment by sheilamv** [comment]
tested and passed in Beta - ready for production.
