### ISSUE TITLE
Search: Organization not returning correct orgs

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#498]
By searching the organization page does not return the org or word in question.

Logged out:
* DataBC
** Result: all sub-orgs under two ministries that do not contain DataBC
* Knowledge: 
** Result: all sub-orgs under two ministries that do not contain Knowledge
** However did at one point as logged in as sysadmin get MOE to show up.

This was verified by Terry and Annika

**Comment by joe-taylor** [comment]
It was returning the first N organizations in the list based on the number N of parent organizations that matched the search or had a suborg that matched the search. It was supposed to return the matching parent organizations themselves.

More could be improved but calling this one done for now.

**Comment by sheilamv** [comment]
STR:

1. Not logged in
2. Hamburger > Explore by Organizations
3. Search for DataBC
**Expected**: One ministry and its branches
**Actual**: One MInistry (Ministry of Citizen Services) and 14 branches (one being DataBC)

**PASS**

3. Search for Knowledge
Expected: Unsure (@annikaLiving - can you tell me what you are expecting)
Actual:  Two Ministries (FLNRORD, ECCS) - each ministry having a branch with Knowledge in the name

I think this is a **pass**, but need to know what you consider to be a pass.

**Comment by joe-taylor** [comment]
I believe this is working as designed now but agree that it should filter suborgs or at least draw attention to the matching ones.

**Comment by annikaLiving** [comment]
@joe-taylor @sheilamv indeed the search is now coming back with the ministries that a branch with the word searched on is associated with. this is an improvement as this is not what it did before, the results returned minstries without a branch with the search word.

however, i agree there an opportunity for an enhancement to bring back only the branches vs the ministry and all of its branches.

**Comment by joe-taylor** [comment]
I believe we have consensus that this aspect should be improved but my key question is whether to work on it pre or post MVP, and should we use this ticket for that enhancement or create a new one where we can flesh out the desired behaviour.

**Comment by TerryLanktree** [comment]
If the functionality is working, let's table enhancements until post launch.  I see lots of room for improvements, but it now resides in the "warts and all" category.  @sheilamv  please enter as an enhancement ticket - including alphabetizing and opening the Ministry (highlight the item?) when doing a search

**Comment by sheilamv** [comment]
@TerryLanktree , this is a tested ticket, that should stay in MVP and move to Beta for testing.  I will add a JIRA ticket for the enhancement.

**Comment by sheilamv** [comment]
**STR**:

- Not logged in
- Hamburger > Explore by Organizations
- Search for DataBC

- **Expected**: One ministry and its branches
- **Actual**: One MInistry (Ministry of Citizen Services) and 14 branches (one being DataBC)

**PASSED**

- Search for Knowledge

- **Expected**: Two Ministries and their branches
- **Actual**: Two Ministries (FLNRORD, ECCS) - each ministry having a branch with Knowledge in the name
**PASSED**
