### ISSUE TITLE
Search Issues - Magnifying glass results in no results unless changing sort order - clearing search does clear results

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#504]
1. When doing multiple searches and then clearing the search and then searching again using the magnifying glass a user is prompted with what looks like nothing but if you change the search order the results will appear.

- When doing multiple searches and then clearing the search and then searching again using the magnifying glass a user is prompted with what looks like nothing but if you change the search order the results will appear.

- below is what a user sees when they click enter after clearing their search and hitting enter and then searching again. there should be 4 results for "market outlook"
![image](https://user-images.githubusercontent.com/32690119/124615991-95506a00-de2a-11eb-8c00-a892e4563c8c.png)
- if you then click on the sort order it then will show the 4 results.

2. Clearing the search terms from the magnifying glass does not reset the search results page to all records.

as the magnifying glass presents so much confusion, suggest removing it.

**Comment by joe-taylor** [comment]
@annikaLiving Is this still an issue? I was not able to replicate.

**Comment by sheilamv** [comment]
- I am able to reproduce in Beta.
- I am not able to reproduce in Toyger.  

I am not sure if other tickets have resolved this issue, but using the magnifying glass (left of the hamburger), I am able to bring back filtered results without having to modify the Order By selection in Toyger. 

Recommendation to @TerryLanktree is to move to **Ready for Beta** for testing after the next push from Toyger to Beta, as no work is required to modify Toyger.

**Comment by sheilamv** [comment]
Unable to reproduce the issue in Beta environment.  Passed.
