### ISSUE TITLE
BETA:  Preview button on Resource not producing the expected results

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#508]
From Colin Newell:

Resource: https://beta-catalogue.data.gov.bc.ca/dataset/parcelmap-bc-parcel-polygons/resource/ab87d159-a059-4dbf-9da5-221c37e5f63e

Press “preview” to get error message.

-----------

From: DataBC CITZ:EX <Data@gov.bc.ca> 
Sent: July 20, 2021 6:43 AM
To: Newall, Colin G CITZ:EX <Colin.Newall@gov.bc.ca>
Cc: CITZ DPD DSS Data Discovery Services <DPDDSDDS@Victoria1.gov.bc.ca>
Subject: RE: BETA - catalogue

New Catalogue looks awesome!  Great work!

I clicked “preview” for the PMBC record and this error appeared – is it supposed to work?

![BETA SMK Error.jpg](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/187e9705-aa43-4add-ad92-7f35952243ba)

Thank you,

Colin Newall
Team Lead, Data Management

**Comment by joe-taylor** [comment]
Although it's possible the map preview isn't supposed to work for this record, as that record relies on the order filler interface, I can see that the issue described above occurs whenever an invalid lat,lon,zoom triplet is provided through the smk-center parameter of the preview page.

 - https://bcdc-smk.data.gov.bc.ca/?smk-center=,, - doesn't work
 - https://bcdc-smk.data.gov.bc.ca/?smk-center=0,0,0 - works

Updating the code so as to not pass values which will trigger the above error is a simple path forward, but with status quo it's possible that preview windows will in many cases load a regular blank map with no extra layers, so I'd like to investigate further to get a better understanding of the problem and alternate solutions.

**Comment by joe-taylor** [comment]
With the way the preview button is engineered currently, logic to disable it where it is not applicable is relatively straightforward to implement, at least in the majority of cases. I've written some code to accomplish this and can send it through to code review if the team is amenable.

**Comment by alixcote** [comment]
Annika/Joe to follow up on logic

**Comment by joe-taylor** [comment]
We've decided to move this forward but will revisit whether some preview windows are hidden that shouldn't be at the UAT stage.

**Comment by joe-taylor** [comment]
Feature to disable the preview button for records it doesn't apply for is ready for code and UAT review.

**Comment by joe-taylor** [comment]
The latest changes haven't been merged to toyger yet.

**Comment by sheilamv** [comment]
### Selecting the Preview Button on each Resource by Resource Data Type

**Testing** - Resource Data Types = **wms, kml**
- https://toyger.data.gov.bc.ca/dataset/natural-disturbance-type-map
- _Result_:  All three resources preview without error.

**Testing** - Resource Data Type = **arcgis_rest**
- https://toyger.data.gov.bc.ca/dataset/stand-level-biodiversity-frep-data-sampling-up-to-2019-
- _Results_:  no error, but nothing displayed
![image](https://user-images.githubusercontent.com/65407822/131709144-b3e57d89-5031-4cfb-9d5a-f05330927f8e.png)

**Testing** - Resource Data Type = **csv**
- https://toyger.data.gov.bc.ca/dataset/bc-geographic-warehouse-object-structure-change-history
- _Results_: no error, but message displayed 
![image](https://user-images.githubusercontent.com/65407822/131712337-06a2546c-7db5-4b49-8919-c506fadc87d2.png)

**Testing** - Resource Data Type = **e00** (mapped to Other)
- https://toyger.data.gov.bc.ca/dataset/bc-geographic-warehouse-object-structure-change-history
- _Results_: no error, but message displayed 
![image](https://user-images.githubusercontent.com/65407822/131714169-3e444959-31e6-4173-8a47-e001430076ed.png)

**Testing** - Resource Data Type = **fgdb** (mapped to Other)
- https://toyger.data.gov.bc.ca/dataset/internet-connectivity-in-relation-to-b-c-health-geographies-map
- _Results_:  no error, but message displayed 
![image](https://user-images.githubusercontent.com/65407822/131716746-2efdd347-0eab-4a75-879e-0fc58be4e1cd.png)

**Testing** - Resource Data Type = **geojson**
- https://toyger.data.gov.bc.ca/dataset/translink-major-road-network
- _Results_: no error, but nothing displayed 
![image](https://user-images.githubusercontent.com/65407822/131717913-0ffc27ec-3f7d-4b7c-82a7-6001ab13a36c.png)

**Testing** - Resource Data Type = **html**
- https://toyger.data.gov.bc.ca/dataset/forest-inventory-ground-sample-data-and-interactive-map
- _Results_: no error, but nothing displayed 
![image](https://user-images.githubusercontent.com/65407822/131718795-0a21c4a0-aff4-42bb-a53b-fd2c2e7c6047.png)

**Testing** - Resource Data Type = **json**
- https://toyger.data.gov.bc.ca/dataset/howe-sound-cumulative-effects-project-area-data-howe-sound-cumulative-effects
- _Results_: no error, but nothing displayed 
![image](https://user-images.githubusercontent.com/65407822/131719123-ecd28458-4e62-427e-9fda-c59b8a44d442.png)

**Testing** - Resource Data Type = **kmz**
- https://toyger.data.gov.bc.ca/dataset/meteorological-monitoring-sites
- _Results_: map displayed and View in iMapBC button 
![image](https://user-images.githubusercontent.com/65407822/131719410-fbd9926d-d570-4d57-b858-5d11064b5580.png)

**Testing** - Resource Data Type = **Multiple**
- https://toyger.data.gov.bc.ca/dataset/archaeology-known-sites
- _Results_: no error, but message displayed 
![image](https://user-images.githubusercontent.com/65407822/131720972-8f222d06-4fd1-4f26-b01f-801ef133da0f.png)

**Testing** - Resource Data Type = **openapi-json**
- https://toyger.data.gov.bc.ca/dataset/common-document-generation-service-api
- _Results_: no error, but message displayed 
![image](https://user-images.githubusercontent.com/65407822/131721276-ae9677b0-42ef-4c9f-9099-0c80e5a2e9d7.png)

**Testing** - Resource Data Type = **other**
- https://toyger.data.gov.bc.ca/dataset/muskwa-kechika-report-to-the-premier-and-public-of-bc-web-viewer-2018
- _Results_:  no error, but message displayed 
![image](https://user-images.githubusercontent.com/65407822/131721660-bac0eb3b-20f0-4e23-87d1-06981d17a258.png)

**Testing** - Resource Data Type = **pdf**
- https://toyger.data.gov.bc.ca/dataset/metadata-for-k-to-12-socio-economic-status-ses-index
- _Results_:  no error, but message displayed 
![image](https://user-images.githubusercontent.com/65407822/131721827-a78dbab7-9115-4c55-96aa-ef968c8a8cf7.png)

**Testing** - Resource Data Type = **shp**
- https://toyger.data.gov.bc.ca/dataset/hexagonal-polygon-grid-resolution-4096-hectare-cell
- _Results_:  no error, but nothing displayed 
![image](https://user-images.githubusercontent.com/65407822/131722307-7f8fbf2f-a18a-4a80-8a1f-45790b3c6de7.png)

**Testing** - Resource Data Type = **txt**
- https://toyger.data.gov.bc.ca/dataset/urgent-and-primary-care-centres
- _Results_:  a map was displayed (**data issue?**) 
![image](https://user-images.githubusercontent.com/65407822/131722577-4d988051-1cd9-4cb9-b1fe-05ef0c9ad474.png)

**Testing** - Resource Data Type = **xls**
- https://toyger.data.gov.bc.ca/dataset/bc-finance-budget-2019
- _Results_: no error, but message displayed  
![image](https://user-images.githubusercontent.com/65407822/131722811-f28508e0-e7f0-4933-a924-5c62e23dcfdf.png)

**Testing** - Resource Data Type = **xlsx**
- https://toyger.data.gov.bc.ca/dataset/bc-finance-budget-2019
- _Results_: no error, but message displayed  
![image](https://user-images.githubusercontent.com/65407822/131723238-02b001af-2fc3-42c6-abba-9c80e2427980.png)

**Testing** - Resource Data Type = **xml**
- https://toyger.data.gov.bc.ca/dataset/bedrock-geology
- _Results_: a map was displayed (**data issue?**) 
![image](https://user-images.githubusercontent.com/65407822/131723452-eaa5370b-a087-4a37-a3dc-01f83a0dacce.png)

**Testing** - Resource Data Type = **zip**
- https://toyger.data.gov.bc.ca/dataset/province-of-british-columbia-boundary-terrestrial
- _Results_:   no error, but nothing displayed 
![image](https://user-images.githubusercontent.com/65407822/131723604-6ebeb3df-adb9-406a-9bda-ce4b3c03d14a.png)

Action thoughts:

1. Confirm the issues noted as data issue
2. Discuss how to handle the ability to select Preview link when nothing is displayed

**Comment by joe-taylor** [comment]
Please note that QA was undertaken before code changes were pushed through to toyger so while there may be useful information about errors overlooked before this is not a review of recent work completed.

**Comment by joe-taylor** [comment]
This has been migrated to toyger but you may need to clear your browsers cache or hold shift and click reload to get the changes to show up.

**Comment by sheilamv** [comment]
Not logged in to do this testing.

**Resource Data Type** = _arcgis_rest_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/stand-level-biodiversity-frep-data-sampling-up-to-2019-
_Resource_: https://toyger.data.gov.bc.ca/dataset/stand-level-biodiversity-frep-data-sampling-up-to-2019-/resource/060981fa-33bc-4383-b598-d844e205023e
_[Preview]_button **enabled**
_Results_: ![image](https://user-images.githubusercontent.com/65407822/131880798-f82b3ad5-001c-46ab-b94f-38c60b24b148.png)

**Resource Data Type** = _csv_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/hunter-sample-moose-survey-estimates-1976-to-current
_Resource_: https://toyger.data.gov.bc.ca/dataset/hunter-sample-moose-survey-estimates-1976-to-current/resource/fdec42f4-4883-43f4-95af-8a8fcb4ba504
_[Preview]_button **disabled**
_Results_: ![image](https://user-images.githubusercontent.com/65407822/131882734-32ddf222-04cd-4498-91c1-32ca459c6fd6.png)

**Resource Data Type** = _e00_ (mapped to _other_)
_Dataset_: https://toyger.data.gov.bc.ca/dataset/bc-canadian-aquatic-biomonitoring-network-cabin-sites-and-models-web-app
_Resource_: https://toyger.data.gov.bc.ca/dataset/bc-canadian-aquatic-biomonitoring-network-cabin-sites-and-models-web-app/resource/151c7801-a738-48bf-8fce-c9106d694575
_[Preview]_ button **disabled**
_Results_: as expected

**Resource Data Type** = _fgdb_ (mapped to _other_)
_Dataset_: https://toyger.data.gov.bc.ca/dataset/internet-connectivity-in-relation-to-b-c-health-geographies-map
_Resource_: https://toyger.data.gov.bc.ca/dataset/internet-connectivity-in-relation-to-b-c-health-geographies-map/resource/ca6b7e94-c9d6-4654-9cf9-b26bce39ec37
_[Preview]_ button **disabled**
_Results_: as expected

**Resource Data Type** = _geojson_ 
_Dataset_: https://toyger.data.gov.bc.ca/dataset/translink-major-road-network
_Resource_: https://toyger.data.gov.bc.ca/dataset/translink-major-road-network/resource/f2cbf48b-3217-4dd3-a2b1-97709467cee0
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131882777-15d396f6-faba-4d03-b999-ede66400bd6f.png)

**Resource Data Type** = _geojson_ 
_Dataset_: https://toyger.data.gov.bc.ca/dataset/translink-major-road-network
_Resource_: https://toyger.data.gov.bc.ca/dataset/translink-major-road-network/resource/f2cbf48b-3217-4dd3-a2b1-97709467cee0
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131883886-bd0ef589-6641-4f3e-a80e-b86996dfba94.png)

**Resource Data Type** = _html_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/forest-inventory-ground-sample-data-and-interactive-map
_Resource_: https://toyger.data.gov.bc.ca/dataset/forest-inventory-ground-sample-data-and-interactive-map/resource/9af955f4-83ba-4b26-a6c5-e9f8dcaec147
_[Preview]_ button **disabled**
_Results_: as expected

**Resource Data Type** = _json_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/howe-sound-cumulative-effects-project-area-data-howe-sound-cumulative-effects
_Resource_: https://toyger.data.gov.bc.ca/dataset/howe-sound-cumulative-effects-project-area-data-howe-sound-cumulative-effects/resource/8eca5485-8f58-4665-94fd-52ba5d0959de
_[Preview]_ button **disabled**
_Results_: as expected

**Resource Data Type** = _kml_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/natural-disturbance-type-map
_Resource_: https://toyger.data.gov.bc.ca/dataset/natural-disturbance-type-map/resource/263926a8-c3db-4480-ac90-b52067f9e42e
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131884380-63e7587a-175c-45e2-8eae-8232c26fd8b4.png)

**Resource Data Type** = _kmz_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/meteorological-monitoring-sites
_Resource_: https://toyger.data.gov.bc.ca/dataset/meteorological-monitoring-sites/resource/a2085229-e5f5-4c21-a5ec-dcf4867b6e02
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131886803-0e78f192-d99b-4837-b7a1-d6d4b1244748.png)

**Resource Data Type** = _mulitple_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/archaeology-known-sites
_Resource_: https://toyger.data.gov.bc.ca/dataset/archaeology-known-sites/resource/548bc387-0726-4036-bf09-f0cb067e0774
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131886879-4c1d5c86-d77e-4ed7-a17a-72bbd60c6fd0.png)

**QUESTION**:  _Should [Preview] button be disabled for this Resource Data Type?_ (@TerryLanktree , @annikaLiving , @joe-taylor , @adodge-bcg )

**Resource Data Type** = _openapi-json_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/common-document-generation-service-api
_Resource_: https://toyger.data.gov.bc.ca/dataset/common-document-generation-service-api/resource/3ab4504d-7647-427a-9f0d-7c1f75b6da90
_[Preview]_ button **disabled**
_Results_: as expected

**Resource Data Type** = _other_ (Application)
_Dataset_: https://toyger.data.gov.bc.ca/dataset/muskwa-kechika-report-to-the-premier-and-public-of-bc-web-viewer-2018
_Resource_: https://toyger.data.gov.bc.ca/dataset/muskwa-kechika-report-to-the-premier-and-public-of-bc-web-viewer-2018/resource/4f12e518-5127-4a2d-9f55-a1b545019bf0
_[Preview]_ button **disabled**
_Results_: as expected

**QUESTION**: _Should [Preview] button be disabled when Type is Application?_ (@TerryLanktree , @annikaLiving , @joe-taylor , @adodge-bcg )

**Resource Data Type** = _other_ (Geographic Data)
_Dataset_: https://toyger.data.gov.bc.ca/dataset/census-profile-key-facts-for-bc-census-divisions-2016-census
_Resource_: https://toyger.data.gov.bc.ca/dataset/census-profile-key-facts-for-bc-census-divisions-2016-census/resource/765dbbf3-5c30-4b45-9ab3-90d503f15c6b
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131888884-c71c3aea-eda0-443e-afe7-7a6c5087d7b4.png)

**Resource Data Type** = _pdf_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/graduation-assessments
_Resource_: https://toyger.data.gov.bc.ca/dataset/graduation-assessments/resource/be0e7d05-11ba-4883-a57a-900a0c3ed5e6
_[Preview]_ button **disabled**
_Results_: as expected

**Resource Data Type** = _shp_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/hexagonal-polygon-grid-resolution-4096-hectare-cell
_Resource_: https://toyger.data.gov.bc.ca/dataset/hexagonal-polygon-grid-resolution-4096-hectare-cell/resource/5b3cd331-7b22-47b0-9397-57833b33941d
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131890230-fb07440c-5b60-467c-b663-b48dbb57b149.png)

**QUESTION**: _When I filtered by **shp**, the result set looks confusing.  I am seeing more than that type returned. I also noticed that there is no way for me to provide the link to the result set like I can in Production.  I will add this an enhancement._ (@TerryLanktree , @annikaLiving , @joe-taylor , @adodge-bcg )

**Resource Data Type** = _txt_ (Geographic Data)
_Dataset_: https://toyger.data.gov.bc.ca/dataset/urgent-and-primary-care-centres
_Resource_: https://toyger.data.gov.bc.ca/dataset/urgent-and-primary-care-centres/resource/5c1bd7aa-48f1-403a-aa6d-aae08e971d33
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131891506-9fd35ed0-9c37-4c21-aecb-3e9a7cc7ceb0.png)

**QUESTION**: _Is this correct?  Could be a data migration issue.  Why would a txt resource Geographic Data resource and not a Tabular Data._ (@TerryLanktree , @annikaLiving , @joe-taylor , @adodge-bcg )

**Resource Data Type** = _wms_ (Webservice/API)
_Dataset_: https://toyger.data.gov.bc.ca/dataset/natural-disturbance-type-map
_Resource_: https://toyger.data.gov.bc.ca/dataset/natural-disturbance-type-map/resource/3a61e42c-18dc-4bcb-977d-479a9e5e945a
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131891898-57e512ba-c4cb-431f-9196-4682960a844c.png)

**Resource Data Type** = _xls_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/bc-finance-budget-2019
_Resource_: https://toyger.data.gov.bc.ca/dataset/bc-finance-budget-2019/resource/974e8efe-e786-4079-aab3-ba426a3383a2
_[Preview]_ button **disabled**
_Results_: as expected

**Resource Data Type** = _xlsx_
_Dataset_: https://toyger.data.gov.bc.ca/dataset/bc-finance-budget-2019
_Resource_: https://toyger.data.gov.bc.ca/dataset/bc-finance-budget-2019/resource/687a51ff-5b62-4f33-b895-f1202759f741
_[Preview]_ button **disabled**
_Results_: as expected

**Resource Data Type** = _xml_ (Geographic Data)
_Dataset_: https://toyger.data.gov.bc.ca/dataset/bedrock-geology
_Resource_: https://toyger.data.gov.bc.ca/dataset/bedrock-geology/resource/31f6fbb1-fa5c-477e-b252-0ddfe4201f3f
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131893335-7912cf66-75a1-4edb-ba9c-1ba0b3b808d7.png)

**Resource Data Type** = _zip_ (Geographic Data)
_Dataset_: https://toyger.data.gov.bc.ca/dataset/province-of-british-columbia-boundary-terrestrial
_Resource_: https://toyger.data.gov.bc.ca/dataset/province-of-british-columbia-boundary-terrestrial/resource/3d72cf36-ab53-4a2a-9988-a883d7488384
_[Preview]_ button **enabled**
_Results_: 
![image](https://user-images.githubusercontent.com/65407822/131893948-fe387551-8c19-4881-9e9e-cfbc1e318b0c.png)

**Comment by sheilamv** [comment]
Testing in https://beta-catalogue.data.gov.bc.ca/datasets

**Resource Data Type** =arcgis_rest
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-drought-levels-time-lapse-2020
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-drought-levels-time-lapse-2020/resource/4c6662f8-5497-46d4-9fe0-a7306ca0d76d
[Preview] button _enabled_
_Results_: as expected

**Resource Data Type** = csv
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-public-service-workforce-profiles
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-public-service-workforce-profiles/resource/f13a27fd-bf54-4222-a546-1a6b5abec39a
[Preview] button _disabled_
_Results_: as expected

**Resource Data Type** = e00 (mapped to other)
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/multiple-resource-value-assessment-coast-mountains-district-skeena-region-web-viewer
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/multiple-resource-value-assessment-coast-mountains-district-skeena-region-web-viewer/resource/c356cb0a-14bc-4c76-b833-1afee49645e3
[Preview] button _disabled_
_Results_: as expected

**Resource Data Type** = fgdb
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/terrain-mapping-ter-project-boundaries
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/terrain-mapping-ter-project-boundaries/resource/247e7804-95c2-4ef9-955d-204a312d3bac
[Preview] button _enabled_
_Results_: as expected (View iMapBC button)

**Resource Data Type** = geojson
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/translink-major-road-network
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/translink-major-road-network/resource/f2cbf48b-3217-4dd3-a2b1-97709467cee0
[Preview] button _enabled_
_Results_: as expected

**Resource Data Type** = html
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/census-profiles-for-bc-census-subdivisions-2016-census
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/census-profiles-for-bc-census-subdivisions-2016-census/resource/97522a75-43e3-42e7-bbb9-3b85759b1b2d
[Preview] button _enabled_
_Results_: as expected (View iMapBC button)

**Resource Data Type** = json
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/howe-sound-cumulative-effects-project-area-data-howe-sound-cumulative-effects
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/howe-sound-cumulative-effects-project-area-data-howe-sound-cumulative-effects/resource/8eca5485-8f58-4665-94fd-52ba5d0959de
[Preview] button _disabled_
_Results_: as expected

**Resource Data Type** = kml
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/terrestrial-protected-areas-representation-by-biogeoclimatic-zone-parc-
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/terrestrial-protected-areas-representation-by-biogeoclimatic-zone-parc-/resource/f658405b-2050-4db8-b8cd-ce76889862ab
[Preview] button _enabled_
_Results_: as expected (View in iMapBC button)

**Resource Data Type** = kmz
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/meteorological-monitoring-sites
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/meteorological-monitoring-sites/resource/a2085229-e5f5-4c21-a5ec-dcf4867b6e02
[Preview] button _enabled_
_Results_: as expected (View in iMapBC button)

**Resource Data Type** = openapi-json
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/common-document-generation-service-api
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/common-document-generation-service-api/resource/3ab4504d-7647-427a-9f0d-7c1f75b6da90
[Preview] button _disabled_
_Results_: as expected 

**Resource Data Type** = other
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/lidarbc-open-lidar-data-portal
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/lidarbc-open-lidar-data-portal/resource/a21bdeda-a376-45a1-8076-c09b5e70d0d8
[Preview] button _disabled_
_Results_: as expected

**Resource Data Type** = pdf (type = geographic data)
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/census-profiles-for-bc-census-subdivisions-2016-census
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/census-profiles-for-bc-census-subdivisions-2016-census/resource/fd2b538d-b5f9-4e45-8396-5385feae89ff
[Preview] button _enabled_
_Results_: as expected (View in iMapBC button)

**Resource Data Type** = shp
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-drought-levels-time-lapse-2020
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-drought-levels-time-lapse-2020/resource/f4b6fd5d-363d-424c-81fe-61b4acf90593
[Preview] button _enabled_
_Results_: as expected

**Resource Data Type** = txt
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/contraventions-data
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/contraventions-data/resource/dbebfeb0-e545-4b95-9a04-81329b9a091a
[Preview] button _disabled_
_Results_: as expected

**Resource Data Type** = wms
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/terrestrial-protected-areas-representation-by-biogeoclimatic-zone-parc-
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/terrestrial-protected-areas-representation-by-biogeoclimatic-zone-parc-/resource/af59ed04-ccc7-41ba-9064-f42acd9983c4
[Preview] button _enabled_
_Results_: as expected (View in iMapBC button)

**Resource Data Type** = xls
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-finance-budget-2019
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-finance-budget-2019/resource/974e8efe-e786-4079-aab3-ba426a3383a2
[Preview] button _disabled_
_Results_: as expected

**Resource Data Type** = xlsx
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-finance-budget-2019
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-finance-budget-2019/resource/687a51ff-5b62-4f33-b895-f1202759f741
[Preview] button _disabled_
_Results_: as expected


**Resource Data Type** = xml
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-assessment-data-advice
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-assessment-data-advice/resource/90b76f20-89f5-4ef8-9e49-6d18409b89baf42acd9983c4
[Preview] button _enabled_
_Results_: as expected 

**Resource Data Type** = zip
_Dataset_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-assessment-data-advice
_Resource_: https://beta-catalogue.data.gov.bc.ca/dataset/bc-assessment-data-advice/resource/2502029a-9425-463c-8181-776c4c00cb1e
[Preview] button _enabled_
_Results_: as expected

Tested and PASSED
