### ISSUE TITLE
BETA: Keyword search results are not consistent and returning results like the current catalogue

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#509]
Hi Terry,

My team owns the “BC Government Directory Extract” catalogue entry which provides public datasets of the BC Government Directory (https://dir.gov.bc.ca).  

I have some concerns with how the catalogue search behaves on the new beta system.

If you search for “BC Government Directory” on the current production catalogue, our catalogue entry is the top result out of 52 datasets.

If you use that exact same search string “BC Government Directory” on the new beta system, there are 1306 datasets spread over 131 pages of results, and I gave up after the first 5 or 6 pages.  I’m sure it’s in there somewhere, but it may be on page 37 or maybe on page 129.   The point is, it’s highly unlikely anyone would ever find our catalogue entry on the new system using the search string that gives a top result on the old system. I also tried adding quotes around the string in order to try to effect a more exact search, but that yielded zero results.

Oddly, if I make the search more broad by just searching for “Directory” it actually narrows the search and there are only 29 results.  Unfortunately, ours is still on the last page, despite the fact that we are the BC Government Directory.

I was able to narrow it down by selecting our branch name “Access and Directory Management Services (ADMS)” under the Organization filter (this of course resulted in an exact match), but most people in government would not be familiar with our branch name to know to select that, much less the public.

Do we perhaps need to define some additional keywords that can get us higher in the results list?  

Thanks,
Jonathan Borrows 
Senior Application Specialist
Access & Directory Management Services
Information Security Branch, Office of the CIO
Ministry of Citizens' Services
tel: 250.952.6016

------

In order to try to reproduce the issue reported below, I did the following:

1.	Search in Current Catalogue on BC Government Directory Extract (logged in)
a.	Result set is 360 records, Order by Relevance
i.	1st position: https://catalogue.data.gov.bc.ca/dataset/bc-government-directory-extract

![cc_search.jpg](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/57dc80b4-4e42-419b-a2da-760d475a4a48)
 
2.	Search in Current Catalogue on BC Government Directory (logged in)
a.	Results Set is 2710 records, Order by Relevance
i.	1st position: https://catalogue.data.gov.bc.ca/dataset/bc-government-directory-extract
3.	Search in Beta Catalogue on BC Government Directory Extract (logged in) from magnifying glass in upper right hand corner
a.	Result set is 56 records, Order by Relevance
i.	1st position: https://beta-catalogue.data.gov.bc.ca/dataset/bc-government-directory-extract

![beta_magnifying_search.jpg](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/52dd771d-fedb-4d3b-b34b-33e068261b87)
 
I did notice that if I searched from the landing page, the Order By selection is Newest, but get the same record count.  I had to change the Order By selection a few times to get Relevance to show your dataset again in #1 position.  

 ![beta_landing_page_search.jpg](https://images.zenhubusercontent.com/5f7367f8b2d31071e65cd2aa/67f7f721-b660-4403-84e0-0c392e6ffd9e)

4.	Search in Beta Catalogue on BC Government Directory (logged in) from magnifying glass in upper right hand corner
a.	Result set is 30 records, Order by Relevance
i.	1st position: https://beta-catalogue.data.gov.bc.ca/dataset/bc-government-directory-extract

I will respond to the editor thanking him for his feedback and that I will bring it to the team.  Just interesting how searching from the landing page assumes you want the newest and searching from the magnifying glass assumes you want the most relevant.  

Interesting that fewer search words in the current cat netted a larger result set than more search words and few search words in the beta cat netted fewer results than more search words.  I know you have concerns with the search yourself, so I thought I would send you my findings.

**Comment by TerryLanktree** [comment]
Not sure if I have the selection cached.  Please ensure that the search is ordered by relevance.  Let's see if that helps things out.  Open to other suggestions.

**Comment by joe-taylor** [comment]
There appears to have been code written to sort results by newest for blank searches, but the code path for blank searches is being applied to all FIRST searches which originate from the front page. See steps below for more info.

It may constitute a regression for some other ticket, but it is trivial to configure the sort order to default to relevance in all cases. To have the results sorted by newest for blank searches on the other hand will take some thought and engineering, especially around UX, in light of the fact that sort preferences carry over to the next search.

To reproduce the current issue:

1. open an incognito window
2. visit https://beta-catalogue.data.gov.bc.ca
3. perform a search for anything using the search box in the centre of the screen
4. note that the results are ordered by newest and that this order persists for subsequent searches unless manually updated

**Comment by joe-taylor** [comment]
I think the simplest solution is to default sort order to relevance, but if the search is blank and relevance is chosen, actually sort results by newest. Creating a pull request to that end and sending to code review.

**Comment by joe-taylor** [comment]
Thank you for code review, Alan - moving to QA.

**Comment by joe-taylor** [comment]
I introduced a small operator precedence related issue; sending a new pull request to fix.

**Comment by sheilamv** [comment]
Testing STR:

1. open an incognito window
2. visit https://toyger-catalogue.data.gov.bc.ca
3. perform a search for anything using the search box in the centre of the screen (not logged in)
4. Search for Hair

Expected:  Result set displayed and Order By defaults to Relevance
Actual: As Expected

1. Change Order by to Popular
2. Select Hamburger > Data Catalogue Home
3. Search for Wildlife

Expected:  Result set displayed and Order By defaults to Relevance
Actual: As Expected

Logged in with same results as above.  **PASSED**

**Comment by sheilamv** [comment]
Followed the same steps as tested in Toyger, in the Beta environment and the system performed as expected.  PASSED.
