### ISSUE TITLE
Remove "Dataset Usage" from hamburger menu

### ISSUE THREAD

**Issue by joe-taylor** [bcgov/ckan-ui#516]
The Dataset Usage page does not currently work in beta. Per bcgov#377, the hamburger menu item linking to it should therefore be removed.

Here's the menu button. The goal is to remove it.

![image.png](https://images.zenhubusercontent.com/60bf9f233260a1bbb1891368/94c07175-72bb-4269-a827-ea182ecce88d)

If you were to click it, you'd arrive upon the below pictured page, where the spinners spin for quite some time:

![image.png](https://images.zenhubusercontent.com/60bf9f233260a1bbb1891368/74cf229d-06ab-4735-9ece-69955e3ead0b)

Finally, an error occurs. It's best we don't point to this page.

![image](https://user-images.githubusercontent.com/5297264/128100091-eb9ac640-f60c-4c5b-a50b-c34001562fa4.png)

**Comment by sheilamv** [comment]
Tested and Passed - whether logged in or not, the Dataset Usage sub-menu option under the hamburger is not visible. 

@joe-taylor, close or leave here to become part of a PR to beta?

**Comment by sheilamv** [comment]
Not Logged in: **PASSED** - menu option not displayed
![image](https://user-images.githubusercontent.com/65407822/132050192-e812b1d2-f0c0-4e6e-a4db-9d902ec40b44.png)

Logged in :  **PASSED** - menu option not displayed
![image](https://user-images.githubusercontent.com/65407822/132050330-c448d222-9aa2-4bfa-874c-b9b522509e76.png)
