### ISSUE TITLE
MVP - Update Delete popup message interface

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#518]
[Continuation of existing ticket - #448](https://github.com/bcgov/ckan-ui/issues/448)

Popup Message when deleting a Resource should be as follows:

Popup Header: Please Confirm Action
Message: Are you sure you want to delete this resource?
Buttons - [Cancel] [Confirm] (highlight on Confirm button)

- Cancel - closes popup and does not delete the resource
- Confrim - closes popup and deletes the resource

Popup Message when deleting a Record (aka Dataset or Metadata) should be as follows:
Popup Header: Please Confirm Action
Message: Are you sure you want to delete this record and all its resources?
Buttons - [Cancel] [Confirm] (highlight on Confirm button)

- Cancel - closes popup and does not delete the record or any associated resources
- Confrim - closes popup and deletes the record and all associated resources

**Comment by joe-taylor** [comment]
Replaced the browser native confirmation dialog with a UI-layer modal, as shown. Mainly kept to the stock options as provided by vuetify.

![image](https://user-images.githubusercontent.com/5297264/132926501-8a66094d-5629-4a2b-8933-99e8b46df678.png)

**Comment by sheilamv** [comment]
Testing deleting a Resource: **PASSED**
![image](https://user-images.githubusercontent.com/65407822/133690752-35f99e71-a7d0-4d87-9a68-9cc75bd99992.png)

Testing deleting a Record: PASSED
![image](https://user-images.githubusercontent.com/65407822/133690965-9620182e-ee3d-478f-a819-1c655fed316c.png)

**Comment by sheilamv** [comment]
Testing deleting a Resource in Beta: PASSED (as above)
Testing deleting a Record in Beta: PASSED (as above)
