### ISSUE TITLE
Delete functionality on Record (aka Dataset/Metadata) and associated Resources

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#519]
[Continuation of existing ticket - #448](https://github.com/bcgov/ckan-ui/issues/448)

There is to be a delete link visible and enabled for each type of user (SysAdmin, Admin, Editor, Logged in with no role, Public) on a record.

**SysAdmins** - have access to all Organization records
**Admins** - have access to all records associated to the Organization to which they have been assigned in Keycloak
**Editor** - has access to all records associated to the Organization to which they have been assigned in Keycloak, but not necessarily the ability to delete records/resources in every status
_Member_ - can view all records, regardless of state, associated to the Organization to which they have been assigned in Keycloak (has not been fully defined yet)

**_Logged in users with no roles_** see more records due to the nature of identifying themselves, but they can't manage any of the records.
**_Public users_** see only published and pending archived records, regardless of the Organization assignment, but they can't manage any of the records. 

**Able to delete** means the Delete link and icon are visible and enabled.
**Unable to delete** means the Delete link and icon are visible but disabled.
**Unable to view record** means the record is not visible or searchable. 

No change to the definitions of who can view the record (or data) or download the data.  This requirement is all about the visiblity of the Delete link and icon on the resource and record.  

Role | Record Type | Status | Expected | Actual 
-----|-----|-----|-----|----
SysAdmin | Resource | Record = Draft | Able to delete | As expected |
SysAdmin | Resource | Record = Pending Publish | Able to delete | As expected |
SysAdmin | Resource | Record = Published | Able to delete | As expected |
SysAdmin | Resource | Record = Pending Archive | Able to delete | As expected|
SysAdmin | Resource | Record = Archived | Able to delete | As expected |
SysAdmin | Record | Draft | Able to delete | As expected|
SysAdmin | Record | Pending Publish | Able to delete | As expected |
SysAdmin | Record | Published | Able to delete | As expected |
SysAdmin | Record | Pending Archive | Able to delete | As expected|
SysAdmin | Record | Archived | Able to delete | As expected |
| | | | |
Admin | Resource | Record = Draft | Able to delete | As expected |
Admin | Resource | Record = Pending Publish | Able to delete | As expected |
Admin | Resource | Record = Published | Able to delete | As expected  |
Admin | Resource | Record = Pending Archive | Able to delete | As expected |
Admin | Resource | Record = Archived | Unable to delete| As expected |
Admin | Record | Draft | Able to delete | As expected |
Admin | Record | Pending Publish | Unable to delete | As expected |
Admin | Record | Published | Unable to delete | As expected |
Admin | Record | Pending Archive | Unable to delete| As expected |
Admin | Record | Archived | Unable to delete | As expected  |
| | | | |
Editor | Resource | Record = Draft | Able to delete | As expected |
Editor | Resource | Record = Pending Publish | Able to delete | As expected|
Editor | Resource | Record = Published | Able to delete | As expected |
Editor  | Resource | Record = Pending Archive | Able to delete | As expected |
Editor | Resource | Record = Archived | Unable to delete| As expected |
Editor | Record | Draft | Able to delete | As expected |
Editor | Record | Pending Publish | Unable to delete | As expected |
Editor | Record | Published | Unable to delete | As expected |
Editor | Record | Pending Archive | Unable to delete | As expected |
Editor | Record | Archived | Unable to delete | As expected |
| | | | |
Logged in with no Role | Resource | Record = Draft | Unable to view record | As expected |
Logged in with no Role | Resource | Record = Pending Publish | Unable to view record| As expected |
Logged in with no Role | Resource | Record = Published | Unable to delete | Delete not available on resource card or resource |
Logged in with no Role | Resource | Record = Pending Archive | Unable to delete | Delete not available on resource card or resource |
Logged in with no Role | Resource | Record = Archived | Unable to view record | As expected |
Logged in with no Role | Record | Draft | Unable to view record | As expectced |
Logged in with no Role | Record | Pending Publish | Unable to view record | As expected |
Logged in with no Role | Record | Published | Unable to delete | Delete not available on record |
Logged in with no Role | Record | Pending Archive | Unable to delete | Delete not available on record |
Logged in with no Role | Record | Archived | Unable to view record | As expected |
| | | | |
Public | Resource | Record = Draft | Unable to view record | As expected |
Public | Resource | Record = Pending Publish | Unable to view record| As expected |
Public | Resource | Record = Published | Unable to delete | Delete not available on resource card or resource |
Public | Resource | Record = Pending Archive | Unable to delete | Delete not available on resource card or resource |
Public | Resource | Record = Archived | Unable to view record | As exptected |
Public | Record | Draft | Unable to view record | As expected |
Public | Record | Pending Publish | Unable to view record | As expected|
Public | Record | Published | Unable to delete | Delete not available record |
Public | Record | Pending Archive | Unable to delete | Delete not available on record|
Public | Record | Archived | Unable to view record | As expected |

**Comment by sheilamv** [comment]
@annikaLiving, can you please read the above requirement about when to allow the Delete ability to be visible and enabled based on user type and the status of the record.  I have defined Member, but not implemented their record access in the requirement as I know you have some thoughts about the true definition of the Keycload role. There is a TBD in the SysAdmin section on the resource, so please have a look and updated as required.

**Comment by joe-taylor** [comment]
It appears that the TBD has been filled in and the requirements are clear from my perspective. Proceeding using the table as stated as the guide.

**Comment by joe-taylor** [comment]
I updated the delete button's visibility logic and added unit tests for same.

> No change to the definitions of who can view the record (or data) or download the data. This requirement is all about the visiblity of the Delete link and icon on the resource and record.

As per the preceding, this ticket's scope is limited to the visibility of the delete link in the UI. API work still outstanding, and will be addressed in the issue referenced below.

 - #500

**Comment by sheilamv** [comment]
Testing in Toyger - Public (not logged in)

- As expected, based on above - PASSES.

**Comment by sheilamv** [comment]
**Public Consumer** - not logged in
- As expected (PASSED)

**Government Consumer** - logged in 
- As expected (PASSED)

**Comment by sheilamv** [comment]
All test cases passed in Beta.
