### ISSUE TITLE
MVP - Update to About Page Text

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#534]
Discussion to change the way the About box is presented.
Content needs to be created and decision on where this data will be stored.

**Comment by joe-taylor** [comment]
For a quick win, I propose using a stylesheet to improve the spacing and font sizes (e.g. for links in headings). I'm sure it could be improved further, and some things will come down to personal taste, but the below is somewhere to start.

<table>
<thead>
<tr>
<th>Before</th><th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/5297264/131207629-6a3d7178-4807-4b64-814f-fe7282fd1dab.png">
</td><td>
<img src="https://user-images.githubusercontent.com/5297264/131207680-71a3cd44-8e46-4a8b-9a72-91c4b19be886.png">
</td>
</tr>
</tbody>
</table>

**Comment by alixcote** [comment]
We are updating the content only for now.

**Comment by sheilamv** [comment]
Production > About: 
![image](https://user-images.githubusercontent.com/65407822/135938649-01f6f2b7-4587-4cba-b1ef-671178181920.png)


Beta > About:
![image](https://user-images.githubusercontent.com/65407822/135938847-267a498e-a947-4a55-a175-a181fb83ad7d.png)

![image](https://user-images.githubusercontent.com/65407822/135938729-7bb4e15e-af4c-4190-9a69-b5f8c26703a0.png)

Toyger > About: 
![image](https://user-images.githubusercontent.com/65407822/135938855-85e65d4e-e07e-4dae-94ab-dd20323e2d04.png)

**Comment by sheilamv** [comment]
Tested in Beta - PASSED
![image](https://user-images.githubusercontent.com/65407822/136256087-2dbb5228-c1e6-43a2-9a0b-495fbde12f7e.png)
