### ISSUE TITLE
MVP - Add a new menu option Documenation under the hamburger

### ISSUE THREAD

**Issue by sheilamv** [bcgov/ckan-ui#535]
Requirement:  Add a new menu option called Documentation between Geographic Services and About.  See links below in a comment from Alix.

**Comment by sheilamv** [comment]
@joe-taylor , are you looking for more of a requirement. I will work with @annikaLiving and Alix to flush that our for you.

**Comment by joe-taylor** [comment]
@sheilamv Thank you, yes that's exactly it. Just the link text(s) and URL(s).

**Comment by alixcote** [comment]
@sheilamv @joe-taylor 

There will be 1 new menu item called "Documentation" and will link to: https://www2.gov.bc.ca/gov/content/data/bc-data-catalogue

Permalink: https://www2.gov.bc.ca/gov/content?id=42230A1DCE4B442A8D72B7B11A53DA5F

Sheila and I were thinking between geographic services and about. Thoughts?

Note: This page will be updated on cutover, but this will be the "Live" url.

**Comment by joe-taylor** [comment]
@alixcote Thank you. I concur on placement. I'll proceed with that and we can change it later need be.

**Comment by sheilamv** [comment]
STR:
1. select hamburger and find Documentation between Geographic  - pass
2. select Documentation
Expected:  Takes the user to https://www2.gov.bc.ca/gov/content/data/bc-data-catalogue
Actual:  as expected

PASSED

**Comment by sheilamv** [comment]
STR (Beta):

1. select hamburger and find Documentation between Geographic - pass
1. select Documentation
Expected: Takes the user to https://www2.gov.bc.ca/gov/content/data/bc-data-catalogue
Actual: as expected
PASSED
