### ISSUE TITLE
Splash View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#54]

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

### Header - Desktop
- The height should be 65 pixels.
- The yellow area should be #FCBA19.
- Should use the proper BC Mark (with embedded protective area), the height of it should be 65 pixels. (See https://www2.gov.bc.ca/gov/content/governments/services-for-government/policies-procedures/bc-visual-identity/design-guidelines#using-the-bc-mark)
- “DATA CATALOGUE” should be “Data Catalogue”, BC Sans - bold - 36px.
- “LOG IN” should be “Log in”, BC Sans - Regular - 16px.
- “LOG OUT” Should be “Log out” and hidden in the menu to leave space for “Add Dataset”.
- “FRANÇAIS” should be “Français”, BC Sans - Regular - 16px.
- “Menu” below the hamburger icon is missing, background color should be #38598A.
- Lower the breakpoint to 720px.

### Header Menu Flyout - Desktop
- The width should be 320 pixels.
- The border-radius should be 0.
- Font should be BC Sans - Regular - 16px.
- The light blue area should be #38598A.
- The yellow area should be #FCBA19.
- “Subscribe to new data” should be “Subscribe to New Data”.
- “Dataset Usage” is missing.

### Header Search Flyout - Desktop
- The height should be 60 pixels.
- The Search icon is missing.
- Remove the grey line below “Search Data Catalogue”.
- “Search Data Catalogue” should be BC Sans - Regular - 28px - #494949.
- The active state of the “Search Data Catalogue” input field should simply display a cursor with placeholder text as “Search Data Catalogue”, Regular - 28px - #888888. (See https://www2.gov.bc.ca/)

### Footer - Desktop
- Font should be BC Sans - Regular - 16px.
- Use Title Case instead of UPPER CASE.

### Splash View - Desktop
- The width and height for the pitch card should be 160 pixels and 180 pixels.
- The border-radius for the pitch card should be 5 pixels.
- The box-shadow for the pitch card should be 0 5px 5px rgba(0, 0, 0, 20%).
- The margin for the pitch card should be 50px 20px.
- The border-radius for the “Search Data Catalogue” input field should be 2 pixels.
- The border for the “Search Data Catalogue” input field should be 2px solid #003366.
- “Search Data Catalogue” should be BC Sans - Regular - 16px - #888888.
- “Try Searching for …” should be BC Sans - Regular - 23px - #494949.
- The margin between “Try Searching for” and the key words should be 0.
- The Search icon should be #888888.

**Comment by SteveChapmanBCDX** [comment]
Assigning to @jachurchill  for implementation.

**Comment by yuisotozaki** [comment]
![AdobeStock_291596098_Preview](https://user-images.githubusercontent.com/56084999/78605471-6f47ae80-7810-11ea-947b-33186621a6c8.jpeg)
Placeholder image for the background.

**Comment by yuisotozaki** [comment]
![BCID_H_rgb_rev](https://user-images.githubusercontent.com/56084999/78717775-00cd2400-78d6-11ea-91d0-1ba7d6d45c2e.png)
BC Mark for header use.

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Header - Desktop
- Should use the proper BC Mark (with embedded protective area), the height of it should be 65 pixels. (See attached image on #54)
- “LOG OUT” Should be “Log out” and hidden in the menu to leave space for “Add Dataset”.
- “Menu” below the hamburger icon is missing, background color should be #38598A.
- Lower the breakpoint to 720px.

### Header Menu Flyout - Desktop
- “Dataset Usage” is missing.
- “Log out” icon should be #FFFFFF.
- The menu flyout isn’t positioned responsively on smaller screens.

### Header Search Flyout - Desktop
- “Search Data Catalogue” should be BC Sans - Regular - 28px - #494949.
- The Search icon should be clickable and function as it indicates.

### Footer

- Font should be BC Sans - Regular - 16px.
- The yellow area should be var(--v-govYellow-base) #FCBA19.
- The left and right edges of the content flow should always align with what’s in Header across different sizes of browser window.

### Splash View - Desktop

- The box-shadow for the pitch card should be 0 5px 5px rgba(0, 0, 0, 20%).
- “Search Data Catalogue” should be BC Sans - Regular - 16px - #888888.
- The Search icon should be #888888.
- Pitch deck designs should be implemented.
- Remove the extra white space on the right side of the viewport (same for Header and Footer).
- The Search icon should be clickable and function as it indicates.
- “Try Searching for ...” and “Crown” should be #FFFFFF when the background image is implemented.
- Background image should be something like this: style="background-image: url(https://as1.ftcdn.net/jpg/02/91/59/60/500_F_291596098_6nXL0nza5UgVMniyp8e92v1JKyANtgbq.jpg); no-repeat; background-size: 100%; background-color:rgba(0,0,0,0.15); background-blend-mode:overlay;"

**Comment by SteveChapmanBCDX** [comment]
Issue implemented - closing ticket.
