### ISSUE TITLE
Prompt for username/password when logging in after having logged out

### ISSUE THREAD

**Issue by joe-taylor** [bcgov/ckan-ui#542]
Logging out should require you to re-authenticate if you want to log back in.

Currently, this happens:

1. Log in to beta-catalogue
2. Enter credentials
3. You're now logged in
4. Click log out
5. You're logged out of the UI
6. Click log in
7. You're now logged in

I propose we introduce the step highlighted below.

1. Log in to beta-catalogue
2. Enter credentials
3. You're now logged in
4. Click log out
5. You're logged out of the UI
6. Click log in
7. **Enter credentials**
8. You're now logged in

Keywords: login logout keycloak siteminder openid

**Comment by joe-taylor** [comment]
A small code change together with an update to configuration should fix this, so I would classify this as a quick win.

**Comment by joe-taylor** [comment]
The configuration change is to add an oidc.logout endpoint such that clicking logout redirects to URLs like this after logging out locally: https://test.oidc.gov.bc.ca/auth/realms/m6kqkznl/protocol/openid-connect/logout?client_id=toyger&redirect_uri=https://toyger.data.gov.bc.ca

**Comment by joe-taylor** [comment]
Configuring dev, test, and prod with aforementioned oidc logout parameter.

**Comment by joe-taylor** [comment]
PR ready to go; also added the below to our deployment configs (with realm and keycloak instance varying by environment):

```
oidc:
  logout: https://test.oidc.gov.bc.ca/auth/realms/m6kqkznl/protocol/openid-connect/logout```

**Comment by joe-taylor** [comment]
This does not appear to be working in dwelf. I wonder if some of the config failed to go through, but back to the drawing board for now.

**Comment by joe-taylor** [comment]
I'll have to update [the helm chart](https://github.com/bcgov/helm-charts) to have the logout config propagate.

**Comment by joe-taylor** [comment]
In code review pending merge of https://github.com/bcgov/helm-charts/pull/17

**Comment by sheilamv** [comment]
STR:
1. logged in as sysAdmin
2. Logged out
![image](https://user-images.githubusercontent.com/65407822/133691416-e0812326-c9d2-4b45-b4c0-7080011159b9.png)
3. Selected Log In
Expected: To enter credentials again
Actual: as expected

**PASSED**

**Comment by sheilamv** [comment]
Closed accidentally - mean to just move to Ready for Beta.

**Comment by sheilamv** [comment]
STR:

1. logged in as sysAdmin
1. Logged out
![image](https://user-images.githubusercontent.com/65407822/134397606-6c3c0b90-42dc-409c-b314-b754d5a68f6c.png)

1. Selected Log In

Expected: To enter credentials again
Actual: as expected
**PASSED**
