### ISSUE TITLE
Beta SOLR - Ensure some other critical fields are searchable

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#586]
Like `object_name` and `bcdc_type`, it was determined that `resource_storage_location` also needs to be available for the pyETS script.

For example:

https://cat.data.gov.bc.ca/api/3/action/resource_search?query=resource_storage_location:%22bc+geographic+warehouse%22

https://cat.data.gov.bc.ca/api/3/action/package_search?q=res_extras_resource_storage_location:%22bc+geographic+warehouse%22

**Comment by joe-taylor** [comment]
I recommend avoiding resource_search for extra fields as it's slow and likely to behave unexpectedly besides. I would prefer package_search.

1. resource_search searches for literal substrings, not keywords
2. When searching by `key:value`, it does not guarantee that the matched value is associated to the key!

From [CKAN's docs](https://docs.ckan.org/en/2.9/api/#ckan.logic.action.get.resource_search):

> Note: Due to a Resource’s extra fields being stored as a json blob, the match is made against the json string representation. As such, false positives may occur:
>
> If the search criteria is:
> 
> ```ini
> query = "field1:term1"
> ```
>
> Then a json blob with the string representation of:
> 
> ```json
> {"field1": "foo", "field2": "term1"}
> ```
> 
> will match the search criteria! This is a known short-coming of this approach.

**Comment by joe-taylor** [comment]
> Rather than bc+geographic+warehouse, why not search for "bc%20geographic%20warehouse"?

@mdunhamwilkie The server decodes both parameters as "bc geographic warehouse" (with spaces) so it comes down to personal preference as to how you want to escape your search parameters. They both return the same results, but one is less characters and more easily read, while the other is less likely to be confused with literal plus characters (which would be %2B in a URL) and more conventional.
