### ISSUE TITLE
MVP - Filter Search Results Group Facet should not display Private Groups when not logged in

### ISSUE THREAD

**Issue by ghost** [bcgov/ckan-ui#589]
Nik provided feedback:

As to the following item:

- We also manage the BEIF group – and are wondering if there are options on how this group is displayed under “Filter Search Results”? [SMV] https://github.com/bcgov/ckan-ui/issues/447 has been entered to remove private groups from the Groups List under Filter Search Results when not logged in.  It is in the backlog to be prioritized post launch.  Let me know if you feel this needs a higher priority than it currently has.  

- We would prefer if this could be moved up the backlog as possible, as the BEIF program is intended to be internal to government.

Private Flag on a Group currently means that this group is hidden from the Public (not logged into the Catalogue with an IDIR).  When viewing Groups (Hamburger > Explore Dataset Groups) and not logged in, groups with the Private flag checked are not visible.  

**Requirement**: When not logged in and viewing the list of datasets ([Hamburger > Explore Datasets](https://beta-catalogue.data.gov.bc.ca/datasets)), groups with the Private flag checked must not be available for selection under Group. 

@TerryLanktree and I have discussed this and it should be handled outside of #447.

**Comment by sheilamv** [comment]
Not sure if this is the correct [ticket ](https://github.com/bcgov/ckan-ui/pull/479) which was used to fix the list of groups displayed on [Groups ](https://beta-catalogue.data.gov.bc.ca/groups) page to not include private groups when viewing the page while not logged in.
