### ISSUE TITLE
UI/UX View => Filters

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#6]
Filters as required to replace the existing filters.

**Comment by JordanReed** [comment]
![Filters - Sectors Tab - Web 1920 x2](https://user-images.githubusercontent.com/3344888/57038311-7cc2e480-6c0e-11e9-92d6-f28b68b79dd8.png)
![Filters - Permissions Tab - Web 1920 x2](https://user-images.githubusercontent.com/3344888/57038344-8cdac400-6c0e-11e9-8712-71935e261ace.png)
![Filters - Data Type Tab Open - Web 1920 x2](https://user-images.githubusercontent.com/3344888/57038350-92d0a500-6c0e-11e9-9dca-307839593f62.png)
![Filters - Org Tab - Web 1920 x2](https://user-images.githubusercontent.com/3344888/57038358-96fcc280-6c0e-11e9-96e6-2a3f02c4a200.png)

**Comment by SteveChapmanBCDX** [comment]
Reviewed with team, closing issue.
