### ISSUE TITLE
Groups View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#60]

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

### Overall
- Font should be BC Sans.
- Background color should be #F2F2F2.
- The left and right edges of the content flow should align with what’s in Header and Footer.
- Should increase the distance between the left section and the right section so that they are visually more separated from each other.
- The distance between Header and the content flow should be 50 pixels.
- The distance between the content flow and Footer should be 50 pixels.
- The position of the right section should be fixed instead of static.
- “Manage” and “Add Group” in the “Groups View Admin View - Desktop” are missing.

### Left Section - “Groups”
- BC Sans - Bold - 23px - #1A5A96.

### Left Section - Search Bar
- Currently missing.
- Background color should be #FFFFFF.
- Border should be 2px solid #003366.
- Border-radius should be 3px.
- The Search icon should be #CCCCCC.
- Box-shadow should be none.

### Left Section - Group Count
- Currently missing.
- BC Sans - Regular - 16px - #494949.

### Left Section - Group Card
- Height 120 pixels.
- Background color should be #FFFFFF.
- Box-shadow should be 0 5px 5px rgba(0, 0, 0, 20%).
- Border-radius should be 0.
- Group name BC Sans - Bold - 23px - #494949.
- Group dataset count BC Sans - Bold - 16px - #494949.
- Group name and dataset count text should be vertically centred on the card as a group.
- {arrow-right} #1A5A96.

### Right Section - Manage
- Height 40 pixels.
- BC Sans - Bold - 16px - #FFFFFF.
- Background color should be #38598A.
- Box-shadow should be none.
- Border-radius should be 0.

### Right Section - Add Group
- Height 50 pixels.
- BC Sans - Bold - 16px - #FFFFFF.
- Text should be centered.
- Background color should be #003366.
- Box-shadow should be none.
- Border-radius should be 4px.

### Right Section - Groups Title
- Height 40 pixels.
- BC Sans - Bold - 16px - #FFFFFF.
- Background color should be #38598A.
- Box-shadow should be none.
- Border-radius should be 0.

### Right Section - Groups Card
- BC Sans - Bold - 16px - #494949.
- Background color should be #FFFFFF.
- Box-shadow should be 0 5px 5px rgba(0, 0, 0, 20%).
- Border-radius should be 0.

**Comment by BrandonSharratt** [comment]
Overall
_Font should be BC Sans._
Done as part of a different ticket

_Background color should be #F2F2F2._
Done

_The left and right edges of the content flow should align with what’s in Header and Footer._
Done

_Should increase the distance between the left section and the right section so that they are visually more separated from each other._
Done

_The distance between Header and the content flow should be 50 pixels.
The distance between the content flow and Footer should be 50 pixels._
Added py-4

_The position of the right section should be fixed instead of static._
Done

_“Manage” and “Add Group” in the “Groups View Admin View - Desktop” are missing._
They were waiting for me to add the individual group view

**Comment by BrandonSharratt** [comment]
Left Section - “Groups”
_BC Sans - Bold - 23px - #1A5A96._
Done

**Comment by BrandonSharratt** [comment]
Left Section - Search Bar
_Currently missing._
You asked for this to be hidden until there were more groups

_Background color should be #FFFFFF.
Border should be 2px solid #003366.
Border-radius should be 3px.
The Search icon should be #CCCCCC.
Box-shadow should be none._
Copied from other page, still hidden

**Comment by BrandonSharratt** [comment]
Left Section - Group Count
_Currently missing._
Not missing is hidden because you asked for this to be hidden until there were more groups

_BC Sans - Regular - 16px - #494949._
Done

**Comment by BrandonSharratt** [comment]
Left Section - Group Card
_Height 120 pixels._
Done

_Background color should be #FFFFFF._
Done

_Box-shadow should be 0 5px 5px rgba(0, 0, 0, 20%)._
Done

_Border-radius should be 0._
Done

_Group name BC Sans - Bold - 23px - #494949._
Done

Group dataset count BC Sans - Bold - 16px - #494949.
Done

Group name and dataset count text should be vertically centred on the card as a group.
{arrow-right} #1A5A96.
Done

**Comment by BrandonSharratt** [comment]
Right Section - Manage
_Height 40 pixels._
Done

_BC Sans - Bold - 16px - #FFFFFF._
Done

_Background color should be #38598A._
Done

_Box-shadow should be none._
Done

_Border-radius should be 0._
Done

**Comment by BrandonSharratt** [comment]
Right Section - Groups Title
_Height 40 pixels._
Done

_BC Sans - Bold - 16px - #FFFFFF._
Done

_Background color should be #38598A._
Done

_Box-shadow should be none._
Done

_Border-radius should be 0._
Done

Right Section - Groups Card
_BC Sans - Bold - 16px - #494949._
Done

_Background color should be #FFFFFF._
Done

_Box-shadow should be 0 5px 5px rgba(0, 0, 0, 20%)._
Done

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Overall
- The left and right edges of the content flow should VISUALLY (reduce extra padding or margin? Please see the Organizations View (#58) review notes for reference) align with what’s in Header and Footer.
- The distance between Header and the content flow and the distance between the content flow and Footer should be the same and consistent with what’s in the Organizations View (#58).
- The visual look and feel should maintain a general consistency between the Groups View and Organizations View, thus things such as font weight, font color, section width, section position (especially horizontal), bar color, bar height, etc. for the corresponding components should be the same. We still try to provide notes for refinement point by point below, but the above is the rationale behind.

### Left Section - “Groups”

### Left Section - Search Bar
- Should be hidden as it is until there are more groups, but maintain consistency with what’s in the Organizations View (#58), notes for refinement are there.

### Left Section - Group Count

### Left Section - Group Card
- Box-shadow should be 0 5px 5px rgba(0, 0, 0, 20%).
- Group dataset count BC Sans - Regular - 16px - #494949.
- {mdi-arrow-right} #1A5A96.
- Increase the distance between the left edge and the group image. Group images should have 20px space around them and resized accordingly.
- Increase the distance between the arrow and the right edge. Arrow icons should have 20px space around them.
- Vertical space between the Group Cards should be 10px.

### Right Section - Manage
- BC Sans - Bold - 16px - #FFFFFF.
- Text should be vertically centered.

### Right Section - Add Group
- Height 50 pixels.
- Vertical space between Add Group and Groups should be 50px.

### Right Section - Groups Title

- BC Sans - Bold - 16px - #FFFFFF.
- Border-radius should be 0.

### Right Section - Groups Card
- Should be in it’s own card, please refer to the mockups.
- BC Sans - Regular - 16px - #494949.
- Box-shadow should be 0 5px 5px rgba(0, 0, 0, 20%).
- Border-radius should be 0.

**Comment by SteveChapmanBCDX** [comment]
View implemented - closing ticket.
