### ISSUE TITLE
Expose resource.last_modified in the UI (DDS-944)

### ISSUE THREAD

**Issue by annikaLiving** [bcgov/ckan-ui#604]
`resource_update_date` is available via the api but not exposed via the UI. This is a heavily used field.

However this field is only really valid if it is in the BCGW or BCDC file/data store. therefore could be conditional on resource_storage_location

    {
      "field_name": "last_modified",
      "form_snippet": null,
      "label": "Resource Last Refreshed/Updated",
      "help_text": "Date the data was last refreshed in the BCGW or BC Data Catalogue.",
      "conditional_field": "resource_storage_location",
      "conditional_values": ["bc geographic warehouse","catalogue data store"],
    },

https://github.com/ckan/ckanext-scheming

What do each of these do?

`"validators": "conditional_required"`

* thinking maybe it can be removed as it is not always on those that have conditional fields
* seems to be when new field shows up when one is selected but not just to make it visible or not.
* i think it is not needed.
 
` "form_snippet": "markdown.html",`

* editing - nope

`"form_snippet": null,`

* if null than won't be displayed in view
* YES!

` "display_snippet": "markdown.html",`
* nope as this make it show up like other large text boxes

**Comment by annikaLiving** [comment]
@BrandonSharratt @adodge-bcg, clients are asking for this field to be made visible for the UI but your comment brandon about adding too many conditions could cause issues. thus would like your review if you would think it okay to implement something like this?

**Comment by adodge-bcg** [comment]
I would have to defer to brandon as the expert, but I dont see anything glaringly wrong with this. Though I am not sure on the conditional how to configure it to be `and` or `or`. The intent is that it should be conditional on `resource_storage_location` being `bc geographic warehouse` or `bc data catalogue`, correct?

**Comment by alixcote** [comment]
Hey @BrandonSharratt - wondering if you might have a few minutes to provide some feedback to Alan and Annika? Thanks!

**Comment by sheilamv** [comment]
https://dpdd.atlassian.net/browse/DDS-944

**Comment by annikaLiving** [comment]
Dates are now visible in the UI. This field is visible only when applicable... BCGW or Data Store. Opportunities in the future to expand if clients request.
