### ISSUE TITLE
Group View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#61]

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt 

### Overall
- Font should be BC Sans.
- Background color should be #F2F2F2.
- The left and right edges of the content flow should align with what’s in Header and Footer.
- Should increase the distance between the left section and the right section so that they are visually more separated from each other (while maintaining the consistency with other views).
- The distance between Header and the content flow should be 50 pixels.
- The distance between the content flow and Footer should be 50 pixels.
- The position of the right section should be fixed instead of static.

### Dataset List, Pagination, Filters
- Keep consistent with what’s in the Datasets View (need to be refined based on review notes there).

### Search Bar, Dataset Count
- Keep consistent with what’s in the Datasets View (need to be refined based on review notes there).
- “Search Datasets in this group” should be “Search for datasets in this group”. 

### Left Section
- “{arrow-left} Back to groups list” should be “{arrow-left} Back to Groups List”, BC Sans - Regular - 16px - #1A5A96, and takes up the same vertical space as “{arrow-left} Back to Results (171)” on the Dataset View, remove containing rectangle.
- Breadcrumb should be BC Sans - Bold - 23px - #1A5A96 for links & #494949 for “/”.

### Right Section
- “LEARN MORE ABOUT THIS GROUP” should be “Learn more about this group”, BC Sans - Regular - 16px - #1A5A96.
- “{content-copy} COPY PERMALINK” should be “{content-copy} Copy Permalink”, BC Sans - Regular - 16px - #1A5A96, no extra space on the left.
- “{minus-circle-outline} Unfollow Group”/“{plus-circle-outline} follow Group” are missing, BC Sans - Regular - 16px - #1A5A96, no extra space on the left.
- “{pencil-outline} Edit Group” should be BC Sans - Bold - 16px - #1A5A96.
- “{delete-outline} Delete Group” should be BC Sans - Bold - 16px - #D8292F.

**Comment by BrandonSharratt** [comment]
Overall
_Font should be BC Sans._
Done as part of datasets view

_Background color should be #F2F2F2._
Done

_The left and right edges of the content flow should align with what’s in Header and Footer._
Done

_Should increase the distance between the left section and the right section so that they are visually more separated from each other (while maintaining the consistency with other views)._
Done

_The distance between Header and the content flow should be 50 pixels.
The distance between the content flow and Footer should be 50 pixels._
Added py-4

_The position of the right section should be fixed instead of static._
As with other things the facet filters don't work when fixed;

_Dataset List, Pagination, Filters
Keep consistent with what’s in the Datasets View (need to be refined based on review notes there).
Search Bar, Dataset Count_
These are all reusable components so they already are.

**Comment by BrandonSharratt** [comment]
Left Section
_“{arrow-left} Back to groups list” should be “{arrow-left} Back to Groups List”, BC Sans - Regular - 16px - #1A5A96, and takes up the same vertical space as “{arrow-left} Back to Results (171)” on the Dataset View, remove containing rectangle._
I don't see back to results on the dataset view, and it doesn't have a containing rectangle, the rest is done

_Breadcrumb should be BC Sans - Bold - 23px - #1A5A96 for links & #494949 for “/”._
Done as part of other ticket

**Comment by BrandonSharratt** [comment]
Right Section
_“LEARN MORE ABOUT THIS GROUP” should be “Learn more about this group”, BC Sans - Regular - 16px - #1A5A96._
Done

_“{content-copy} COPY PERMALINK” should be “{content-copy} Copy Permalink”, BC Sans - Regular - 16px - #1A5A96, no extra space on the left._
Done

_“{minus-circle-outline} Unfollow Group”/“{plus-circle-outline} follow Group” are missing, BC Sans - Regular - 16px - #1A5A96, no extra space on the left._
These require log in, the styling has been applied

_“{pencil-outline} Edit Group” should be BC Sans - Bold - 16px - #1A5A96._
Done

_“{delete-outline} Delete Group” should be BC Sans - Bold - 16px - #D8292F._
Done

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Mockup with Guides
![image](https://user-images.githubusercontent.com/58751681/79509010-8c8a3300-7fef-11ea-810b-bfe81d44493c.png)

### Current State in Toyger
![image](https://user-images.githubusercontent.com/58751681/79509039-9a3fb880-7fef-11ea-9baf-8596a9ce7afe.png)

### Overall
- The left and right edges of the content flow should visually align (please see illustrations above) with what’s in Header and Footer.
- The position of the right section should be fixed instead of static (scrollable separately from the left section when expanded if achievable). We want the user to have access to the filter wherever the user is vertically on the datasets list.

### Edit Mode
- Image URL field placeholder should be in regular font weight.
- Image URL field label and the placeholder that becomes label (as per material design spec) is clashing, so can we make it so that the placeholder doesn’t turn into the label?

### Dataset List, Pagination, Filters
- Keep consistent with what’s in the Datasets View (need to be refined based on review notes there).

### Search Bar, Dataset Count
- Keep consistent with what’s in the Datasets View (need to be refined based on review notes there).
- “Search Datasets in this group” should be “Search for datasets in this group”.

### Left Section
- “{arrow-left} Back to Groups list” should be “{arrow-left} Back to Groups List”, #1A5A96 (for both icon and text), and takes up the same vertical space as “{arrow-left} Back to Results (171)” on the Dataset View (please refer to the mockups if unsure).
- Breadcrumb should have #494949 for “/” and no underline for links.

### Right Section
- “{pencil-outline} Edit Group” should use the outline icon.
- “{delete-outline} Delete Group” should use the outline icon.
- Add a little space between the icons and the button labels (Copy Permalink, Follow/Unfollow Group, Edit Group, Delete Group).

**Comment by SteveChapmanBCDX** [comment]
View implemented - closing ticket.
