### ISSUE TITLE
Invitation Script - UI/UX Improvements Plan

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#62]

**Comment by nanyangpro** [comment]
Hi {First Name},
 
As part of our continuous improvement effort, we are excited to notify you that updates on the BC Data Catalogue website are in progress. These changes give us the opportunity to enhance the user experience and continue to deliver value to our clients like you. We’ve modernized the UI while preserving the same functionality and workflow for our users as our first pass and **you are invited to experience the new user interface and provide insights into its look and feel as well as usability!**

We look forward to working with you either in person or remotely based on your availability to collect your input in an user task session that take no more than an hour to complete. Your contribution by participating is highly appreciated and would help a lot in BCDC future improvements to benefit all users.

Warm regards,
BC Data Catalogue

**Comment by SteveChapmanBCDX** [comment]
@nanyangpro - We will use this script as the basis for the email to both "consumers" and "editors".  Good work - closing the issue.
