### ISSUE TITLE
Splash View - Content for Three Placeholder Views: Implementation

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#63]
Implement for splash view:
* Three Placeholder Views
* Background photo

**Comment by yuisotozaki** [comment]
![AdobeStock_291596098_Preview](https://user-images.githubusercontent.com/56084999/77930198-70506d00-725f-11ea-8ff8-63e6a80cd7e0.jpeg)
Attaching a preview of the background image from Adobe Stock (#291596098).
