### ISSUE TITLE
Update About page to link to JSM

### ISSUE THREAD

**Issue by alixcote** [bcgov/ckan-ui#707]
Update the “About” modal with the following text:

From: 
If you have general questions about the catalogue, please send us an email at [data@gov.bc.ca](mailto:data@gov.bc.ca).

To: 
If you have general questions about the catalogue or wish to provide feedback, please open a ticket with the [Data Systems & Services request system](https://dpdd.atlassian.net/servicedesk/customer/portal/1).

**Comment by annikaLiving** [comment]
Work has been completed
