### ISSUE TITLE
Test Reference Script (for Test Conductors)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#71]

**Comment by yuisotozaki** [comment]
Based on the user testing script template in the following reference document, we want to create specific scripts for each user type.
https://documize.pathfinder.gov.bc.ca/s/bkph5eb5fb79okvk8ffg/data-discovery-and-management/d/bp261mnf7ss5649lh7h0/bcdc-uiux-design-notes?currentPageId=bpj6j08kgd7clt4om2eg
