### ISSUE TITLE
Test Introduction Slide Deck (for Test Participants)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#72]

**Comment by yuisotozaki** [comment]
During user testing introduction, we want something for the user to look at. A presentation with the following slides will help users get a grip on the context.
- Introduction
- Background
- Agenda (test session starts after this slide)
- Conclusion/Q&A/Feedback

**Comment by nanyangpro** [comment]
[BCDC User Test Introduction.pptx](https://github.com/bcgov/ckan-ui/files/4416241/BCDC.User.Test.Introduction.pptx)

**Comment by nanyangpro** [comment]
Updated
[BCDC User Test Introduction.pptx](https://github.com/bcgov/ckan-ui/files/4445539/BCDC.User.Test.Introduction.pptx)
