### ISSUE TITLE
About View - Implementation Review (Desktop)

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#78]

**Comment by BrandonSharratt** [comment]
Overall
_Background color should be rgba(0, 0, 0, 0.5)._
Done

_The left and right edges of the card should align with what’s in Header and Footer._
Done

_Border radius should be 0._
Done

**Comment by BrandonSharratt** [comment]
Title Bar
_Background color should be #38598A._
Done

Text should be BC Sans - Regular - 16px - #FFFFFF.
Done

_The distance between the left edge and “About”, and the distance between the right edge and “X” should be the same._
Done

**Comment by BrandonSharratt** [comment]
Main Content
_The left and right edges of the content flow should align with what’s in Header._
Done

_Text should be BC Sans - Regular - 16px - #FFFFFF._
White text wouldn't show up? using #494949 as we discussed others done

_Text links should be BC Sans - Regular - 16px - #1A5A96, no underline._
Done

“Edit” should only be displayed and enabled for system admins.
Done

**Comment by BrandonSharratt** [comment]
Edit Mode
_Background color should be #F2F2F2._
Done

_Input field background color should be #FFFFFF, border 1px solid #CCCCCC, border-radius 0._
Some WYSIWYG handlers are missing, please see the mockup for reference._
Presumably this will happen with the dataset page change

_“Save” button isn’t functioning._
It works if you're logged in

_“Cancel” button background color should be #FFFFFF, border 2px solid #003366, text BC Sans - Regular - 16px - #003366._
Done

**Comment by nanyangpro** [comment]
Notes for @jachurchill and @BrandonSharratt

Items fulfilled from the last round of changes were tested and deleted.
Items still need to be addressed remain.
Newly observed issues are added.

### Overall
- The left and right edges of the card should align with what’s in Header and Footer.
- Border radius should be 0 across different sizes of viewport.

### Title Bar

### Main Content
- Text links should be BC Sans - Regular - 16px - #1A5A96, no underline.

### Edit Mode
- Background color should be #F2F2F2 (please see the mockup for reference and leave no white gaps).
- Input field background color should be #FFFFFF, border 1px solid #CCCCCC, border-radius 0.
- Some WYSIWYG handlers are missing, please see the mockup for reference.
- “Save” button isn’t functioning when logged in, no shadow.
- “Cancel” button background color should be #FFFFFF, border 2px solid #003366, text BC Sans - Regular - 16px - #003366, no shadow.

**Comment by jachurchill** [comment]
Overall
* The left and right edges of the card should align with what’s in Header and Footer.
    * Done
* Border radius should be 0 across different sizes of viewport.

Title Bar
Main Content
* Text links should be BC Sans - Regular - 16px - #1A5A96, no underline.
    * Done

Edit Mode
* Background color should be #F2F2F2 (please see the mockup for reference and leave no white gaps).
    * Done
* Input field background color should be #FFFFFF, border 1px solid #CCCCCC, border-radius 0.
    * This is a shared template with schema based forms, if we do this it does it everywhere
* Some WYSIWYG handlers are missing, please see the mockup for reference.
* “Save” button isn’t functioning when logged in, no shadow.
    * Done
* “Cancel” button background color should be #FFFFFF, border 2px solid #003366, text BC Sans - Regular - 16px - #003366, no shadow.
    * Done

**Comment by SteveChapmanBCDX** [comment]
Ticket completed - closing.
