### ISSUE TITLE
Change word-break property from "break-all" to "normal".

### ISSUE THREAD

**Issue by SteveChapmanBCDX** [bcgov/ckan-ui#85]
Several of the views set the CSS word-break property to "break-all".  This means that words are broken at arbitrary points.

Let's set the property to "normal" instead.

**Action:**
* Audit all files for CSS word-break property; and
* Set the word-break property to "normal"

**Comment by yuisotozaki** [comment]
As of 2020-Dec-16, word-break values are 'normal' on toyger.

**Comment by SteveChapmanBCDX** [comment]
Issue resolved - closing ticket.
