### ISSUE TITLE
Holistic List of Tasks to Complete

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#88]
- Come up with a list of tasks to complete before the usability testing.
- Instead of addressing items view-specifically, notes will be provided holistically.

**Comment by nanyangpro** [comment]
### Tasks to Complete
1. Complete implementation of the Splash View.
2. Revise the copy and order of the fields (and the gray line separators) to match what’s in the mockups.
3. Make sure the background color, text color, font family, font size, border-radius, relative position of the reusable components or components on the same level are consistent across all the key views.
4. Make sure all the buttons/links are functioning as they should when clicked on.
5. Remove the extra white space/gaps on each view.
6. Complete implementation of the tooltips?

### Layout Recommendation
We have this recommendation to work out the overall page margins and spacing to improve the visual balance.
- Use 1150px as maximum edge to edge distance (left edge of the BC Mark PNG and right edge of the menu box).
- Fix the width of the gap bewteen left hand side content and right hand side content to 70px.
- Let the remaining browser space divide equally on the left and right as margins.

### Some examples for point 3 above:
- Dataset, Organization, and Group view's left hand side should all left align the same way.
- Datasets, Dataset, Organization, and Group views' "Back to ..." should all be displayed at the same location.
- All instances of a box with white title in it should use #38598A as the background colour of the box with about 40px height.
- All instances of buttons with icons need to have their icons aligned (e.g. Copy Permalink, View the groups ..., Edit ..., Delete ...)

### Next Steps
- Responsiveness check.

**Comment by nanyangpro** [comment]
### Datasets View with Guides
![Datasets View with Guides](https://user-images.githubusercontent.com/58751681/79804020-01bf7600-8318-11ea-9e0f-86c3e1a3e223.png)
### Dataset View with Guides
![Dataset View with Guides](https://user-images.githubusercontent.com/58751681/79804034-06842a00-8318-11ea-9f2a-87d18ce48ae9.png)
### Resource View with Guides
![Resource View with Guides](https://user-images.githubusercontent.com/58751681/79804050-0f74fb80-8318-11ea-9a00-b506f2ddfc8b.png)
### Organizations View with Guides
![Organizations View with Guides](https://user-images.githubusercontent.com/58751681/79804064-169c0980-8318-11ea-913a-171db3a480ad.png)
### Organization View with Guides
![Organization View with Guides](https://user-images.githubusercontent.com/58751681/79804074-1bf95400-8318-11ea-9d4f-f00b154861d4.png)
### Groups View with Guides
![Groups View with Guides](https://user-images.githubusercontent.com/58751681/79804087-1f8cdb00-8318-11ea-82b6-ce4cad0d7e79.png)
### Group View with Guides
![Group View with Guides](https://user-images.githubusercontent.com/58751681/79804095-23206200-8318-11ea-9321-cdbdfd78f0e6.png)

**Comment by SteveChapmanBCDX** [comment]
@nanyangpro - Thank you for compiling this list.  We will use this list to guide the team's work to prepare the application for user testing.

**Comment by SteveChapmanBCDX** [comment]
@jachurchill - Please review the "Tasks to Complete" list above and add inline comments for the tasks that have been completed (or partly completed).
