### ISSUE TITLE
Functional Review - Consumers

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#91]
### Tasks:
1. Find out more about BC Data Catalogue.
2. Given a specific dataset data file, find it and download the file.
3. Given an organization name and a vague description about a data file, find it and download it.
4. Log in with IDIR.
5. Go back to BCDC home page.
6. Given a dataset name, navigate to it then conduct a new search for another dataset.

### Notes:
- The ellipsis icons on the resource cards of the Dataset View and Resource View don’t work as they should. Instead of displaying a dropdown list, they now bring users directly to the Resource View when clicked on.
- The right column does not always render properly on first rendering.  This often manifests as a header element that is hidden behind the banner.  Refreshing the browser clears this issues.  Example: for the Dataset View, the "Resources" header is concealed behind the Banner.
- “View the group(s) this dataset belongs to” doesn’t work.
- The fixed right section (when containing longer lists) doesn’t scroll and display properly on the Dataset View and Resource View, and thus hides information due to overflow.
- The search functionality doesn’t work and always shows “0 datasets found” after logged in.
- After conducting a search, when accessing the header search bar, the bar content should not contain previous search term(s) - this helps users start a brand new search quickly while being able to review their last search term with the in-content search bar.
- Some data unreachable on toyger via search (e.g. "British Columbia Wildfire Bans and Prohibitions" that should be easily found using "campfire prohibition") The dataset is there but does not show up in the search result.
- 2796 records in toyger vs 2985 in prod.
- Some data reachable on toyger without IDIR login when they are not on prod (e.g. "Avalanche and Weather Programs - Weather and Frost Probe Station Network" is reachable on toyger but not on prod).
- When accessing the Dataset view, the resource UI group is displayed off-screen - reloading the page fixes this.
- Not an issue with the implementation but going back to "home" by clicking on the title rather than the BC logo. Might need a home icon to guide the user better.

**Comment by yuisotozaki** [comment]
All of these issues have been addressed/explained.
