### ISSUE TITLE
Functional Review - Editors

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#92]
**Tasks:**
1. Given a specific dataset name, find it and edit its keywords.
2. Given a specific dataset name, find it and add a new resource.
3. Given a specific dataset name, and resource name, edit its description.
4. Add a new dataset under a predefined organization.
5. Add a dataset to a predefined group.

**Notes:**

**1.  Create Record**

* When an admin fills in only required fields (as denoted by asterisk), form identifies additional fields as "required fields" and blocks submission of form

* Date fields needs better UX => should either have calendar picker or denote required form of date entry prior to inputting data

* Error message is covered by banner ("Validation error - an organization must be provided.")

* Can't create record because cannot populate "Organization" field (Dropdown menu has single item - "no data available")

**2.  Save Record**

* Can't clear submission error ("Please fix the fields in error before submitting")

* Validation error appears even when all fields have been completed.

* Save button UX is weird - when you hit "Save", it does not provide any feedback as to whether you saved the changes or not.  Nor does it navigate out of the record.

**Comment by BrandonSharratt** [comment]
1. Create Record

> When an admin fills in only required fields (as denoted by asterisk), form identifies additional fields as "required fields" and blocks submission of form

There was a bug with a certain type of field in repeating that has been rectified

> Date fields needs better UX => should either have calendar picker or denote required form of date entry prior to inputting data

Done, this broke validation but that has also been fixed

> Error message is covered by banner ("Validation error - an organization must be provided.")

Fixed

> Can't create record because cannot populate "Organization" field (Dropdown menu has single item - "no data available")

This can still happen but is normally rectified by not clicking on the drop down immediately as it can be fetching the information from the server.

2. Save Record

> Can't clear submission error ("Please fix the fields in error before submitting")

It's dismissable so I'm not sure what you mean

> Validation error appears even when all fields have been completed.
This is an error in the migration script John is looking into it will be resolved seperately

> Save button UX is weird - when you hit "Save", it does not provide any feedback as to whether you saved the changes or not. Nor does it navigate out of the record.

It disables the fields, and then provides a success or error message at the top and undisables the field when it finishes. I have made the alert fixed and just below the header, this will be very limited screen space on mobile/small viewports. If you want a "saving please wait" alert or snackbar that can be arranged.

**Comment by SteveChapmanBCDX** [comment]
Changes implemented - closing ticket.
