### ISSUE TITLE
Functional Tests - Admins/System Admins

### ISSUE THREAD

**Issue by nanyangpro** [bcgov/ckan-ui#93]
Tasks:
1. Given a specific organization name, find it and edit its description
2. Add a new organization
3. Add a new group
4. Given a specific user name and group, add the user to the group
5. Given a specific user name and group, remove the user from the group

**Comment by SteveChapmanBCDX** [comment]
Annika and Mike conducted a detailed review of admin/sysadmin functionality.  Annika saved the results to the `DDM_BCDC` Teams channel.  Closing this issues as a duplicate.
